export type DialectSeed = {
  code: string;
  languageCode: string;
  nameEn: string;
  nameNative?: string;
  region?: string;
  cueTerms: string[];
  notes?: string;
};

/**
 * Curated dialect seeds (VL-131) — priority African + related varieties.
 * Not an exhaustive linguistics catalog.
 */
export const DIALECT_SEEDS: DialectSeed[] = [
  // —— Existing ——
  {
    code: 'sw-tz',
    languageCode: 'sw',
    nameEn: 'Tanzanian / coastal Swahili',
    nameNative: 'Kiswahili cha pwani',
    region: 'TZ / coastal East Africa',
    cueTerms: ['sana', 'kwenye', 'labda', 'tafadhali', 'asante sana', 'habari yako'],
    notes: 'Standard coastal-leaning cues; heuristic only.',
  },
  {
    code: 'sw-ke',
    languageCode: 'sw',
    nameEn: 'Kenyan Swahili',
    nameNative: 'Kiswahili cha Kenya',
    region: 'KE',
    cueTerms: ['sasa', 'poa', 'niaje', 'bro', 'uko aje', 'safi'],
    notes: 'Urban Kenyan cues mixed with Sheng-adjacent tokens.',
  },
  {
    code: 'yo-ng',
    languageCode: 'yo',
    nameEn: 'Nigerian Yoruba',
    nameNative: 'Yorùbá',
    region: 'NG',
    cueTerms: ['ẹ káàárọ̀', 'ẹ kú', 'ọmọ', 'jọ̀ọ́', 'béẹ̀ni', 'ràra'],
    notes: 'Common orthographic forms; tone marks optional in matching.',
  },
  {
    code: 'am-et',
    languageCode: 'am',
    nameEn: 'Ethiopian Amharic',
    nameNative: 'አማርኛ',
    region: 'ET',
    cueTerms: ['ሰላም', 'አመሰግናለሁ', 'እባክህ', 'እባክሽ', 'እንደምን'],
    notes: 'Ethiopic-script cues.',
  },
  {
    code: 'ar-eg',
    languageCode: 'ar',
    nameEn: 'Egyptian Arabic',
    nameNative: 'مصري',
    region: 'EG',
    cueTerms: ['ازيك', 'كده', 'مش', 'علشان', 'يعني', 'دلوقتي'],
    notes: 'Colloquial Egyptian cues in Arabic script.',
  },
  {
    code: 'ar-ma',
    languageCode: 'ar',
    nameEn: 'Moroccan Darija',
    nameNative: 'الدارجة',
    region: 'MA',
    cueTerms: ['واش', 'بزاف', 'فين', 'صافي', 'لا باس', 'كيفاش'],
    notes: 'Maghrebi cues; distinct from MSA.',
  },
  {
    code: 'en-ng',
    languageCode: 'en',
    nameEn: 'Nigerian English',
    region: 'NG',
    cueTerms: ['abi', 'na wa', 'how far', 'oya', 'wetin', 'sef'],
    notes: 'Lexical cues only — not accent detection.',
  },
  {
    code: 'en-za',
    languageCode: 'en',
    nameEn: 'South African English',
    region: 'ZA',
    cueTerms: ['lekker', 'braai', 'robot', 'just now', 'sharp sharp', 'howzit'],
    notes: 'Lexical cues only — not accent detection.',
  },
  {
    code: 'ha-ng',
    languageCode: 'ha',
    nameEn: 'Nigerian Hausa',
    nameNative: 'Hausa',
    region: 'NG',
    cueTerms: ['sannu', 'na gode', 'yaya', 'ina kwana', 'lahiya'],
    notes: 'Common greeting/lexical cues.',
  },
  {
    code: 'zu-za',
    languageCode: 'zu',
    nameEn: 'South African Zulu',
    nameNative: 'isiZulu',
    region: 'ZA',
    cueTerms: ['sawubona', 'ngiyabonga', 'unjani', 'yebo', 'cha'],
    notes: 'Common greeting/lexical cues.',
  },
  {
    code: 'af-za',
    languageCode: 'af',
    nameEn: 'South African Afrikaans',
    nameNative: 'Afrikaans',
    region: 'ZA',
    cueTerms: ['dankie', 'asseblief', 'hoe gaan dit', 'baie', 'lekker'],
    notes: 'Common lexical cues.',
  },

  // —— Ghana ——
  {
    code: 'ak-gh',
    languageCode: 'ak',
    nameEn: 'Ghanaian Akan',
    nameNative: 'Akan',
    region: 'GH',
    cueTerms: ['maakye', 'medaase', 'wo ho te sɛn', 'yɛ', 'aane', 'daabi'],
    notes: 'Akan greeting/lexical cues; covers Twi-adjacent forms.',
  },
  {
    code: 'tw-gh',
    languageCode: 'tw',
    nameEn: 'Ghanaian Twi',
    nameNative: 'Twi',
    region: 'GH',
    cueTerms: ['maakye', 'medaase', 'ɛte sɛn', 'me pɛ', 'yoo', 'dabi'],
    notes: 'Twi lexical cues.',
  },
  {
    code: 'ee-gh',
    languageCode: 'ee',
    nameEn: 'Ghanaian Ewe',
    nameNative: 'Eʋegbe',
    region: 'GH',
    cueTerms: ['ŋdi', 'akpe', 'efɔ̃a', 'ẽ', 'ao', 'míawo'],
    notes: 'Ewe greeting/lexical cues.',
  },
  {
    code: 'gaa-gh',
    languageCode: 'gaa',
    nameEn: 'Ghanaian Ga',
    nameNative: 'Gã',
    region: 'GH',
    cueTerms: ['ojekoo', 'oyiwala don', 'te oyɔ', 'hãã', 'dao', 'miishɛ'],
    notes: 'Ga lexical cues.',
  },
  {
    code: 'dag-gh',
    languageCode: 'dag',
    nameEn: 'Ghanaian Dagbani',
    nameNative: 'Dagbani',
    region: 'GH',
    cueTerms: ['desiba', 'mpaɣya', 'a wuhima', 'mm', 'ayi', 'naa'],
    notes: 'Dagbani greeting/lexical cues.',
  },
  {
    code: 'en-gh',
    languageCode: 'en',
    nameEn: 'Ghanaian English',
    region: 'GH',
    cueTerms: ['chale', 'paa', 'charley', 'small small', 'please', 'eh'],
    notes: 'Lexical cues only — not accent detection.',
  },

  // —— South Africa ——
  {
    code: 'xh-za',
    languageCode: 'xh',
    nameEn: 'South African Xhosa',
    nameNative: 'isiXhosa',
    region: 'ZA',
    cueTerms: ['molo', 'enkosi', 'unjani', 'ewe', 'hayi', 'ndiyabulela'],
    notes: 'Common greeting/lexical cues.',
  },
  {
    code: 'nso-za',
    languageCode: 'nso',
    nameEn: 'South African Northern Sotho',
    nameNative: 'Sesotho sa Leboa',
    region: 'ZA',
    cueTerms: ['thobela', 'ke a leboga', 'o kae', 'ee', 'aowa'],
    notes: 'Sepedi lexical cues.',
  },
  {
    code: 'tn-za',
    languageCode: 'tn',
    nameEn: 'South African Tswana',
    nameNative: 'Setswana',
    region: 'ZA',
    cueTerms: ['dumela', 'ke a leboga', 'o tsogile jang', 'ee', 'nyaa'],
    notes: 'Setswana lexical cues.',
  },
  {
    code: 'st-za',
    languageCode: 'st',
    nameEn: 'South African Southern Sotho',
    nameNative: 'Sesotho',
    region: 'ZA',
    cueTerms: ['dumela', 'kea leboha', 'u phela joang', 'e', 'tjhe'],
    notes: 'Sesotho lexical cues.',
  },
  {
    code: 'ss-za',
    languageCode: 'ss',
    nameEn: 'South African / Swazi Swati',
    nameNative: 'siSwati',
    region: 'ZA / SZ',
    cueTerms: ['sawubona', 'ngiyabonga', 'unjani', 'yebo', 'cha'],
    notes: 'siSwati lexical cues.',
  },
  {
    code: 'ts-za',
    languageCode: 'ts',
    nameEn: 'South African Tsonga',
    nameNative: 'Xitsonga',
    region: 'ZA',
    cueTerms: ['avuxeni', 'ndza khensa', 'ku njhani', 'ina', 'e-e'],
    notes: 'Xitsonga lexical cues.',
  },
  {
    code: 've-za',
    languageCode: 've',
    nameEn: 'South African Venda',
    nameNative: 'Tshivenḓa',
    region: 'ZA',
    cueTerms: ['ndaa', 'ndo livhuwa', 'vha vhona hani', 'ee', 'hai'],
    notes: 'Tshivenḓa lexical cues.',
  },
  {
    code: 'nr-za',
    languageCode: 'nr',
    nameEn: 'South African Southern Ndebele',
    nameNative: 'isiNdebele',
    region: 'ZA',
    cueTerms: ['lotjhani', 'ngiyathokoza', 'unjani', 'yebo', 'azi'],
    notes: 'Southern Ndebele lexical cues.',
  },

  // —— East / Horn ——
  {
    code: 'lg-ug',
    languageCode: 'lg',
    nameEn: 'Ugandan Luganda',
    nameNative: 'Luganda',
    region: 'UG',
    cueTerms: ['gyebaleko', 'weebale', 'oli otya', 'ye', 'nedda', 'webale nnyo'],
    notes: 'Luganda greeting/lexical cues.',
  },
  {
    code: 'rw-rw',
    languageCode: 'rw',
    nameEn: 'Rwandan Kinyarwanda',
    nameNative: 'Ikinyarwanda',
    region: 'RW',
    cueTerms: ['muraho', 'murakoze', 'amakuru', 'yego', 'oya'],
    notes: 'Kinyarwanda lexical cues.',
  },
  {
    code: 'rn-bi',
    languageCode: 'rn',
    nameEn: 'Burundian Kirundi',
    nameNative: 'Ikirundi',
    region: 'BI',
    cueTerms: ['bwasaha', 'urakoze', 'amakuru', 'ego', 'oya'],
    notes: 'Kirundi lexical cues.',
  },
  {
    code: 'so-so',
    languageCode: 'so',
    nameEn: 'Somali (Somalia)',
    nameNative: 'Soomaali',
    region: 'SO',
    cueTerms: ['salaan', 'mahadsanid', 'sidee tahay', 'haa', 'maya', 'waad mahadsantahay'],
    notes: 'Somali lexical cues.',
  },
  {
    code: 'om-et',
    languageCode: 'om',
    nameEn: 'Ethiopian Oromo',
    nameNative: 'Afaan Oromoo',
    region: 'ET',
    cueTerms: ['akkam', 'galatoomi', 'nagaa', 'eeyyee', 'lakki'],
    notes: 'Oromo lexical cues.',
  },
  {
    code: 'ti-er',
    languageCode: 'ti',
    nameEn: 'Eritrean Tigrinya',
    nameNative: 'ትግርኛ',
    region: 'ER',
    cueTerms: ['ሰላም', 'የቐንየለይ', 'ከመይ', 'እወ', 'ኣይኮንን'],
    notes: 'Ethiopic-script Tigrinya cues.',
  },

  // —— North Africa ——
  {
    code: 'ar-tn',
    languageCode: 'ar',
    nameEn: 'Tunisian Arabic',
    nameNative: 'تونسي',
    region: 'TN',
    cueTerms: ['علاش', 'برشا', 'شنوة', 'باهي', 'اي', 'لي'],
    notes: 'Tunisian Darija cues.',
  },
  {
    code: 'ar-dz',
    languageCode: 'ar',
    nameEn: 'Algerian Arabic',
    nameNative: 'دزيرية',
    region: 'DZ',
    cueTerms: ['واش', 'بزاف', 'كي راك', 'صح', 'لا', 'راني'],
    notes: 'Algerian Darija cues.',
  },
  {
    code: 'ar-ly',
    languageCode: 'ar',
    nameEn: 'Libyan Arabic',
    nameNative: 'ليبي',
    region: 'LY',
    cueTerms: ['كيفك', 'هكي', 'وين', 'ايوة', 'لا', 'زين'],
    notes: 'Libyan Arabic cues.',
  },
  {
    code: 'ber-ma',
    languageCode: 'ber',
    nameEn: 'Moroccan Tamazight (macro)',
    nameNative: 'Tamaziɣt',
    region: 'MA',
    cueTerms: ['azul', 'tanemmirt', 'mandeɣ', 'yah', 'uhu'],
    notes: 'Macro Amazigh cues; prefer tzm/shi where known.',
  },
  {
    code: 'tzm-ma',
    languageCode: 'tzm',
    nameEn: 'Central Atlas Tamazight (Morocco)',
    nameNative: 'Tamaziɣt',
    region: 'MA',
    cueTerms: ['azul', 'tanemmirt', 'mliḥ', 'yah', 'uhu', 'tifawt'],
    notes: 'Central Atlas Tamazight lexical cues.',
  },

  // —— West Africa ——
  {
    code: 'ig-ng',
    languageCode: 'ig',
    nameEn: 'Nigerian Igbo',
    nameNative: 'Igbo',
    region: 'NG',
    cueTerms: ['kedu', 'daalụ', 'ndewo', 'ee', 'mba', 'biko'],
    notes: 'Igbo greeting/lexical cues.',
  },
  {
    code: 'wo-sn',
    languageCode: 'wo',
    nameEn: 'Senegalese Wolof',
    nameNative: 'Wolof',
    region: 'SN',
    cueTerms: ['nanga def', 'jërëjëf', 'waaw', 'déédéét', 'salaam aleekum'],
    notes: 'Wolof lexical cues.',
  },
  {
    code: 'bm-ml',
    languageCode: 'bm',
    nameEn: 'Malian Bambara',
    nameNative: 'Bamanankan',
    region: 'ML',
    cueTerms: ['i ni ce', 'i ni sogoma', 'aw ni baara', 'awɔ', 'ayiwa'],
    notes: 'Bambara greeting/lexical cues.',
  },
  {
    code: 'ff-sn',
    languageCode: 'ff',
    nameEn: 'Senegalese Pulaar',
    nameNative: 'Pulaar',
    region: 'SN',
    cueTerms: ['jam tan', 'a jaaraama', 'no mbadda', 'ey', 'alaa'],
    notes: 'Pulaar lexical cues.',
  },
  {
    code: 'ff-ng',
    languageCode: 'ff',
    nameEn: 'Nigerian Fulfulde',
    nameNative: 'Fulfulde',
    region: 'NG',
    cueTerms: ['sannu', 'a jaraama', 'noy', 'eyi', 'alaa'],
    notes: 'Nigerian Fulfulde lexical cues.',
  },
  {
    code: 'yo-bj',
    languageCode: 'yo',
    nameEn: 'Beninese Yoruba',
    nameNative: 'Yorùbá',
    region: 'BJ',
    cueTerms: ['ẹ káàárọ̀', 'ẹ kú', 'báwo', 'béẹ̀ni', 'ràra'],
    notes: 'Yoruba in Benin border communities.',
  },

  // —— Central ——
  {
    code: 'ln-cd',
    languageCode: 'ln',
    nameEn: 'DRC Lingala',
    nameNative: 'Lingála',
    region: 'CD',
    cueTerms: ['mbote', 'merci mingi', 'ozali malamu', 'iyo', 'te'],
    notes: 'Lingala lexical cues (Kinshasa-leaning).',
  },
  {
    code: 'ln-cg',
    languageCode: 'ln',
    nameEn: 'Congo-Brazzaville Lingala',
    nameNative: 'Lingála',
    region: 'CG',
    cueTerms: ['mbote', 'matondo', 'sango nini', 'ee', 'te'],
    notes: 'Lingala lexical cues (Brazzaville-leaning).',
  },
  {
    code: 'swc-cd',
    languageCode: 'swc',
    nameEn: 'Congo Swahili',
    nameNative: 'Kiswahili ya Kongo',
    region: 'CD',
    cueTerms: ['jambo', 'asante', 'habari', 'ndiyo', 'hapana', 'karibu'],
    notes: 'Eastern DRC Swahili cues; distinct from coastal standards.',
  },

  // —— Southern ——
  {
    code: 'ny-mw',
    languageCode: 'ny',
    nameEn: 'Malawian Chichewa',
    nameNative: 'Chichewa',
    region: 'MW',
    cueTerms: ['moni', 'zikomo', 'muli bwanji', 'inde', 'ayi'],
    notes: 'Chichewa lexical cues.',
  },
  {
    code: 'sn-zw',
    languageCode: 'sn',
    nameEn: 'Zimbabwean Shona',
    nameNative: 'chiShona',
    region: 'ZW',
    cueTerms: ['mhoro', 'ndatenda', 'makadii', 'hongu', 'kwete'],
    notes: 'Shona lexical cues.',
  },
  {
    code: 'tn-bw',
    languageCode: 'tn',
    nameEn: 'Botswana Tswana',
    nameNative: 'Setswana',
    region: 'BW',
    cueTerms: ['dumela', 'ke a leboga', 'o tsogile jang', 'ee', 'nyaa'],
    notes: 'Botswana Setswana lexical cues.',
  },
  {
    code: 'st-ls',
    languageCode: 'st',
    nameEn: 'Lesotho Sesotho',
    nameNative: 'Sesotho',
    region: 'LS',
    cueTerms: ['dumela', 'kea leboha', 'u phela joang', 'e', 'tjhe'],
    notes: 'Lesotho Sesotho lexical cues.',
  },
];
