export type AiInternetSeed = {
  domain: string;
  kind: string;
  title: string;
  status: string;
  summary: string;
  ownerLabel: string;
  content: Record<string, unknown>;
};

export function aiInternetDefaultSeeds(): AiInternetSeed[] {
  return [
    {
      domain: 'foundation',
      kind: 'dns',
      title: 'AI DNS - sample',
      status: 'active',
      summary: 'AI Internet sample record.',
      ownerLabel: 'AI Internet Ops',
      content: { ownedModels: true, runsGlobalAiInternet: false },
    },
    {
      domain: 'foundation',
      kind: 'identity',
      title: 'AI Identity - sample',
      status: 'active',
      summary: 'AI Internet sample record.',
      ownerLabel: 'AI Internet Ops',
      content: { ownedModels: true, runsGlobalAiInternet: false },
    },
    {
      domain: 'dns',
      kind: 'record',
      title: 'AI name record - sample',
      status: 'active',
      summary: 'AI DNS sample record.',
      ownerLabel: 'AI Internet Ops',
      content: { ownedModels: true, runsGlobalAiInternet: false },
    },
    {
      domain: 'dns',
      kind: 'resolve',
      title: 'Resolve AI name - sample',
      status: 'active',
      summary: 'AI DNS sample record.',
      ownerLabel: 'AI Internet Ops',
      content: { ownedModels: true, runsGlobalAiInternet: false },
    },
    {
      domain: 'identity',
      kind: 'wallet',
      title: 'Identity wallet - sample',
      status: 'active',
      summary: 'AI Identity Wallet sample record.',
      ownerLabel: 'AI Internet Ops',
      content: { ownedModels: true, runsGlobalAiInternet: false },
    },
    {
      domain: 'identity',
      kind: 'credential',
      title: 'AI credential - sample',
      status: 'active',
      summary: 'AI Identity Wallet sample record.',
      ownerLabel: 'AI Internet Ops',
      content: { ownedModels: true, runsGlobalAiInternet: false },
    },
    {
      domain: 'discovery',
      kind: 'service',
      title: 'Service discovery entry - sample',
      status: 'active',
      summary: 'AI Discovery sample record.',
      ownerLabel: 'AI Internet Ops',
      content: { ownedModels: true, runsGlobalAiInternet: false },
    },
    {
      domain: 'discovery',
      kind: 'capability',
      title: 'Capability registry entry - sample',
      status: 'active',
      summary: 'AI Discovery sample record.',
      ownerLabel: 'AI Internet Ops',
      content: { ownedModels: true, runsGlobalAiInternet: false },
    },
    {
      domain: 'federation',
      kind: 'model_federation',
      title: 'Model federation link - sample',
      status: 'active',
      summary: 'AI Federation Mesh sample record.',
      ownerLabel: 'AI Internet Ops',
      content: { ownedModels: true, runsGlobalAiInternet: false },
    },
    {
      domain: 'federation',
      kind: 'runtime_federation',
      title: 'Runtime federation link - sample',
      status: 'active',
      summary: 'AI Federation Mesh sample record.',
      ownerLabel: 'AI Internet Ops',
      content: { ownedModels: true, runsGlobalAiInternet: false },
    },
    {
      domain: 'a2a',
      kind: 'session',
      title: 'A2A session - sample',
      status: 'active',
      summary: 'A2A Protocol sample record.',
      ownerLabel: 'AI Internet Ops',
      content: { ownedModels: true, runsGlobalAiInternet: false },
    },
    {
      domain: 'a2a',
      kind: 'message',
      title: 'Cross-platform message - sample',
      status: 'active',
      summary: 'A2A Protocol sample record.',
      ownerLabel: 'AI Internet Ops',
      content: { ownedModels: true, runsGlobalAiInternet: false },
    },
    {
      domain: 'trust',
      kind: 'trust_edge',
      title: 'Trust edge - sample',
      status: 'active',
      summary: 'AI Trust Network sample record.',
      ownerLabel: 'AI Internet Ops',
      content: { ownedModels: true, runsGlobalAiInternet: false },
    },
    {
      domain: 'trust',
      kind: 'reputation',
      title: 'Reputation score - sample',
      status: 'active',
      summary: 'AI Trust Network sample record.',
      ownerLabel: 'AI Internet Ops',
      content: { ownedModels: true, runsGlobalAiInternet: false },
    },
    {
      domain: 'payments',
      kind: 'payment_intent',
      title: 'AI payment intent - sample',
      status: 'active',
      summary: 'AI Payment Network sample record.',
      ownerLabel: 'AI Internet Ops',
      content: { ownedModels: true, runsGlobalAiInternet: false },
    },
    {
      domain: 'payments',
      kind: 'contract',
      title: 'AI contract - sample',
      status: 'active',
      summary: 'AI Payment Network sample record.',
      ownerLabel: 'AI Internet Ops',
      content: { ownedModels: true, runsGlobalAiInternet: false },
    },
    {
      domain: 'ca',
      kind: 'certificate',
      title: 'AI certificate - sample',
      status: 'active',
      summary: 'AI Certificate Authority sample record.',
      ownerLabel: 'AI Internet Ops',
      content: { ownedModels: true, runsGlobalAiInternet: false },
    },
    {
      domain: 'ca',
      kind: 'csr',
      title: 'Certificate request - sample',
      status: 'active',
      summary: 'AI Certificate Authority sample record.',
      ownerLabel: 'AI Internet Ops',
      content: { ownedModels: true, runsGlobalAiInternet: false },
    },
    {
      domain: 'routing',
      kind: 'route',
      title: 'Global route - sample',
      status: 'active',
      summary: 'AI Global Routing sample record.',
      ownerLabel: 'AI Internet Ops',
      content: { ownedModels: true, runsGlobalAiInternet: false },
    },
    {
      domain: 'routing',
      kind: 'edge_peer',
      title: 'Edge federation peer - sample',
      status: 'active',
      summary: 'AI Global Routing sample record.',
      ownerLabel: 'AI Internet Ops',
      content: { ownedModels: true, runsGlobalAiInternet: false },
    },
    {
      domain: 'governance',
      kind: 'policy_bundle',
      title: 'Federated policy bundle - sample',
      status: 'active',
      summary: 'AI Governance Federation sample record.',
      ownerLabel: 'AI Internet Ops',
      content: { ownedModels: true, runsGlobalAiInternet: false },
    },
    {
      domain: 'governance',
      kind: 'compliance_pack',
      title: 'Compliance exchange pack - sample',
      status: 'active',
      summary: 'AI Governance Federation sample record.',
      ownerLabel: 'AI Internet Ops',
      content: { ownedModels: true, runsGlobalAiInternet: false },
    },
    {
      domain: 'sovereignty',
      kind: 'sovereignty_claim',
      title: 'Sovereignty claim - sample',
      status: 'active',
      summary: 'AI Sovereignty Exchange sample record.',
      ownerLabel: 'AI Internet Ops',
      content: { ownedModels: true, runsGlobalAiInternet: false },
    },
    {
      domain: 'sovereignty',
      kind: 'policy_exchange',
      title: 'Policy exchange - sample',
      status: 'active',
      summary: 'AI Sovereignty Exchange sample record.',
      ownerLabel: 'AI Internet Ops',
      content: { ownedModels: true, runsGlobalAiInternet: false },
    },
    {
      domain: 'marketplace',
      kind: 'listing_sync',
      title: 'Listing sync - sample',
      status: 'active',
      summary: 'AI Marketplace Federation sample record.',
      ownerLabel: 'AI Internet Ops',
      content: { ownedModels: true, runsGlobalAiInternet: false },
    },
    {
      domain: 'marketplace',
      kind: 'catalog_peer',
      title: 'Catalog peer - sample',
      status: 'active',
      summary: 'AI Marketplace Federation sample record.',
      ownerLabel: 'AI Internet Ops',
      content: { ownedModels: true, runsGlobalAiInternet: false },
    },
    {
      domain: 'global_os',
      kind: 'os_profile',
      title: 'Global OS profile - sample',
      status: 'active',
      summary: 'VerbaLab Global OS sample record.',
      ownerLabel: 'AI Internet Ops',
      content: { ownedModels: true, runsGlobalAiInternet: false },
    },
    {
      domain: 'global_os',
      kind: 'runtime_plane',
      title: 'Runtime plane - sample',
      status: 'active',
      summary: 'VerbaLab Global OS sample record.',
      ownerLabel: 'AI Internet Ops',
      content: { ownedModels: true, runsGlobalAiInternet: false },
    },
    {
      domain: 'credentials',
      kind: 'stripe',
      title: 'Stripe keys - sample',
      status: 'active',
      summary: 'Credentials Readiness sample record.',
      ownerLabel: 'AI Internet Ops',
      content: { ownedModels: true, runsGlobalAiInternet: false },
    },
    {
      domain: 'credentials',
      kind: 'clerk',
      title: 'Clerk keys - sample',
      status: 'active',
      summary: 'Credentials Readiness sample record.',
      ownerLabel: 'AI Internet Ops',
      content: { ownedModels: true, runsGlobalAiInternet: false },
    },
  ];
}
