export type CountryPackSeed = {
  code: string;
  nameEn: string;
  region: string;
  currencyCode: string;
  primaryLanguages: string[];
  bcp47Tags: string[];
  relatedDialectCodes?: string[];
  relatedAccentCodes?: string[];
  dateNotes: string;
  numberNotes: string;
  currencyNotes: string;
  culturalNotes: string;
};

/**
 * Curated African-priority country packs (VL-135).
 * All AU member states — major spoken languages, not an Ethnologue dump.
 */
export const COUNTRY_PACK_SEEDS: CountryPackSeed[] = [
  // —— Existing packs (deepened) ——
  {
    code: 'KE',
    nameEn: 'Kenya',
    region: 'East Africa',
    currencyCode: 'KES',
    primaryLanguages: ['sw', 'en', 'ki', 'luo', 'kam', 'guz', 'mer', 'kln', 'luy', 'mas'],
    bcp47Tags: ['sw-KE', 'en-KE', 'ki-KE', 'luo-KE'],
    relatedDialectCodes: ['sw-ke'],
    relatedAccentCodes: ['sw-ke', 'en-ke'],
    dateNotes: 'DMY common in administration; ISO 8601 for APIs.',
    numberNotes: 'Arabic digits; prefer consistent thousand separators in product UI.',
    currencyNotes: 'Kenyan shilling (KSh / KES).',
    culturalNotes: 'Swahili + English bilingual contexts; Sheng-influenced urban Swahili may appear in informal copy.',
  },
  {
    code: 'TZ',
    nameEn: 'Tanzania',
    region: 'East Africa',
    currencyCode: 'TZS',
    primaryLanguages: ['sw', 'en', 'suk', 'hay', 'nym', 'gog', 'heh', 'mas'],
    bcp47Tags: ['sw-TZ', 'en-TZ'],
    relatedDialectCodes: ['sw-tz'],
    relatedAccentCodes: ['en-tz'],
    dateNotes: 'DMY; Monday week start common in formal contexts.',
    numberNotes: 'Arabic digits; align with sw locale pack formatting.',
    currencyNotes: 'Tanzanian shilling (TSh / TZS).',
    culturalNotes: 'Coastal Swahili norms; respectful address (Mheshimiwa) in public-sector copy.',
  },
  {
    code: 'NG',
    nameEn: 'Nigeria',
    region: 'West Africa',
    currencyCode: 'NGN',
    primaryLanguages: ['en', 'yo', 'ha', 'ig', 'ff', 'kr', 'pcm', 'tiv', 'ibb', 'efi', 'bin'],
    bcp47Tags: ['en-NG', 'yo-NG', 'ha-NG', 'ig-NG', 'ff-NG', 'pcm-NG'],
    relatedDialectCodes: ['en-ng', 'yo-ng', 'ha-ng', 'ig-ng', 'ff-ng'],
    relatedAccentCodes: ['en-ng', 'ha-ng', 'yo-ng', 'ig-ng'],
    dateNotes: 'DMY common in administration.',
    numberNotes: 'Arabic digits; naira amounts often use ₦.',
    currencyNotes: 'Nigerian naira (₦ / NGN).',
    culturalNotes: 'Multilingual federation; tone marks matter in formal Yoruba; English and Pidgin are bridge varieties.',
  },
  {
    code: 'GH',
    nameEn: 'Ghana',
    region: 'West Africa',
    currencyCode: 'GHS',
    primaryLanguages: ['en', 'ak', 'tw', 'ee', 'gaa', 'dag', 'ada', 'nzi', 'gjn', 'xsm', 'fat'],
    bcp47Tags: ['en-GH', 'ak-GH', 'tw-GH', 'ee-GH', 'gaa-GH', 'dag-GH'],
    relatedDialectCodes: ['en-gh', 'ak-gh', 'tw-gh', 'ee-gh', 'gaa-gh', 'dag-gh'],
    relatedAccentCodes: ['en-gh', 'ak-gh', 'ee-gh'],
    dateNotes: 'DMY common.',
    numberNotes: 'Arabic digits.',
    currencyNotes: 'Ghanaian cedi (GH₵ / GHS).',
    culturalNotes: 'English official; Akan/Twi, Ewe, Ga, and Dagbani are major community languages — keep brand names stable.',
  },
  {
    code: 'ZA',
    nameEn: 'South Africa',
    region: 'Southern Africa',
    currencyCode: 'ZAR',
    primaryLanguages: ['en', 'zu', 'xh', 'af', 'nso', 'tn', 'st', 'ts', 'ss', 've', 'nr'],
    bcp47Tags: ['en-ZA', 'zu-ZA', 'xh-ZA', 'af-ZA', 'nso-ZA', 'tn-ZA', 'st-ZA', 'ts-ZA', 'ss-ZA', 've-ZA', 'nr-ZA'],
    relatedDialectCodes: ['en-za', 'zu-za', 'af-za', 'xh-za', 'nso-za', 'tn-za', 'st-za', 'ss-za', 'ts-za', 've-za', 'nr-za'],
    relatedAccentCodes: ['en-za', 'zu-za', 'af-za', 'xh-za'],
    dateNotes: 'YMD often in formal/business; DMY also appears — prefer ISO in APIs.',
    numberNotes: 'Space or comma thousands; period decimal in many EN contexts.',
    currencyNotes: 'South African rand (R / ZAR).',
    culturalNotes: 'Eleven official languages; English, isiZulu, isiXhosa, and Afrikaans are common product targets.',
  },
  {
    code: 'EG',
    nameEn: 'Egypt',
    region: 'North Africa',
    currencyCode: 'EGP',
    primaryLanguages: ['ar'],
    bcp47Tags: ['ar-EG'],
    relatedDialectCodes: ['ar-eg'],
    relatedAccentCodes: ['ar-eg'],
    dateNotes: 'DMY; Hijri may appear in cultural contexts — keep civil Gregorian for APIs.',
    numberNotes: 'Arabic-Indic or Western digits depending on audience; prefer Western digits in APIs.',
    currencyNotes: 'Egyptian pound (E£ / EGP).',
    culturalNotes: 'Egyptian Arabic differs from MSA; RTL layout required for Arabic UI.',
  },
  {
    code: 'MA',
    nameEn: 'Morocco',
    region: 'North Africa',
    currencyCode: 'MAD',
    primaryLanguages: ['ar', 'fr', 'tzm', 'shi', 'zgh', 'ber', 'rif'],
    bcp47Tags: ['ar-MA', 'fr-MA', 'tzm-MA', 'shi-MA', 'zgh-MA'],
    relatedDialectCodes: ['ar-ma', 'ber-ma', 'tzm-ma'],
    relatedAccentCodes: ['ar-ma', 'fr-ma'],
    dateNotes: 'DMY common in French/Arabic admin contexts.',
    numberNotes: 'French-influenced decimal comma may appear in FR copy.',
    currencyNotes: 'Moroccan dirham (MAD).',
    culturalNotes: 'Darija + French bilingual markets; Tamazight official; MSA for formal Arabic.',
  },
  {
    code: 'SN',
    nameEn: 'Senegal',
    region: 'West Africa',
    currencyCode: 'XOF',
    primaryLanguages: ['fr', 'wo', 'ff', 'mnk', 'snk'],
    bcp47Tags: ['fr-SN', 'wo-SN', 'ff-SN'],
    relatedDialectCodes: ['wo-sn', 'ff-sn'],
    relatedAccentCodes: ['fr-sn', 'wo-sn'],
    dateNotes: 'DMY (French).',
    numberNotes: 'French decimal comma conventions in FR copy.',
    currencyNotes: 'West African CFA franc (XOF).',
    culturalNotes: 'French official; Wolof strongly present in spoken contexts; Pulaar and Mandinka widely used.',
  },
  {
    code: 'CI',
    nameEn: 'Côte d’Ivoire',
    region: 'West Africa',
    currencyCode: 'XOF',
    primaryLanguages: ['fr', 'dyu', 'bci', 'any', 'sef', 'dnj'],
    bcp47Tags: ['fr-CI', 'dyu-CI', 'bci-CI'],
    relatedDialectCodes: [],
    relatedAccentCodes: ['fr-ci'],
    dateNotes: 'DMY (French).',
    numberNotes: 'French decimal conventions in FR copy.',
    currencyNotes: 'West African CFA franc (XOF).',
    culturalNotes: 'French official; Dyula and Baoulé widely spoken; Nouchi influences informal speech.',
  },
  {
    code: 'ET',
    nameEn: 'Ethiopia',
    region: 'Horn of Africa',
    currencyCode: 'ETB',
    primaryLanguages: ['am', 'om', 'ti', 'so', 'aa', 'sid', 'wal', 'en'],
    bcp47Tags: ['am-ET', 'om-ET', 'ti-ET', 'so-ET', 'en-ET'],
    relatedDialectCodes: ['am-et', 'om-et'],
    relatedAccentCodes: ['am-et'],
    dateNotes: 'Ethiopian calendar may appear culturally; use Gregorian ISO in APIs.',
    numberNotes: 'Arabic digits in Latin UI; Ethiopic script for Amharic/Tigrinya.',
    currencyNotes: 'Ethiopian birr (Br / ETB).',
    culturalNotes: 'Amharic federal working language; Oromo largest mother tongue; script fidelity matters.',
  },

  // —— North Africa ——
  {
    code: 'DZ',
    nameEn: 'Algeria',
    region: 'North Africa',
    currencyCode: 'DZD',
    primaryLanguages: ['ar', 'fr', 'kab', 'ber'],
    bcp47Tags: ['ar-DZ', 'fr-DZ', 'kab-DZ'],
    relatedDialectCodes: ['ar-dz'],
    relatedAccentCodes: ['fr-dz'],
    dateNotes: 'DMY common.',
    numberNotes: 'French decimal conventions often in FR copy.',
    currencyNotes: 'Algerian dinar (DZD).',
    culturalNotes: 'Arabic and Tamazight official; French widely used in administration and business.',
  },
  {
    code: 'TN',
    nameEn: 'Tunisia',
    region: 'North Africa',
    currencyCode: 'TND',
    primaryLanguages: ['ar', 'fr'],
    bcp47Tags: ['ar-TN', 'fr-TN'],
    relatedDialectCodes: ['ar-tn'],
    relatedAccentCodes: [],
    dateNotes: 'DMY common.',
    numberNotes: 'Western digits common in digital UI.',
    currencyNotes: 'Tunisian dinar (TND).',
    culturalNotes: 'Tunisian Arabic (Darija) differs from MSA; French common in business.',
  },
  {
    code: 'LY',
    nameEn: 'Libya',
    region: 'North Africa',
    currencyCode: 'LYD',
    primaryLanguages: ['ar'],
    bcp47Tags: ['ar-LY'],
    relatedDialectCodes: ['ar-ly'],
    relatedAccentCodes: [],
    dateNotes: 'DMY; Gregorian for APIs.',
    numberNotes: 'Western digits preferred in APIs.',
    currencyNotes: 'Libyan dinar (LYD).',
    culturalNotes: 'Arabic official; RTL required for Arabic UI.',
  },
  {
    code: 'SD',
    nameEn: 'Sudan',
    region: 'East Africa',
    currencyCode: 'SDG',
    primaryLanguages: ['ar', 'en', 'fvr', 'zag', 'mls'],
    bcp47Tags: ['ar-SD', 'en-SD'],
    relatedDialectCodes: [],
    relatedAccentCodes: [],
    dateNotes: 'DMY common.',
    numberNotes: 'Arabic or Western digits by audience.',
    currencyNotes: 'Sudanese pound (SDG).',
    culturalNotes: 'Arabic dominant; multiple Nilo-Saharan languages in Darfur and border regions.',
  },

  // —— Horn ——
  {
    code: 'SO',
    nameEn: 'Somalia',
    region: 'Horn of Africa',
    currencyCode: 'SOS',
    primaryLanguages: ['so', 'ar'],
    bcp47Tags: ['so-SO', 'ar-SO'],
    relatedDialectCodes: ['so-so'],
    relatedAccentCodes: ['so-so'],
    dateNotes: 'DMY common.',
    numberNotes: 'Arabic digits.',
    currencyNotes: 'Somali shilling (SOS).',
    culturalNotes: 'Somali official with Arabic; Latin orthography for Somali is standard in digital products.',
  },
  {
    code: 'DJ',
    nameEn: 'Djibouti',
    region: 'Horn of Africa',
    currencyCode: 'DJF',
    primaryLanguages: ['fr', 'ar', 'so', 'aa'],
    bcp47Tags: ['fr-DJ', 'ar-DJ', 'so-DJ', 'aa-DJ'],
    relatedDialectCodes: [],
    relatedAccentCodes: [],
    dateNotes: 'DMY (French admin).',
    numberNotes: 'French decimal conventions in FR copy.',
    currencyNotes: 'Djiboutian franc (DJF).',
    culturalNotes: 'French and Arabic official; Somali and Afar widely spoken.',
  },
  {
    code: 'ER',
    nameEn: 'Eritrea',
    region: 'Horn of Africa',
    currencyCode: 'ERN',
    primaryLanguages: ['ti', 'ar', 'en', 'tig', 'aa'],
    bcp47Tags: ['ti-ER', 'ar-ER', 'en-ER'],
    relatedDialectCodes: ['ti-er'],
    relatedAccentCodes: [],
    dateNotes: 'DMY; Gregorian for APIs.',
    numberNotes: 'Arabic digits in Latin UI; Ethiopic for Tigrinya.',
    currencyNotes: 'Eritrean nakfa (ERN).',
    culturalNotes: 'Tigrinya widely used; Arabic and English also official working languages.',
  },

  // —— West Africa ——
  {
    code: 'BJ',
    nameEn: 'Benin',
    region: 'West Africa',
    currencyCode: 'XOF',
    primaryLanguages: ['fr', 'fon', 'yo', 'bba'],
    bcp47Tags: ['fr-BJ', 'fon-BJ', 'yo-BJ'],
    relatedDialectCodes: ['yo-bj'],
    relatedAccentCodes: [],
    dateNotes: 'DMY (French).',
    numberNotes: 'French decimal conventions.',
    currencyNotes: 'West African CFA franc (XOF).',
    culturalNotes: 'French official; Fon and Yoruba major national languages.',
  },
  {
    code: 'BF',
    nameEn: 'Burkina Faso',
    region: 'West Africa',
    currencyCode: 'XOF',
    primaryLanguages: ['fr', 'mos', 'dyu', 'ff'],
    bcp47Tags: ['fr-BF', 'mos-BF', 'dyu-BF'],
    relatedDialectCodes: [],
    relatedAccentCodes: [],
    dateNotes: 'DMY (French).',
    numberNotes: 'French decimal conventions.',
    currencyNotes: 'West African CFA franc (XOF).',
    culturalNotes: 'French official; Mooré most widely spoken; Dyula trade language.',
  },
  {
    code: 'CV',
    nameEn: 'Cabo Verde',
    region: 'West Africa',
    currencyCode: 'CVE',
    primaryLanguages: ['pt', 'kea'],
    bcp47Tags: ['pt-CV', 'kea-CV'],
    relatedDialectCodes: [],
    relatedAccentCodes: [],
    dateNotes: 'DMY (Portuguese).',
    numberNotes: 'Portuguese decimal conventions.',
    currencyNotes: 'Cape Verdean escudo (CVE).',
    culturalNotes: 'Portuguese official; Kabuverdianu dominant in daily speech.',
  },
  {
    code: 'GM',
    nameEn: 'Gambia',
    region: 'West Africa',
    currencyCode: 'GMD',
    primaryLanguages: ['en', 'wo', 'mnk', 'ff'],
    bcp47Tags: ['en-GM', 'wo-GM', 'mnk-GM'],
    relatedDialectCodes: [],
    relatedAccentCodes: [],
    dateNotes: 'DMY common.',
    numberNotes: 'Arabic digits.',
    currencyNotes: 'Gambian dalasi (GMD).',
    culturalNotes: 'English official; Mandinka, Wolof, and Pulaar widely spoken.',
  },
  {
    code: 'GN',
    nameEn: 'Guinea',
    region: 'West Africa',
    currencyCode: 'GNF',
    primaryLanguages: ['fr', 'ff', 'man', 'sus'],
    bcp47Tags: ['fr-GN', 'ff-GN', 'sus-GN'],
    relatedDialectCodes: [],
    relatedAccentCodes: [],
    dateNotes: 'DMY (French).',
    numberNotes: 'French decimal conventions.',
    currencyNotes: 'Guinean franc (GNF).',
    culturalNotes: 'French official; Pular, Maninka, and Susu are major national languages.',
  },
  {
    code: 'GW',
    nameEn: 'Guinea-Bissau',
    region: 'West Africa',
    currencyCode: 'XOF',
    primaryLanguages: ['pt', 'pov'],
    bcp47Tags: ['pt-GW', 'pov-GW'],
    relatedDialectCodes: [],
    relatedAccentCodes: [],
    dateNotes: 'DMY (Portuguese).',
    numberNotes: 'Portuguese decimal conventions.',
    currencyNotes: 'West African CFA franc (XOF).',
    culturalNotes: 'Portuguese official; Guinea-Bissau Creole is the lingua franca.',
  },
  {
    code: 'LR',
    nameEn: 'Liberia',
    region: 'West Africa',
    currencyCode: 'LRD',
    primaryLanguages: ['en', 'kpe', 'vai', 'men'],
    bcp47Tags: ['en-LR'],
    relatedDialectCodes: [],
    relatedAccentCodes: [],
    dateNotes: 'MDY influence from US education; DMY also appears — prefer ISO in APIs.',
    numberNotes: 'Arabic digits.',
    currencyNotes: 'Liberian dollar (LRD); USD also circulates.',
    culturalNotes: 'English official; Kpelle and other Mande/Atlantic languages widely spoken.',
  },
  {
    code: 'ML',
    nameEn: 'Mali',
    region: 'West Africa',
    currencyCode: 'XOF',
    primaryLanguages: ['fr', 'bm', 'ff', 'snk', 'tmh', 'dje', 'ses'],
    bcp47Tags: ['fr-ML', 'bm-ML', 'ff-ML'],
    relatedDialectCodes: ['bm-ml'],
    relatedAccentCodes: ['bm-ml'],
    dateNotes: 'DMY (French).',
    numberNotes: 'French decimal conventions.',
    currencyNotes: 'West African CFA franc (XOF).',
    culturalNotes: 'French official; Bambara is the main lingua franca; Fulfulde and Songhay varieties important.',
  },
  {
    code: 'MR',
    nameEn: 'Mauritania',
    region: 'West Africa',
    currencyCode: 'MRU',
    primaryLanguages: ['ar', 'ff', 'wo', 'snk'],
    bcp47Tags: ['ar-MR', 'ff-MR'],
    relatedDialectCodes: [],
    relatedAccentCodes: [],
    dateNotes: 'DMY; Gregorian for APIs.',
    numberNotes: 'Western digits preferred in APIs.',
    currencyNotes: 'Mauritanian ouguiya (MRU).',
    culturalNotes: 'Arabic official; Pulaar, Wolof, and Soninke recognized national languages.',
  },
  {
    code: 'NE',
    nameEn: 'Niger',
    region: 'West Africa',
    currencyCode: 'XOF',
    primaryLanguages: ['fr', 'ha', 'dje', 'ff', 'kr', 'tmh'],
    bcp47Tags: ['fr-NE', 'ha-NE', 'dje-NE'],
    relatedDialectCodes: [],
    relatedAccentCodes: [],
    dateNotes: 'DMY (French).',
    numberNotes: 'French decimal conventions.',
    currencyNotes: 'West African CFA franc (XOF).',
    culturalNotes: 'French official; Hausa and Zarma are the largest mother tongues.',
  },
  {
    code: 'SL',
    nameEn: 'Sierra Leone',
    region: 'West Africa',
    currencyCode: 'SLE',
    primaryLanguages: ['en', 'kri', 'tem', 'men'],
    bcp47Tags: ['en-SL', 'kri-SL'],
    relatedDialectCodes: [],
    relatedAccentCodes: [],
    dateNotes: 'DMY common.',
    numberNotes: 'Arabic digits.',
    currencyNotes: 'Sierra Leonean leone (SLE).',
    culturalNotes: 'English official; Krio is the lingua franca; Temne and Mende major regional languages.',
  },
  {
    code: 'TG',
    nameEn: 'Togo',
    region: 'West Africa',
    currencyCode: 'XOF',
    primaryLanguages: ['fr', 'ee', 'kbp'],
    bcp47Tags: ['fr-TG', 'ee-TG', 'kbp-TG'],
    relatedDialectCodes: [],
    relatedAccentCodes: [],
    dateNotes: 'DMY (French).',
    numberNotes: 'French decimal conventions.',
    currencyNotes: 'West African CFA franc (XOF).',
    culturalNotes: 'French official; Ewe and Kabiyè are major national languages.',
  },

  // —— Central Africa ——
  {
    code: 'CM',
    nameEn: 'Cameroon',
    region: 'Central Africa',
    currencyCode: 'XAF',
    primaryLanguages: ['fr', 'en', 'ewo', 'dua', 'bas', 'bum', 'ff'],
    bcp47Tags: ['fr-CM', 'en-CM', 'ewo-CM'],
    relatedDialectCodes: [],
    relatedAccentCodes: [],
    dateNotes: 'DMY common.',
    numberNotes: 'French or English conventions by region.',
    currencyNotes: 'Central African CFA franc (XAF).',
    culturalNotes: 'French and English official; many national languages — Ewondo, Duala, Fulfulde among the most visible.',
  },
  {
    code: 'CF',
    nameEn: 'Central African Republic',
    region: 'Central Africa',
    currencyCode: 'XAF',
    primaryLanguages: ['fr', 'sg'],
    bcp47Tags: ['fr-CF', 'sg-CF'],
    relatedDialectCodes: [],
    relatedAccentCodes: [],
    dateNotes: 'DMY (French).',
    numberNotes: 'French decimal conventions.',
    currencyNotes: 'Central African CFA franc (XAF).',
    culturalNotes: 'French and Sango official; Sango is the national lingua franca.',
  },
  {
    code: 'TD',
    nameEn: 'Chad',
    region: 'Central Africa',
    currencyCode: 'XAF',
    primaryLanguages: ['fr', 'ar'],
    bcp47Tags: ['fr-TD', 'ar-TD'],
    relatedDialectCodes: [],
    relatedAccentCodes: [],
    dateNotes: 'DMY common.',
    numberNotes: 'French or Arabic conventions by audience.',
    currencyNotes: 'Central African CFA franc (XAF).',
    culturalNotes: 'French and Arabic official; many Chadic and Sara languages spoken regionally.',
  },
  {
    code: 'CG',
    nameEn: 'Congo',
    region: 'Central Africa',
    currencyCode: 'XAF',
    primaryLanguages: ['fr', 'ln', 'kg'],
    bcp47Tags: ['fr-CG', 'ln-CG'],
    relatedDialectCodes: ['ln-cg'],
    relatedAccentCodes: [],
    dateNotes: 'DMY (French).',
    numberNotes: 'French decimal conventions.',
    currencyNotes: 'Central African CFA franc (XAF).',
    culturalNotes: 'French official; Lingala and Kikongo are major national languages.',
  },
  {
    code: 'CD',
    nameEn: 'DR Congo',
    region: 'Central Africa',
    currencyCode: 'CDF',
    primaryLanguages: ['fr', 'ln', 'swc', 'lu', 'kg', 'lua'],
    bcp47Tags: ['fr-CD', 'ln-CD', 'sw-CD', 'lu-CD'],
    relatedDialectCodes: ['ln-cd', 'swc-cd'],
    relatedAccentCodes: [],
    dateNotes: 'DMY (French).',
    numberNotes: 'French decimal conventions.',
    currencyNotes: 'Congolese franc (CDF).',
    culturalNotes: 'French official; Lingala, Congo Swahili, Tshiluba, and Kikongo are national languages.',
  },
  {
    code: 'GQ',
    nameEn: 'Equatorial Guinea',
    region: 'Central Africa',
    currencyCode: 'XAF',
    primaryLanguages: ['es', 'fr', 'pt', 'fan'],
    bcp47Tags: ['es-GQ', 'fr-GQ', 'pt-GQ'],
    relatedDialectCodes: [],
    relatedAccentCodes: [],
    dateNotes: 'DMY common.',
    numberNotes: 'Spanish decimal conventions common.',
    currencyNotes: 'Central African CFA franc (XAF).',
    culturalNotes: 'Spanish, French, and Portuguese official; Fang widely spoken.',
  },
  {
    code: 'GA',
    nameEn: 'Gabon',
    region: 'Central Africa',
    currencyCode: 'XAF',
    primaryLanguages: ['fr', 'fan'],
    bcp47Tags: ['fr-GA', 'fan-GA'],
    relatedDialectCodes: [],
    relatedAccentCodes: [],
    dateNotes: 'DMY (French).',
    numberNotes: 'French decimal conventions.',
    currencyNotes: 'Central African CFA franc (XAF).',
    culturalNotes: 'French official; Fang is the largest mother tongue.',
  },
  {
    code: 'ST',
    nameEn: 'São Tomé and Príncipe',
    region: 'Central Africa',
    currencyCode: 'STN',
    primaryLanguages: ['pt', 'cri'],
    bcp47Tags: ['pt-ST', 'cri-ST'],
    relatedDialectCodes: [],
    relatedAccentCodes: [],
    dateNotes: 'DMY (Portuguese).',
    numberNotes: 'Portuguese decimal conventions.',
    currencyNotes: 'Dobra (STN).',
    culturalNotes: 'Portuguese official; Forro (Sãotomense) widely spoken.',
  },

  // —— East Africa ——
  {
    code: 'BI',
    nameEn: 'Burundi',
    region: 'East Africa',
    currencyCode: 'BIF',
    primaryLanguages: ['rn', 'fr', 'en', 'sw'],
    bcp47Tags: ['rn-BI', 'fr-BI', 'en-BI', 'sw-BI'],
    relatedDialectCodes: ['rn-bi'],
    relatedAccentCodes: [],
    dateNotes: 'DMY common.',
    numberNotes: 'Arabic digits; French conventions in FR copy.',
    currencyNotes: 'Burundian franc (BIF).',
    culturalNotes: 'Kirundi official with French and English; Swahili used in trade.',
  },
  {
    code: 'KM',
    nameEn: 'Comoros',
    region: 'East Africa',
    currencyCode: 'KMF',
    primaryLanguages: ['ar', 'fr', 'zdj', 'wni'],
    bcp47Tags: ['ar-KM', 'fr-KM', 'zdj-KM'],
    relatedDialectCodes: [],
    relatedAccentCodes: [],
    dateNotes: 'DMY common.',
    numberNotes: 'French or Arabic conventions by audience.',
    currencyNotes: 'Comorian franc (KMF).',
    culturalNotes: 'Comorian (Shikomori varieties), Arabic, and French are official.',
  },
  {
    code: 'MG',
    nameEn: 'Madagascar',
    region: 'East Africa',
    currencyCode: 'MGA',
    primaryLanguages: ['mg', 'fr'],
    bcp47Tags: ['mg-MG', 'fr-MG'],
    relatedDialectCodes: [],
    relatedAccentCodes: [],
    dateNotes: 'DMY common.',
    numberNotes: 'French decimal conventions in FR copy.',
    currencyNotes: 'Malagasy ariary (MGA).',
    culturalNotes: 'Malagasy and French official; Austronesian Malagasy is the national lingua franca.',
  },
  {
    code: 'MW',
    nameEn: 'Malawi',
    region: 'Southern Africa',
    currencyCode: 'MWK',
    primaryLanguages: ['en', 'ny', 'tum', 'yao'],
    bcp47Tags: ['en-MW', 'ny-MW'],
    relatedDialectCodes: ['ny-mw'],
    relatedAccentCodes: [],
    dateNotes: 'DMY common.',
    numberNotes: 'Arabic digits.',
    currencyNotes: 'Malawian kwacha (MWK).',
    culturalNotes: 'English and Chichewa official; Tumbuka and Yao important regionally.',
  },
  {
    code: 'MU',
    nameEn: 'Mauritius',
    region: 'East Africa',
    currencyCode: 'MUR',
    primaryLanguages: ['en', 'fr', 'mfe'],
    bcp47Tags: ['en-MU', 'fr-MU', 'mfe-MU'],
    relatedDialectCodes: [],
    relatedAccentCodes: [],
    dateNotes: 'DMY common.',
    numberNotes: 'French or English conventions by audience.',
    currencyNotes: 'Mauritian rupee (MUR).',
    culturalNotes: 'English official; French widely used; Morisyen is the everyday lingua franca.',
  },
  {
    code: 'MZ',
    nameEn: 'Mozambique',
    region: 'Southern Africa',
    currencyCode: 'MZN',
    primaryLanguages: ['pt', 'vmw', 'ts', 'seh', 'ngl', 'ny'],
    bcp47Tags: ['pt-MZ', 'vmw-MZ', 'ts-MZ'],
    relatedDialectCodes: [],
    relatedAccentCodes: ['pt-mz'],
    dateNotes: 'DMY (Portuguese).',
    numberNotes: 'Portuguese decimal conventions.',
    currencyNotes: 'Mozambican metical (MZN).',
    culturalNotes: 'Portuguese official; Makhuwa, Tsonga, Sena, and Lomwe among major Bantu languages.',
  },
  {
    code: 'RW',
    nameEn: 'Rwanda',
    region: 'East Africa',
    currencyCode: 'RWF',
    primaryLanguages: ['rw', 'en', 'fr', 'sw'],
    bcp47Tags: ['rw-RW', 'en-RW', 'fr-RW', 'sw-RW'],
    relatedDialectCodes: ['rw-rw'],
    relatedAccentCodes: ['rw-rw'],
    dateNotes: 'DMY common.',
    numberNotes: 'Arabic digits.',
    currencyNotes: 'Rwandan franc (RWF).',
    culturalNotes: 'Kinyarwanda is the national language; English, French, and Swahili also official.',
  },
  {
    code: 'SC',
    nameEn: 'Seychelles',
    region: 'East Africa',
    currencyCode: 'SCR',
    primaryLanguages: ['en', 'fr', 'crs'],
    bcp47Tags: ['en-SC', 'fr-SC', 'crs-SC'],
    relatedDialectCodes: [],
    relatedAccentCodes: [],
    dateNotes: 'DMY common.',
    numberNotes: 'English or French conventions by audience.',
    currencyNotes: 'Seychellois rupee (SCR).',
    culturalNotes: 'English, French, and Seselwa Creole are official.',
  },
  {
    code: 'SS',
    nameEn: 'South Sudan',
    region: 'East Africa',
    currencyCode: 'SSP',
    primaryLanguages: ['en', 'ar', 'din', 'nus', 'shk'],
    bcp47Tags: ['en-SS', 'ar-SS', 'din-SS'],
    relatedDialectCodes: [],
    relatedAccentCodes: [],
    dateNotes: 'DMY common.',
    numberNotes: 'Arabic digits.',
    currencyNotes: 'South Sudanese pound (SSP).',
    culturalNotes: 'English official; Arabic used; Dinka and Nuer are major national languages.',
  },
  {
    code: 'UG',
    nameEn: 'Uganda',
    region: 'East Africa',
    currencyCode: 'UGX',
    primaryLanguages: ['en', 'sw', 'lg', 'ach', 'teo', 'nyn', 'myx', 'lgg', 'cgg', 'xog'],
    bcp47Tags: ['en-UG', 'sw-UG', 'lg-UG', 'nyn-UG'],
    relatedDialectCodes: ['lg-ug'],
    relatedAccentCodes: ['en-ug', 'lg-ug'],
    dateNotes: 'DMY common.',
    numberNotes: 'Arabic digits.',
    currencyNotes: 'Ugandan shilling (UGX).',
    culturalNotes: 'English and Swahili official; Luganda is the major central lingua franca among many national languages.',
  },

  // —— Southern Africa ——
  {
    code: 'AO',
    nameEn: 'Angola',
    region: 'Southern Africa',
    currencyCode: 'AOA',
    primaryLanguages: ['pt', 'umb', 'kmb', 'kg', 'kj'],
    bcp47Tags: ['pt-AO', 'umb-AO', 'kmb-AO'],
    relatedDialectCodes: [],
    relatedAccentCodes: ['pt-ao'],
    dateNotes: 'DMY (Portuguese).',
    numberNotes: 'Portuguese decimal conventions.',
    currencyNotes: 'Angolan kwanza (AOA).',
    culturalNotes: 'Portuguese official; Umbundu and Kimbundu are major national languages.',
  },
  {
    code: 'BW',
    nameEn: 'Botswana',
    region: 'Southern Africa',
    currencyCode: 'BWP',
    primaryLanguages: ['en', 'tn'],
    bcp47Tags: ['en-BW', 'tn-BW'],
    relatedDialectCodes: ['tn-bw'],
    relatedAccentCodes: [],
    dateNotes: 'DMY common.',
    numberNotes: 'Arabic digits.',
    currencyNotes: 'Botswana pula (BWP).',
    culturalNotes: 'English official; Setswana is the national language.',
  },
  {
    code: 'LS',
    nameEn: 'Lesotho',
    region: 'Southern Africa',
    currencyCode: 'LSL',
    primaryLanguages: ['en', 'st'],
    bcp47Tags: ['en-LS', 'st-LS'],
    relatedDialectCodes: ['st-ls'],
    relatedAccentCodes: [],
    dateNotes: 'DMY common.',
    numberNotes: 'Arabic digits.',
    currencyNotes: 'Lesotho loti (LSL); ZAR also circulates.',
    culturalNotes: 'Sesotho and English official.',
  },
  {
    code: 'NA',
    nameEn: 'Namibia',
    region: 'Southern Africa',
    currencyCode: 'NAD',
    primaryLanguages: ['en', 'af', 'kj', 'ng', 'her', 'naq', 'de'],
    bcp47Tags: ['en-NA', 'af-NA', 'kj-NA', 'ng-NA'],
    relatedDialectCodes: [],
    relatedAccentCodes: [],
    dateNotes: 'DMY common.',
    numberNotes: 'Arabic digits.',
    currencyNotes: 'Namibian dollar (NAD); ZAR also circulates.',
    culturalNotes: 'English official; Afrikaans widely used; Oshiwambo varieties (Kuanyama/Ndonga), Herero, and Nama important.',
  },
  {
    code: 'SZ',
    nameEn: 'Eswatini',
    region: 'Southern Africa',
    currencyCode: 'SZL',
    primaryLanguages: ['en', 'ss'],
    bcp47Tags: ['en-SZ', 'ss-SZ'],
    relatedDialectCodes: ['ss-za'],
    relatedAccentCodes: [],
    dateNotes: 'DMY common.',
    numberNotes: 'Arabic digits.',
    currencyNotes: 'Swazi lilangeni (SZL); ZAR also circulates.',
    culturalNotes: 'siSwati and English official.',
  },
  {
    code: 'ZM',
    nameEn: 'Zambia',
    region: 'Southern Africa',
    currencyCode: 'ZMW',
    primaryLanguages: ['en', 'bem', 'ny', 'toi', 'loz', 'tum'],
    bcp47Tags: ['en-ZM', 'bem-ZM', 'ny-ZM'],
    relatedDialectCodes: [],
    relatedAccentCodes: [],
    dateNotes: 'DMY common.',
    numberNotes: 'Arabic digits.',
    currencyNotes: 'Zambian kwacha (ZMW).',
    culturalNotes: 'English official; Bemba, Nyanja, Tonga, and Lozi are major national languages.',
  },
  {
    code: 'ZW',
    nameEn: 'Zimbabwe',
    region: 'Southern Africa',
    currencyCode: 'ZWL',
    primaryLanguages: ['en', 'sn', 'nd', 'kck', 'ndc'],
    bcp47Tags: ['en-ZW', 'sn-ZW', 'nd-ZW'],
    relatedDialectCodes: ['sn-zw'],
    relatedAccentCodes: [],
    dateNotes: 'DMY common.',
    numberNotes: 'Arabic digits.',
    currencyNotes: 'Zimbabwean dollar (ZWL); USD widely used in practice.',
    culturalNotes: 'English, chiShona, and isiNdebele are the main official languages in practice.',
  },
];
