export type AccentSeed = {
  code: string;
  languageCode: string;
  nameEn: string;
  nameNative?: string;
  region?: string;
  relatedDialectCode?: string;
  cueTerms: string[];
  notes?: string;
};

/**
 * Curated spoken accent profiles (VL-132) — African-priority.
 * Labels are profiles inferred from transcript cues after STT or from text.
 * Not an acoustic phonetics / unlimited accent catalog.
 */
export const ACCENT_SEEDS: AccentSeed[] = [
  // —— Existing ——
  {
    code: 'en-ng',
    languageCode: 'en',
    nameEn: 'Nigerian English (spoken)',
    region: 'NG',
    relatedDialectCode: 'en-ng',
    cueTerms: ['abi', 'na wa', 'how far', 'oya', 'wetin', 'sef', 'abeg'],
    notes: 'Lexical proxies for spoken Nigerian English — not acoustic ID.',
  },
  {
    code: 'en-za',
    languageCode: 'en',
    nameEn: 'South African English (spoken)',
    region: 'ZA',
    relatedDialectCode: 'en-za',
    cueTerms: ['lekker', 'braai', 'robot', 'just now', 'sharp sharp', 'howzit'],
    notes: 'Lexical proxies — not acoustic ID.',
  },
  {
    code: 'en-ke',
    languageCode: 'en',
    nameEn: 'Kenyan English (spoken)',
    region: 'KE',
    cueTerms: ['sasa', 'pole', 'hakuna', 'niaje', 'kwani', 'mzungu'],
    notes: 'Kenyan English / Sheng-adjacent spoken cues.',
  },
  {
    code: 'en-gh',
    languageCode: 'en',
    nameEn: 'Ghanaian English (spoken)',
    region: 'GH',
    relatedDialectCode: 'en-gh',
    cueTerms: ['chale', 'paa', 'charley', 'small small', 'please', 'eh'],
    notes: 'Common Ghanaian English lexical cues.',
  },
  {
    code: 'fr-sn',
    languageCode: 'fr',
    nameEn: 'Senegalese French (spoken)',
    region: 'SN',
    cueTerms: ['waaw', 'déédéét', 'amul', 'jërëjëf', 'nanga def'],
    notes: 'Wolof-influenced French spoken cues mixed with French.',
  },
  {
    code: 'fr-ci',
    languageCode: 'fr',
    nameEn: 'Ivorian French (spoken)',
    region: 'CI',
    cueTerms: ['yako', 'on est ensemble', 'il y a moyen', 'en tout cas', 'même'],
    notes: 'Nouchi / Ivorian spoken French proxies.',
  },
  {
    code: 'ar-eg',
    languageCode: 'ar',
    nameEn: 'Egyptian Arabic (spoken)',
    region: 'EG',
    relatedDialectCode: 'ar-eg',
    cueTerms: ['ازيك', 'كده', 'مش', 'علشان', 'يعني', 'دلوقتي'],
    notes: 'Colloquial Egyptian spoken cues.',
  },
  {
    code: 'sw-ke',
    languageCode: 'sw',
    nameEn: 'Kenyan Swahili (spoken)',
    region: 'KE',
    relatedDialectCode: 'sw-ke',
    cueTerms: ['sasa', 'poa', 'niaje', 'bro', 'uko aje', 'safi'],
    notes: 'Spoken Kenyan Swahili / Sheng-adjacent cues.',
  },
  {
    code: 'ha-ng',
    languageCode: 'ha',
    nameEn: 'Nigerian Hausa (spoken)',
    region: 'NG',
    relatedDialectCode: 'ha-ng',
    cueTerms: ['sannu', 'na gode', 'yaya', 'ina kwana', 'lahiya'],
    notes: 'Spoken greeting/lexical cues.',
  },
  {
    code: 'zu-za',
    languageCode: 'zu',
    nameEn: 'South African Zulu (spoken)',
    region: 'ZA',
    relatedDialectCode: 'zu-za',
    cueTerms: ['sawubona', 'ngiyabonga', 'unjani', 'yebo', 'cha'],
    notes: 'Spoken greeting/lexical cues.',
  },

  // —— New spoken profiles ——
  {
    code: 'am-et',
    languageCode: 'am',
    nameEn: 'Ethiopian Amharic (spoken)',
    region: 'ET',
    relatedDialectCode: 'am-et',
    cueTerms: ['ሰላም', 'አመሰግናለሁ', 'እባክህ', 'እንደምን', 'አዎ'],
    notes: 'Spoken Amharic lexical proxies.',
  },
  {
    code: 'yo-ng',
    languageCode: 'yo',
    nameEn: 'Nigerian Yoruba (spoken)',
    region: 'NG',
    relatedDialectCode: 'yo-ng',
    cueTerms: ['ẹ káàárọ̀', 'jọ̀ọ́', 'ọmọ', 'béẹ̀ni', 'ràra'],
    notes: 'Spoken Yoruba lexical proxies.',
  },
  {
    code: 'ar-ma',
    languageCode: 'ar',
    nameEn: 'Moroccan Arabic (spoken)',
    region: 'MA',
    relatedDialectCode: 'ar-ma',
    cueTerms: ['واش', 'بزاف', 'فين', 'صافي', 'كيفاش'],
    notes: 'Darija spoken cues.',
  },
  {
    code: 'af-za',
    languageCode: 'af',
    nameEn: 'South African Afrikaans (spoken)',
    region: 'ZA',
    relatedDialectCode: 'af-za',
    cueTerms: ['dankie', 'asseblief', 'hoe gaan dit', 'baie', 'lekker'],
    notes: 'Spoken Afrikaans lexical proxies.',
  },
  {
    code: 'xh-za',
    languageCode: 'xh',
    nameEn: 'South African Xhosa (spoken)',
    region: 'ZA',
    relatedDialectCode: 'xh-za',
    cueTerms: ['molo', 'enkosi', 'unjani', 'ewe', 'hayi'],
    notes: 'Spoken Xhosa lexical proxies.',
  },
  {
    code: 'ig-ng',
    languageCode: 'ig',
    nameEn: 'Nigerian Igbo (spoken)',
    region: 'NG',
    relatedDialectCode: 'ig-ng',
    cueTerms: ['kedu', 'daalụ', 'ndewo', 'ee', 'mba'],
    notes: 'Spoken Igbo lexical proxies.',
  },
  {
    code: 'wo-sn',
    languageCode: 'wo',
    nameEn: 'Senegalese Wolof (spoken)',
    region: 'SN',
    relatedDialectCode: 'wo-sn',
    cueTerms: ['nanga def', 'jërëjëf', 'waaw', 'déédéét', 'amul'],
    notes: 'Spoken Wolof lexical proxies.',
  },
  {
    code: 'lg-ug',
    languageCode: 'lg',
    nameEn: 'Ugandan Luganda (spoken)',
    region: 'UG',
    relatedDialectCode: 'lg-ug',
    cueTerms: ['gyebaleko', 'weebale', 'oli otya', 'ye', 'nedda'],
    notes: 'Spoken Luganda lexical proxies.',
  },
  {
    code: 'rw-rw',
    languageCode: 'rw',
    nameEn: 'Rwandan Kinyarwanda (spoken)',
    region: 'RW',
    relatedDialectCode: 'rw-rw',
    cueTerms: ['muraho', 'murakoze', 'amakuru', 'yego', 'oya'],
    notes: 'Spoken Kinyarwanda lexical proxies.',
  },
  {
    code: 'so-so',
    languageCode: 'so',
    nameEn: 'Somali (spoken)',
    region: 'SO',
    relatedDialectCode: 'so-so',
    cueTerms: ['salaan', 'mahadsanid', 'sidee tahay', 'haa', 'maya'],
    notes: 'Spoken Somali lexical proxies.',
  },
  {
    code: 'bm-ml',
    languageCode: 'bm',
    nameEn: 'Malian Bambara (spoken)',
    region: 'ML',
    relatedDialectCode: 'bm-ml',
    cueTerms: ['i ni ce', 'i ni sogoma', 'awɔ', 'ayiwa', 'an be'],
    notes: 'Spoken Bambara lexical proxies.',
  },
  {
    code: 'ak-gh',
    languageCode: 'ak',
    nameEn: 'Ghanaian Akan (spoken)',
    region: 'GH',
    relatedDialectCode: 'ak-gh',
    cueTerms: ['maakye', 'medaase', 'wo ho te sɛn', 'aane', 'daabi'],
    notes: 'Spoken Akan lexical proxies.',
  },
  {
    code: 'ee-gh',
    languageCode: 'ee',
    nameEn: 'Ghanaian Ewe (spoken)',
    region: 'GH',
    relatedDialectCode: 'ee-gh',
    cueTerms: ['ŋdi', 'akpe', 'efɔ̃a', 'ẽ', 'ao'],
    notes: 'Spoken Ewe lexical proxies.',
  },
  {
    code: 'fr-ma',
    languageCode: 'fr',
    nameEn: 'Moroccan French (spoken)',
    region: 'MA',
    cueTerms: ['wa', 'bzaf', 'inchallah', 'yak', 'safi'],
    notes: 'Darija-influenced French spoken cues. Country locale tag: fr-MA.',
  },
  {
    code: 'fr-dz',
    languageCode: 'fr',
    nameEn: 'Algerian French (spoken)',
    region: 'DZ',
    cueTerms: ['wesh', 'kif', 'sahbi', 'wallah', 'bien sûr'],
    notes: 'Algerian French / Darija contact cues. Country locale tag: fr-DZ.',
  },
  {
    code: 'fr-tn',
    languageCode: 'fr',
    nameEn: 'Tunisian French (spoken)',
    region: 'TN',
    cueTerms: ['barsha', 'normal', 'yaawi', 'wallah', 'bien sûr'],
    notes: 'Tunisian French / Darija contact cues. Country locale tag: fr-TN.',
  },
  {
    code: 'fr-mr',
    languageCode: 'fr',
    nameEn: 'Mauritanian French (spoken)',
    region: 'MR',
    cueTerms: ['inshallah', 'wallah', 'ça va', 'normal', 'sahbi'],
    notes: 'Hassaniya-contact French spoken cues. Country locale tag: fr-MR.',
  },
  {
    code: 'ar-tn',
    languageCode: 'ar',
    nameEn: 'Tunisian Arabic (spoken)',
    region: 'TN',
    relatedDialectCode: 'ar-tn',
    cueTerms: ['علاش', 'برشا', 'شنوة', 'باهي', 'اي'],
    notes: 'Tunisian Darija spoken cues. ISO alias: aeb.',
  },
  {
    code: 'ar-dz',
    languageCode: 'ar',
    nameEn: 'Algerian Arabic (spoken)',
    region: 'DZ',
    relatedDialectCode: 'ar-dz',
    cueTerms: ['واش', 'بزاف', 'كي راك', 'صح', 'راني'],
    notes: 'Algerian Darija spoken cues. ISO alias: arq.',
  },
  {
    code: 'ar-ly',
    languageCode: 'ar',
    nameEn: 'Libyan Arabic (spoken)',
    region: 'LY',
    relatedDialectCode: 'ar-ly',
    cueTerms: ['كيفك', 'هكي', 'وين', 'ايوة', 'زين'],
    notes: 'Libyan Arabic spoken cues. ISO alias: ayl.',
  },
  {
    code: 'ar-sd',
    languageCode: 'ar',
    nameEn: 'Sudanese Arabic (spoken)',
    region: 'SD',
    relatedDialectCode: 'ar-sd',
    cueTerms: ['كيفك', 'زين', 'مافي', 'يا زول', 'كويس'],
    notes: 'Sudanese Arabic spoken cues. ISO alias: apd.',
  },
  {
    code: 'mey-mr',
    languageCode: 'mey',
    nameEn: 'Hassaniya Arabic (spoken)',
    region: 'MR',
    relatedDialectCode: 'mey-mr',
    cueTerms: ['اشحال', 'واش', 'زين', 'ماهي', 'ايوه'],
    notes: 'Hassaniya spoken cues — Mauritania primary market.',
  },
  {
    code: 'ber-ma',
    languageCode: 'ber',
    nameEn: 'Moroccan Amazigh (spoken, macro)',
    region: 'MA',
    relatedDialectCode: 'ber-ma',
    cueTerms: ['azul', 'tanemmirt', 'mandeɣ', 'yah', 'uhu'],
    notes: 'Macro Amazigh spoken cues; prefer tzm/shi/rif/kab when known.',
  },
  {
    code: 'tzm-ma',
    languageCode: 'tzm',
    nameEn: 'Central Atlas Tamazight (spoken)',
    region: 'MA',
    relatedDialectCode: 'tzm-ma',
    cueTerms: ['azul', 'tanemmirt', 'mliḥ', 'yah', 'uhu'],
    notes: 'Spoken Central Atlas Tamazight lexical proxies.',
  },
  {
    code: 'shi-ma',
    languageCode: 'shi',
    nameEn: 'Tachelhit (spoken)',
    region: 'MA',
    relatedDialectCode: 'shi-ma',
    cueTerms: ['azul', 'tanemmirt', 'mzyan', 'yah', 'uhu'],
    notes: 'Spoken Tachelhit lexical proxies.',
  },
  {
    code: 'rif-ma',
    languageCode: 'rif',
    nameEn: 'Tarifit (spoken)',
    region: 'MA',
    relatedDialectCode: 'rif-ma',
    cueTerms: ['azul', 'tanemmirt', 'baha', 'wah', 'ala'],
    notes: 'Spoken Tarifit lexical proxies.',
  },
  {
    code: 'kab-dz',
    languageCode: 'kab',
    nameEn: 'Kabyle (spoken)',
    region: 'DZ',
    relatedDialectCode: 'kab-dz',
    cueTerms: ['azul', 'tanemmirt', 'ih', 'ala', 'aqvayli'],
    notes: 'Spoken Kabyle lexical proxies.',
  },
  {
    code: 'zgh-ma',
    languageCode: 'zgh',
    nameEn: 'Standard Moroccan Tamazight (spoken)',
    region: 'MA',
    relatedDialectCode: 'zgh-ma',
    cueTerms: ['azul', 'tanemmirt', 'yah', 'uhu', 'tifinagh'],
    notes: 'Spoken standard Moroccan Tamazight proxies.',
  },
  {
    code: 'pt-ao',
    languageCode: 'pt',
    nameEn: 'Angolan Portuguese (spoken)',
    region: 'AO',
    cueTerms: ['bué', 'fixe', 'pá', 'ya', 'então'],
    notes: 'Angolan Portuguese lexical proxies.',
  },
  {
    code: 'pt-mz',
    languageCode: 'pt',
    nameEn: 'Mozambican Portuguese (spoken)',
    region: 'MZ',
    cueTerms: ['fixe', 'ya', 'machamba', 'tuga', 'então'],
    notes: 'Mozambican Portuguese lexical proxies.',
  },
  {
    code: 'en-tz',
    languageCode: 'en',
    nameEn: 'Tanzanian English (spoken)',
    region: 'TZ',
    cueTerms: ['pole', 'asante', 'karibu', 'sawa', 'ndiyo'],
    notes: 'Swahili-influenced Tanzanian English cues.',
  },
  {
    code: 'en-ug',
    languageCode: 'en',
    nameEn: 'Ugandan English (spoken)',
    region: 'UG',
    cueTerms: ['sebo', 'nyabo', 'please', 'somehow', 'you people'],
    notes: 'Ugandan English lexical proxies.',
  },
  {
    code: 'sw-tz',
    languageCode: 'sw',
    nameEn: 'Tanzanian Swahili (spoken)',
    region: 'TZ',
    relatedDialectCode: 'sw-tz',
    cueTerms: ['sana', 'kwenye', 'labda', 'tafadhali', 'asante sana'],
    notes: 'Spoken coastal Swahili cues.',
  },

  // —— Strategic global spoken accents ——
  {
    code: 'en-in',
    languageCode: 'en',
    nameEn: 'Indian English (spoken)',
    region: 'IN',
    relatedDialectCode: 'en-in',
    cueTerms: ['yaar', 'only', 'itself', 'kindly', 'do the needful', 'prepone'],
    notes: 'Spoken Indian English lexical proxies.',
  },
  {
    code: 'en-ph',
    languageCode: 'en',
    nameEn: 'Philippine English (spoken)',
    region: 'PH',
    relatedDialectCode: 'en-ph',
    cueTerms: ['opo', 'po', 'already', 'open the light', 'comfort room'],
    notes: 'Spoken Philippine English proxies.',
  },
  {
    code: 'en-sg',
    languageCode: 'en',
    nameEn: 'Singapore English (spoken)',
    region: 'SG',
    relatedDialectCode: 'en-sg',
    cueTerms: ['lah', 'lor', 'meh', 'shiok', 'makan'],
    notes: 'Singlish particle proxies.',
  },
  {
    code: 'en-jm',
    languageCode: 'en',
    nameEn: 'Jamaican English (spoken)',
    region: 'JM',
    relatedDialectCode: 'en-jm',
    cueTerms: ['irie', 'wah gwaan', 'soon come', 'likkle', 'bredren'],
    notes: 'Jamaican English spoken proxies.',
  },
  {
    code: 'en-tt',
    languageCode: 'en',
    nameEn: 'Trinidadian English (spoken)',
    region: 'TT',
    relatedDialectCode: 'en-tt',
    cueTerms: ['allyuh', 'lime', 'tabanca', 'bacchanal'],
    notes: 'Trinidadian English spoken proxies.',
  },
  {
    code: 'es-mx',
    languageCode: 'es',
    nameEn: 'Mexican Spanish (spoken)',
    region: 'MX',
    relatedDialectCode: 'es-mx',
    cueTerms: ['orale', 'guey', 'chido', 'que onda', 'ahorita'],
    notes: 'Mexican Spanish spoken proxies.',
  },
  {
    code: 'es-co',
    languageCode: 'es',
    nameEn: 'Colombian Spanish (spoken)',
    region: 'CO',
    relatedDialectCode: 'es-co',
    cueTerms: ['parce', 'bacano', 'que mas', 'listo'],
    notes: 'Colombian Spanish spoken proxies.',
  },
  {
    code: 'es-ar',
    languageCode: 'es',
    nameEn: 'Rioplatense Spanish (spoken)',
    region: 'AR',
    relatedDialectCode: 'es-ar',
    cueTerms: ['che', 'boludo', 'vos', 're'],
    notes: 'Rioplatense spoken proxies.',
  },
  {
    code: 'es-do',
    languageCode: 'es',
    nameEn: 'Dominican Spanish (spoken)',
    region: 'DO',
    relatedDialectCode: 'es-do',
    cueTerms: ['vaina', 'tiguere', 'klk', 'jevi'],
    notes: 'Dominican Spanish spoken proxies.',
  },
  {
    code: 'es-pr',
    languageCode: 'es',
    nameEn: 'Puerto Rican Spanish (spoken)',
    region: 'PR',
    relatedDialectCode: 'es-pr',
    cueTerms: ['wepa', 'brutal', 'bregar', 'chinchorro'],
    notes: 'Puerto Rican Spanish spoken proxies.',
  },
  {
    code: 'pt-br',
    languageCode: 'pt',
    nameEn: 'Brazilian Portuguese (spoken)',
    region: 'BR',
    relatedDialectCode: 'pt-br',
    cueTerms: ['voce', 'legal', 'cara', 'beleza', 'valeu'],
    notes: 'Brazilian Portuguese spoken proxies.',
  },
  {
    code: 'hi-in',
    languageCode: 'hi',
    nameEn: 'Indian Hindi (spoken)',
    region: 'IN',
    relatedDialectCode: 'hi-in',
    cueTerms: ['namaste', 'ji', 'yaar', 'accha', 'theek hai'],
    notes: 'Hindi spoken proxies.',
  },
  {
    code: 'bn-bd',
    languageCode: 'bn',
    nameEn: 'Bangladeshi Bengali (spoken)',
    region: 'BD',
    relatedDialectCode: 'bn-bd',
    cueTerms: ['assalamualaikum', 'apni', 'kemon', 'dhonnobad'],
    notes: 'Bangla spoken proxies.',
  },
  {
    code: 'ta-in',
    languageCode: 'ta',
    nameEn: 'Indian Tamil (spoken)',
    region: 'IN',
    relatedDialectCode: 'ta-in',
    cueTerms: ['vanakkam', 'nandri', 'seri', 'ille'],
    notes: 'Tamil spoken proxies.',
  },
  {
    code: 'te-in',
    languageCode: 'te',
    nameEn: 'Indian Telugu (spoken)',
    region: 'IN',
    relatedDialectCode: 'te-in',
    cueTerms: ['namaskaram', 'dhanyavadalu', 'avunu', 'kadhu'],
    notes: 'Telugu spoken proxies.',
  },
  {
    code: 'th-th',
    languageCode: 'th',
    nameEn: 'Central Thai (spoken)',
    region: 'TH',
    relatedDialectCode: 'th-th',
    cueTerms: ['sawasdee', 'khob khun', 'mai pen rai', 'krub', 'ka'],
    notes: 'Thai spoken politeness proxies.',
  },
  {
    code: 'vi-vn',
    languageCode: 'vi',
    nameEn: 'Vietnamese (spoken)',
    region: 'VN',
    relatedDialectCode: 'vi-vn',
    cueTerms: ['xin chao', 'cam on', 'khong', 'da'],
    notes: 'Vietnamese spoken proxies.',
  },
  {
    code: 'tl-ph',
    languageCode: 'tl',
    nameEn: 'Tagalog (spoken)',
    region: 'PH',
    relatedDialectCode: 'tl-ph',
    cueTerms: ['kumusta', 'salamat', 'po', 'opo', 'hindi'],
    notes: 'Tagalog spoken proxies.',
  },
  {
    code: 'ms-my',
    languageCode: 'ms',
    nameEn: 'Malaysian Malay (spoken)',
    region: 'MY',
    relatedDialectCode: 'ms-my',
    cueTerms: ['terima kasih', 'boleh', 'lah', 'tak'],
    notes: 'Malay spoken proxies.',
  },
  {
    code: 'ur-pk',
    languageCode: 'ur',
    nameEn: 'Pakistani Urdu (spoken)',
    region: 'PK',
    relatedDialectCode: 'ur-pk',
    cueTerms: ['assalamualaikum', 'shukriya', 'ji', 'theek'],
    notes: 'Urdu spoken proxies.',
  },
  {
    code: 'ht-ht',
    languageCode: 'ht',
    nameEn: 'Haitian Creole (spoken)',
    region: 'HT',
    relatedDialectCode: 'ht-ht',
    cueTerms: ['bonjou', 'mesi', 'kijan', 'wi', 'non'],
    notes: 'Haitian Creole spoken proxies.',
  },
  {
    code: 'jam-jm',
    languageCode: 'jam',
    nameEn: 'Jamaican Patwa (spoken)',
    region: 'JM',
    relatedDialectCode: 'jam-jm',
    cueTerms: ['wah gwaan', 'mi', 'yuh', 'nuh', 'irie'],
    notes: 'Patwa spoken proxies.',
  },
  {
    code: 'qu-pe',
    languageCode: 'qu',
    nameEn: 'Peruvian Quechua (spoken)',
    region: 'PE',
    relatedDialectCode: 'qu-pe',
    cueTerms: ['allillanchu', 'sulpayki', 'ari', 'mana'],
    notes: 'Quechua spoken proxies.',
  },
  {
    code: 'gn-py',
    languageCode: 'gn',
    nameEn: 'Paraguayan Guarani (spoken)',
    region: 'PY',
    relatedDialectCode: 'gn-py',
    cueTerms: ['mbaeteko', 'aguyje', 'hee', 'che'],
    notes: 'Guarani spoken proxies.',
  },
  {
    code: 'yue-hk',
    languageCode: 'yue',
    nameEn: 'Hong Kong Cantonese (spoken)',
    region: 'HK',
    relatedDialectCode: 'yue-hk',
    cueTerms: ['nei hou', 'm goi', 'hou', 'hai'],
    notes: 'Cantonese spoken proxies.',
  },
  {
    code: 'es-pe',
    languageCode: 'es',
    nameEn: 'Peruvian Spanish (spoken)',
    region: 'PE',
    relatedDialectCode: 'es-pe',
    cueTerms: ['causa', 'pata', 'pe', 'ya pues'],
    notes: 'Peruvian Spanish spoken proxies.',
  },

];
