export type AccentSeed = {
  code: string;
  languageCode: string;
  nameEn: string;
  nameNative?: string;
  region?: string;
  relatedDialectCode?: string;
  cueTerms: string[];
  notes?: string;
};

/**
 * Curated spoken accent profiles (VL-132) — African-priority.
 * Labels are profiles inferred from transcript cues after STT or from text.
 * Not an acoustic phonetics / unlimited accent catalog.
 */
export const ACCENT_SEEDS: AccentSeed[] = [
  // —— Existing ——
  {
    code: 'en-ng',
    languageCode: 'en',
    nameEn: 'Nigerian English (spoken)',
    region: 'NG',
    relatedDialectCode: 'en-ng',
    cueTerms: ['abi', 'na wa', 'how far', 'oya', 'wetin', 'sef', 'abeg'],
    notes: 'Lexical proxies for spoken Nigerian English — not acoustic ID.',
  },
  {
    code: 'en-za',
    languageCode: 'en',
    nameEn: 'South African English (spoken)',
    region: 'ZA',
    relatedDialectCode: 'en-za',
    cueTerms: ['lekker', 'braai', 'robot', 'just now', 'sharp sharp', 'howzit'],
    notes: 'Lexical proxies — not acoustic ID.',
  },
  {
    code: 'en-ke',
    languageCode: 'en',
    nameEn: 'Kenyan English (spoken)',
    region: 'KE',
    cueTerms: ['sasa', 'pole', 'hakuna', 'niaje', 'kwani', 'mzungu'],
    notes: 'Kenyan English / Sheng-adjacent spoken cues.',
  },
  {
    code: 'en-gh',
    languageCode: 'en',
    nameEn: 'Ghanaian English (spoken)',
    region: 'GH',
    relatedDialectCode: 'en-gh',
    cueTerms: ['chale', 'paa', 'charley', 'small small', 'please', 'eh'],
    notes: 'Common Ghanaian English lexical cues.',
  },
  {
    code: 'fr-sn',
    languageCode: 'fr',
    nameEn: 'Senegalese French (spoken)',
    region: 'SN',
    cueTerms: ['waaw', 'déédéét', 'amul', 'jërëjëf', 'nanga def'],
    notes: 'Wolof-influenced French spoken cues mixed with French.',
  },
  {
    code: 'fr-ci',
    languageCode: 'fr',
    nameEn: 'Ivorian French (spoken)',
    region: 'CI',
    cueTerms: ['yako', 'on est ensemble', 'il y a moyen', 'en tout cas', 'même'],
    notes: 'Nouchi / Ivorian spoken French proxies.',
  },
  {
    code: 'ar-eg',
    languageCode: 'ar',
    nameEn: 'Egyptian Arabic (spoken)',
    region: 'EG',
    relatedDialectCode: 'ar-eg',
    cueTerms: ['ازيك', 'كده', 'مش', 'علشان', 'يعني', 'دلوقتي'],
    notes: 'Colloquial Egyptian spoken cues.',
  },
  {
    code: 'sw-ke',
    languageCode: 'sw',
    nameEn: 'Kenyan Swahili (spoken)',
    region: 'KE',
    relatedDialectCode: 'sw-ke',
    cueTerms: ['sasa', 'poa', 'niaje', 'bro', 'uko aje', 'safi'],
    notes: 'Spoken Kenyan Swahili / Sheng-adjacent cues.',
  },
  {
    code: 'ha-ng',
    languageCode: 'ha',
    nameEn: 'Nigerian Hausa (spoken)',
    region: 'NG',
    relatedDialectCode: 'ha-ng',
    cueTerms: ['sannu', 'na gode', 'yaya', 'ina kwana', 'lahiya'],
    notes: 'Spoken greeting/lexical cues.',
  },
  {
    code: 'zu-za',
    languageCode: 'zu',
    nameEn: 'South African Zulu (spoken)',
    region: 'ZA',
    relatedDialectCode: 'zu-za',
    cueTerms: ['sawubona', 'ngiyabonga', 'unjani', 'yebo', 'cha'],
    notes: 'Spoken greeting/lexical cues.',
  },

  // —— New spoken profiles ——
  {
    code: 'am-et',
    languageCode: 'am',
    nameEn: 'Ethiopian Amharic (spoken)',
    region: 'ET',
    relatedDialectCode: 'am-et',
    cueTerms: ['ሰላም', 'አመሰግናለሁ', 'እባክህ', 'እንደምን', 'አዎ'],
    notes: 'Spoken Amharic lexical proxies.',
  },
  {
    code: 'yo-ng',
    languageCode: 'yo',
    nameEn: 'Nigerian Yoruba (spoken)',
    region: 'NG',
    relatedDialectCode: 'yo-ng',
    cueTerms: ['ẹ káàárọ̀', 'jọ̀ọ́', 'ọmọ', 'béẹ̀ni', 'ràra'],
    notes: 'Spoken Yoruba lexical proxies.',
  },
  {
    code: 'ar-ma',
    languageCode: 'ar',
    nameEn: 'Moroccan Arabic (spoken)',
    region: 'MA',
    relatedDialectCode: 'ar-ma',
    cueTerms: ['واش', 'بزاف', 'فين', 'صافي', 'كيفاش'],
    notes: 'Darija spoken cues.',
  },
  {
    code: 'af-za',
    languageCode: 'af',
    nameEn: 'South African Afrikaans (spoken)',
    region: 'ZA',
    relatedDialectCode: 'af-za',
    cueTerms: ['dankie', 'asseblief', 'hoe gaan dit', 'baie', 'lekker'],
    notes: 'Spoken Afrikaans lexical proxies.',
  },
  {
    code: 'xh-za',
    languageCode: 'xh',
    nameEn: 'South African Xhosa (spoken)',
    region: 'ZA',
    relatedDialectCode: 'xh-za',
    cueTerms: ['molo', 'enkosi', 'unjani', 'ewe', 'hayi'],
    notes: 'Spoken Xhosa lexical proxies.',
  },
  {
    code: 'ig-ng',
    languageCode: 'ig',
    nameEn: 'Nigerian Igbo (spoken)',
    region: 'NG',
    relatedDialectCode: 'ig-ng',
    cueTerms: ['kedu', 'daalụ', 'ndewo', 'ee', 'mba'],
    notes: 'Spoken Igbo lexical proxies.',
  },
  {
    code: 'wo-sn',
    languageCode: 'wo',
    nameEn: 'Senegalese Wolof (spoken)',
    region: 'SN',
    relatedDialectCode: 'wo-sn',
    cueTerms: ['nanga def', 'jërëjëf', 'waaw', 'déédéét', 'amul'],
    notes: 'Spoken Wolof lexical proxies.',
  },
  {
    code: 'lg-ug',
    languageCode: 'lg',
    nameEn: 'Ugandan Luganda (spoken)',
    region: 'UG',
    relatedDialectCode: 'lg-ug',
    cueTerms: ['gyebaleko', 'weebale', 'oli otya', 'ye', 'nedda'],
    notes: 'Spoken Luganda lexical proxies.',
  },
  {
    code: 'rw-rw',
    languageCode: 'rw',
    nameEn: 'Rwandan Kinyarwanda (spoken)',
    region: 'RW',
    relatedDialectCode: 'rw-rw',
    cueTerms: ['muraho', 'murakoze', 'amakuru', 'yego', 'oya'],
    notes: 'Spoken Kinyarwanda lexical proxies.',
  },
  {
    code: 'so-so',
    languageCode: 'so',
    nameEn: 'Somali (spoken)',
    region: 'SO',
    relatedDialectCode: 'so-so',
    cueTerms: ['salaan', 'mahadsanid', 'sidee tahay', 'haa', 'maya'],
    notes: 'Spoken Somali lexical proxies.',
  },
  {
    code: 'bm-ml',
    languageCode: 'bm',
    nameEn: 'Malian Bambara (spoken)',
    region: 'ML',
    relatedDialectCode: 'bm-ml',
    cueTerms: ['i ni ce', 'i ni sogoma', 'awɔ', 'ayiwa', 'an be'],
    notes: 'Spoken Bambara lexical proxies.',
  },
  {
    code: 'ak-gh',
    languageCode: 'ak',
    nameEn: 'Ghanaian Akan (spoken)',
    region: 'GH',
    relatedDialectCode: 'ak-gh',
    cueTerms: ['maakye', 'medaase', 'wo ho te sɛn', 'aane', 'daabi'],
    notes: 'Spoken Akan lexical proxies.',
  },
  {
    code: 'ee-gh',
    languageCode: 'ee',
    nameEn: 'Ghanaian Ewe (spoken)',
    region: 'GH',
    relatedDialectCode: 'ee-gh',
    cueTerms: ['ŋdi', 'akpe', 'efɔ̃a', 'ẽ', 'ao'],
    notes: 'Spoken Ewe lexical proxies.',
  },
  {
    code: 'fr-ma',
    languageCode: 'fr',
    nameEn: 'Moroccan French (spoken)',
    region: 'MA',
    cueTerms: ['wa', 'bzaf', 'inchallah', 'yak', 'safi'],
    notes: 'Darija-influenced French spoken cues.',
  },
  {
    code: 'fr-dz',
    languageCode: 'fr',
    nameEn: 'Algerian French (spoken)',
    region: 'DZ',
    cueTerms: ['wesh', 'kif', 'sahbi', 'wallah', 'bien sûr'],
    notes: 'Algerian French / Darija contact cues.',
  },
  {
    code: 'pt-ao',
    languageCode: 'pt',
    nameEn: 'Angolan Portuguese (spoken)',
    region: 'AO',
    cueTerms: ['bué', 'fixe', 'pá', 'ya', 'então'],
    notes: 'Angolan Portuguese lexical proxies.',
  },
  {
    code: 'pt-mz',
    languageCode: 'pt',
    nameEn: 'Mozambican Portuguese (spoken)',
    region: 'MZ',
    cueTerms: ['fixe', 'ya', 'machamba', 'tuga', 'então'],
    notes: 'Mozambican Portuguese lexical proxies.',
  },
  {
    code: 'en-tz',
    languageCode: 'en',
    nameEn: 'Tanzanian English (spoken)',
    region: 'TZ',
    cueTerms: ['pole', 'asante', 'karibu', 'sawa', 'ndiyo'],
    notes: 'Swahili-influenced Tanzanian English cues.',
  },
  {
    code: 'en-ug',
    languageCode: 'en',
    nameEn: 'Ugandan English (spoken)',
    region: 'UG',
    cueTerms: ['sebo', 'nyabo', 'please', 'somehow', 'you people'],
    notes: 'Ugandan English lexical proxies.',
  },
  {
    code: 'sw-tz',
    languageCode: 'sw',
    nameEn: 'Tanzanian Swahili (spoken)',
    region: 'TZ',
    relatedDialectCode: 'sw-tz',
    cueTerms: ['sana', 'kwenye', 'labda', 'tafadhali', 'asante sana'],
    notes: 'Spoken coastal Swahili cues.',
  },
];
