export type DialectSeed = {
  code: string;
  languageCode: string;
  nameEn: string;
  nameNative?: string;
  region?: string;
  cueTerms: string[];
  notes?: string;
};

/**
 * Curated dialect seeds (VL-131) — priority African + related varieties.
 * Not an exhaustive linguistics catalog.
 */
export const DIALECT_SEEDS: DialectSeed[] = [
  // —— Existing ——
  {
    code: 'sw-tz',
    languageCode: 'sw',
    nameEn: 'Tanzanian / coastal Swahili',
    nameNative: 'Kiswahili cha pwani',
    region: 'TZ / coastal East Africa',
    cueTerms: ['sana', 'kwenye', 'labda', 'tafadhali', 'asante sana', 'habari yako'],
    notes: 'Standard coastal-leaning cues; heuristic only.',
  },
  {
    code: 'sw-ke',
    languageCode: 'sw',
    nameEn: 'Kenyan Swahili',
    nameNative: 'Kiswahili cha Kenya',
    region: 'KE',
    cueTerms: ['sasa', 'poa', 'niaje', 'bro', 'uko aje', 'safi'],
    notes: 'Urban Kenyan cues mixed with Sheng-adjacent tokens.',
  },
  {
    code: 'yo-ng',
    languageCode: 'yo',
    nameEn: 'Nigerian Yoruba',
    nameNative: 'Yorùbá',
    region: 'NG',
    cueTerms: ['ẹ káàárọ̀', 'ẹ kú', 'ọmọ', 'jọ̀ọ́', 'béẹ̀ni', 'ràra'],
    notes: 'Common orthographic forms; tone marks optional in matching.',
  },
  {
    code: 'am-et',
    languageCode: 'am',
    nameEn: 'Ethiopian Amharic',
    nameNative: 'አማርኛ',
    region: 'ET',
    cueTerms: ['ሰላም', 'አመሰግናለሁ', 'እባክህ', 'እባክሽ', 'እንደምን'],
    notes: 'Ethiopic-script cues.',
  },
  {
    code: 'ar-eg',
    languageCode: 'ar',
    nameEn: 'Egyptian Arabic',
    nameNative: 'مصري',
    region: 'EG',
    cueTerms: ['ازيك', 'كده', 'مش', 'علشان', 'يعني', 'دلوقتي'],
    notes: 'Colloquial Egyptian cues in Arabic script.',
  },
  {
    code: 'ar-ma',
    languageCode: 'ar',
    nameEn: 'Moroccan Darija',
    nameNative: 'الدارجة',
    region: 'MA',
    cueTerms: ['واش', 'بزاف', 'فين', 'صافي', 'لا باس', 'كيفاش'],
    notes: 'Maghrebi cues; distinct from MSA. ISO 639-3 alias: ary.',
  },
  {
    code: 'en-ng',
    languageCode: 'en',
    nameEn: 'Nigerian English',
    region: 'NG',
    cueTerms: ['abi', 'na wa', 'how far', 'oya', 'wetin', 'sef'],
    notes: 'Lexical cues only — not accent detection.',
  },
  {
    code: 'en-za',
    languageCode: 'en',
    nameEn: 'South African English',
    region: 'ZA',
    cueTerms: ['lekker', 'braai', 'robot', 'just now', 'sharp sharp', 'howzit'],
    notes: 'Lexical cues only — not accent detection.',
  },
  {
    code: 'ha-ng',
    languageCode: 'ha',
    nameEn: 'Nigerian Hausa',
    nameNative: 'Hausa',
    region: 'NG',
    cueTerms: ['sannu', 'na gode', 'yaya', 'ina kwana', 'lahiya'],
    notes: 'Common greeting/lexical cues.',
  },
  {
    code: 'zu-za',
    languageCode: 'zu',
    nameEn: 'South African Zulu',
    nameNative: 'isiZulu',
    region: 'ZA',
    cueTerms: ['sawubona', 'ngiyabonga', 'unjani', 'yebo', 'cha'],
    notes: 'Common greeting/lexical cues.',
  },
  {
    code: 'af-za',
    languageCode: 'af',
    nameEn: 'South African Afrikaans',
    nameNative: 'Afrikaans',
    region: 'ZA',
    cueTerms: ['dankie', 'asseblief', 'hoe gaan dit', 'baie', 'lekker'],
    notes: 'Common lexical cues.',
  },

  // —— Ghana ——
  {
    code: 'ak-gh',
    languageCode: 'ak',
    nameEn: 'Ghanaian Akan',
    nameNative: 'Akan',
    region: 'GH',
    cueTerms: ['maakye', 'medaase', 'wo ho te sɛn', 'yɛ', 'aane', 'daabi'],
    notes: 'Akan greeting/lexical cues; covers Twi-adjacent forms.',
  },
  {
    code: 'tw-gh',
    languageCode: 'tw',
    nameEn: 'Ghanaian Twi',
    nameNative: 'Twi',
    region: 'GH',
    cueTerms: ['maakye', 'medaase', 'ɛte sɛn', 'me pɛ', 'yoo', 'dabi'],
    notes: 'Twi lexical cues.',
  },
  {
    code: 'ee-gh',
    languageCode: 'ee',
    nameEn: 'Ghanaian Ewe',
    nameNative: 'Eʋegbe',
    region: 'GH',
    cueTerms: ['ŋdi', 'akpe', 'efɔ̃a', 'ẽ', 'ao', 'míawo'],
    notes: 'Ewe greeting/lexical cues.',
  },
  {
    code: 'gaa-gh',
    languageCode: 'gaa',
    nameEn: 'Ghanaian Ga',
    nameNative: 'Gã',
    region: 'GH',
    cueTerms: ['ojekoo', 'oyiwala don', 'te oyɔ', 'hãã', 'dao', 'miishɛ'],
    notes: 'Ga lexical cues.',
  },
  {
    code: 'dag-gh',
    languageCode: 'dag',
    nameEn: 'Ghanaian Dagbani',
    nameNative: 'Dagbani',
    region: 'GH',
    cueTerms: ['desiba', 'mpaɣya', 'a wuhima', 'mm', 'ayi', 'naa'],
    notes: 'Dagbani greeting/lexical cues.',
  },
  {
    code: 'en-gh',
    languageCode: 'en',
    nameEn: 'Ghanaian English',
    region: 'GH',
    cueTerms: ['chale', 'paa', 'charley', 'small small', 'please', 'eh'],
    notes: 'Lexical cues only — not accent detection.',
  },

  // —— South Africa ——
  {
    code: 'xh-za',
    languageCode: 'xh',
    nameEn: 'South African Xhosa',
    nameNative: 'isiXhosa',
    region: 'ZA',
    cueTerms: ['molo', 'enkosi', 'unjani', 'ewe', 'hayi', 'ndiyabulela'],
    notes: 'Common greeting/lexical cues.',
  },
  {
    code: 'nso-za',
    languageCode: 'nso',
    nameEn: 'South African Northern Sotho',
    nameNative: 'Sesotho sa Leboa',
    region: 'ZA',
    cueTerms: ['thobela', 'ke a leboga', 'o kae', 'ee', 'aowa'],
    notes: 'Sepedi lexical cues.',
  },
  {
    code: 'tn-za',
    languageCode: 'tn',
    nameEn: 'South African Tswana',
    nameNative: 'Setswana',
    region: 'ZA',
    cueTerms: ['dumela', 'ke a leboga', 'o tsogile jang', 'ee', 'nyaa'],
    notes: 'Setswana lexical cues.',
  },
  {
    code: 'st-za',
    languageCode: 'st',
    nameEn: 'South African Southern Sotho',
    nameNative: 'Sesotho',
    region: 'ZA',
    cueTerms: ['dumela', 'kea leboha', 'u phela joang', 'e', 'tjhe'],
    notes: 'Sesotho lexical cues.',
  },
  {
    code: 'ss-za',
    languageCode: 'ss',
    nameEn: 'South African / Swazi Swati',
    nameNative: 'siSwati',
    region: 'ZA / SZ',
    cueTerms: ['sawubona', 'ngiyabonga', 'unjani', 'yebo', 'cha'],
    notes: 'siSwati lexical cues.',
  },
  {
    code: 'ts-za',
    languageCode: 'ts',
    nameEn: 'South African Tsonga',
    nameNative: 'Xitsonga',
    region: 'ZA',
    cueTerms: ['avuxeni', 'ndza khensa', 'ku njhani', 'ina', 'e-e'],
    notes: 'Xitsonga lexical cues.',
  },
  {
    code: 've-za',
    languageCode: 've',
    nameEn: 'South African Venda',
    nameNative: 'Tshivenḓa',
    region: 'ZA',
    cueTerms: ['ndaa', 'ndo livhuwa', 'vha vhona hani', 'ee', 'hai'],
    notes: 'Tshivenḓa lexical cues.',
  },
  {
    code: 'nr-za',
    languageCode: 'nr',
    nameEn: 'South African Southern Ndebele',
    nameNative: 'isiNdebele',
    region: 'ZA',
    cueTerms: ['lotjhani', 'ngiyathokoza', 'unjani', 'yebo', 'azi'],
    notes: 'Southern Ndebele lexical cues.',
  },

  // —— East / Horn ——
  {
    code: 'lg-ug',
    languageCode: 'lg',
    nameEn: 'Ugandan Luganda',
    nameNative: 'Luganda',
    region: 'UG',
    cueTerms: ['gyebaleko', 'weebale', 'oli otya', 'ye', 'nedda', 'webale nnyo'],
    notes: 'Luganda greeting/lexical cues.',
  },
  {
    code: 'rw-rw',
    languageCode: 'rw',
    nameEn: 'Rwandan Kinyarwanda',
    nameNative: 'Ikinyarwanda',
    region: 'RW',
    cueTerms: ['muraho', 'murakoze', 'amakuru', 'yego', 'oya'],
    notes: 'Kinyarwanda lexical cues.',
  },
  {
    code: 'rn-bi',
    languageCode: 'rn',
    nameEn: 'Burundian Kirundi',
    nameNative: 'Ikirundi',
    region: 'BI',
    cueTerms: ['bwasaha', 'urakoze', 'amakuru', 'ego', 'oya'],
    notes: 'Kirundi lexical cues.',
  },
  {
    code: 'so-so',
    languageCode: 'so',
    nameEn: 'Somali (Somalia)',
    nameNative: 'Soomaali',
    region: 'SO',
    cueTerms: ['salaan', 'mahadsanid', 'sidee tahay', 'haa', 'maya', 'waad mahadsantahay'],
    notes: 'Somali lexical cues.',
  },
  {
    code: 'om-et',
    languageCode: 'om',
    nameEn: 'Ethiopian Oromo',
    nameNative: 'Afaan Oromoo',
    region: 'ET',
    cueTerms: ['akkam', 'galatoomi', 'nagaa', 'eeyyee', 'lakki'],
    notes: 'Oromo lexical cues.',
  },
  {
    code: 'ti-er',
    languageCode: 'ti',
    nameEn: 'Eritrean Tigrinya',
    nameNative: 'ትግርኛ',
    region: 'ER',
    cueTerms: ['ሰላም', 'የቐንየለይ', 'ከመይ', 'እወ', 'ኣይኮንን'],
    notes: 'Ethiopic-script Tigrinya cues.',
  },

  // —— North Africa ——
  {
    code: 'ar-tn',
    languageCode: 'ar',
    nameEn: 'Tunisian Arabic',
    nameNative: 'تونسي',
    region: 'TN',
    cueTerms: ['علاش', 'برشا', 'شنوة', 'باهي', 'اي', 'لي'],
    notes: 'Tunisian Darija cues. ISO 639-3 alias: aeb.',
  },
  {
    code: 'ar-dz',
    languageCode: 'ar',
    nameEn: 'Algerian Arabic',
    nameNative: 'دزيرية',
    region: 'DZ',
    cueTerms: ['واش', 'بزاف', 'كي راك', 'صح', 'لا', 'راني'],
    notes: 'Algerian Darija cues. ISO 639-3 alias: arq.',
  },
  {
    code: 'ar-ly',
    languageCode: 'ar',
    nameEn: 'Libyan Arabic',
    nameNative: 'ليبي',
    region: 'LY',
    cueTerms: ['كيفك', 'هكي', 'وين', 'ايوة', 'لا', 'زين'],
    notes: 'Libyan Arabic cues. ISO 639-3 alias: ayl.',
  },
  {
    code: 'ar-sd',
    languageCode: 'ar',
    nameEn: 'Sudanese Arabic',
    nameNative: 'سوداني',
    region: 'SD',
    cueTerms: ['كيفك', 'زين', 'مافي', 'يا زول', 'كويس', 'خلاص'],
    notes: 'Sudanese Arabic cues. ISO 639-3 alias: apd.',
  },
  {
    code: 'mey-mr',
    languageCode: 'mey',
    nameEn: 'Mauritanian Hassaniya',
    nameNative: 'حسانية',
    region: 'MR',
    cueTerms: ['اشحال', 'واش', 'زين', 'ماهي', 'ايوه', 'لا'],
    notes: 'Hassaniya Arabic cues (Mauritania / Western Sahara belt).',
  },
  {
    code: 'ber-ma',
    languageCode: 'ber',
    nameEn: 'Moroccan Tamazight (macro)',
    nameNative: 'Tamaziɣt',
    region: 'MA',
    cueTerms: ['azul', 'tanemmirt', 'mandeɣ', 'yah', 'uhu'],
    notes: 'Macro Amazigh cues; prefer tzm/shi/rif/zgh where known.',
  },
  {
    code: 'tzm-ma',
    languageCode: 'tzm',
    nameEn: 'Central Atlas Tamazight (Morocco)',
    nameNative: 'Tamaziɣt',
    region: 'MA',
    cueTerms: ['azul', 'tanemmirt', 'mliḥ', 'yah', 'uhu', 'tifawt'],
    notes: 'Central Atlas Tamazight lexical cues.',
  },
  {
    code: 'shi-ma',
    languageCode: 'shi',
    nameEn: 'Tachelhit (Morocco)',
    nameNative: 'Taclḥit',
    region: 'MA',
    cueTerms: ['azul', 'tanemmirt', 'mzyan', 'yah', 'uhu', 'tifawin'],
    notes: 'Souss / Anti-Atlas Tachelhit lexical cues.',
  },
  {
    code: 'rif-ma',
    languageCode: 'rif',
    nameEn: 'Tarifit (Morocco)',
    nameNative: 'Tarifit',
    region: 'MA',
    cueTerms: ['azul', 'tanemmirt', 'baha', 'wah', 'ala', 'tifawt'],
    notes: 'Rif Tarifit lexical cues.',
  },
  {
    code: 'kab-dz',
    languageCode: 'kab',
    nameEn: 'Kabyle (Algeria)',
    nameNative: 'Taqbaylit',
    region: 'DZ',
    cueTerms: ['azul', 'tanemmirt', 'ih', 'ala', 'aqvayli', 'tamurt'],
    notes: 'Kabyle (Taqbaylit) lexical cues.',
  },
  {
    code: 'zgh-ma',
    languageCode: 'zgh',
    nameEn: 'Standard Moroccan Tamazight',
    nameNative: 'Tamaziɣt',
    region: 'MA',
    cueTerms: ['azul', 'tanemmirt', 'yah', 'uhu', 'tifinagh', 'ircam'],
    notes: 'IRCAM-standardized Moroccan Tamazight cues.',
  },

  // —— West Africa ——
  {
    code: 'ig-ng',
    languageCode: 'ig',
    nameEn: 'Nigerian Igbo',
    nameNative: 'Igbo',
    region: 'NG',
    cueTerms: ['kedu', 'daalụ', 'ndewo', 'ee', 'mba', 'biko'],
    notes: 'Igbo greeting/lexical cues.',
  },
  {
    code: 'wo-sn',
    languageCode: 'wo',
    nameEn: 'Senegalese Wolof',
    nameNative: 'Wolof',
    region: 'SN',
    cueTerms: ['nanga def', 'jërëjëf', 'waaw', 'déédéét', 'salaam aleekum'],
    notes: 'Wolof lexical cues.',
  },
  {
    code: 'bm-ml',
    languageCode: 'bm',
    nameEn: 'Malian Bambara',
    nameNative: 'Bamanankan',
    region: 'ML',
    cueTerms: ['i ni ce', 'i ni sogoma', 'aw ni baara', 'awɔ', 'ayiwa'],
    notes: 'Bambara greeting/lexical cues.',
  },
  {
    code: 'ff-sn',
    languageCode: 'ff',
    nameEn: 'Senegalese Pulaar',
    nameNative: 'Pulaar',
    region: 'SN',
    cueTerms: ['jam tan', 'a jaaraama', 'no mbadda', 'ey', 'alaa'],
    notes: 'Pulaar lexical cues.',
  },
  {
    code: 'ff-ng',
    languageCode: 'ff',
    nameEn: 'Nigerian Fulfulde',
    nameNative: 'Fulfulde',
    region: 'NG',
    cueTerms: ['sannu', 'a jaraama', 'noy', 'eyi', 'alaa'],
    notes: 'Nigerian Fulfulde lexical cues.',
  },
  {
    code: 'yo-bj',
    languageCode: 'yo',
    nameEn: 'Beninese Yoruba',
    nameNative: 'Yorùbá',
    region: 'BJ',
    cueTerms: ['ẹ káàárọ̀', 'ẹ kú', 'báwo', 'béẹ̀ni', 'ràra'],
    notes: 'Yoruba in Benin border communities.',
  },

  // —— Central ——
  {
    code: 'ln-cd',
    languageCode: 'ln',
    nameEn: 'DRC Lingala',
    nameNative: 'Lingála',
    region: 'CD',
    cueTerms: ['mbote', 'merci mingi', 'ozali malamu', 'iyo', 'te'],
    notes: 'Lingala lexical cues (Kinshasa-leaning).',
  },
  {
    code: 'ln-cg',
    languageCode: 'ln',
    nameEn: 'Congo-Brazzaville Lingala',
    nameNative: 'Lingála',
    region: 'CG',
    cueTerms: ['mbote', 'matondo', 'sango nini', 'ee', 'te'],
    notes: 'Lingala lexical cues (Brazzaville-leaning).',
  },
  {
    code: 'swc-cd',
    languageCode: 'swc',
    nameEn: 'Congo Swahili',
    nameNative: 'Kiswahili ya Kongo',
    region: 'CD',
    cueTerms: ['jambo', 'asante', 'habari', 'ndiyo', 'hapana', 'karibu'],
    notes: 'Eastern DRC Swahili cues; distinct from coastal standards.',
  },

  // —— Southern ——
  {
    code: 'ny-mw',
    languageCode: 'ny',
    nameEn: 'Malawian Chichewa',
    nameNative: 'Chichewa',
    region: 'MW',
    cueTerms: ['moni', 'zikomo', 'muli bwanji', 'inde', 'ayi'],
    notes: 'Chichewa lexical cues.',
  },
  {
    code: 'sn-zw',
    languageCode: 'sn',
    nameEn: 'Zimbabwean Shona',
    nameNative: 'chiShona',
    region: 'ZW',
    cueTerms: ['mhoro', 'ndatenda', 'makadii', 'hongu', 'kwete'],
    notes: 'Shona lexical cues.',
  },
  {
    code: 'tn-bw',
    languageCode: 'tn',
    nameEn: 'Botswana Tswana',
    nameNative: 'Setswana',
    region: 'BW',
    cueTerms: ['dumela', 'ke a leboga', 'o tsogile jang', 'ee', 'nyaa'],
    notes: 'Botswana Setswana lexical cues.',
  },
  {
    code: 'st-ls',
    languageCode: 'st',
    nameEn: 'Lesotho Sesotho',
    nameNative: 'Sesotho',
    region: 'LS',
    cueTerms: ['dumela', 'kea leboha', 'u phela joang', 'e', 'tjhe'],
    notes: 'Lesotho Sesotho lexical cues.',
  },

  // —— Strategic global (SEA / India / LatAm / Caribbean) ——
  {
    code: 'en-in',
    languageCode: 'en',
    nameEn: 'Indian English',
    region: 'IN',
    cueTerms: ['yaar', 'only', 'itself', 'kindly', 'do the needful', 'prepone'],
    notes: 'Indian English lexical cues — not acoustic ID.',
  },
  {
    code: 'en-ph',
    languageCode: 'en',
    nameEn: 'Philippine English',
    region: 'PH',
    cueTerms: ['opo', 'po', 'already', 'open the light', 'comfort room', 'CR'],
    notes: 'Philippine English lexical cues.',
  },
  {
    code: 'en-sg',
    languageCode: 'en',
    nameEn: 'Singapore English / Singlish',
    region: 'SG',
    cueTerms: ['lah', 'lor', 'meh', 'can', 'shiok', 'makan'],
    notes: 'Singlish particle cues.',
  },
  {
    code: 'en-jm',
    languageCode: 'en',
    nameEn: 'Jamaican English',
    region: 'JM',
    cueTerms: ['irie', 'wah gwaan', 'soon come', 'likkle', 'bredren'],
    notes: 'Jamaican English / continuum toward Patwa.',
  },
  {
    code: 'en-tt',
    languageCode: 'en',
    nameEn: 'Trinidadian English',
    region: 'TT',
    cueTerms: ['allyuh', 'lime', 'tabanca', 'stewps', 'bacchanal'],
    notes: 'Trinidad & Tobago English lexical cues.',
  },
  {
    code: 'es-mx',
    languageCode: 'es',
    nameEn: 'Mexican Spanish',
    nameNative: 'Espanol mexicano',
    region: 'MX',
    cueTerms: ['orale', 'guey', 'chido', 'padre', 'que onda', 'ahorita'],
    notes: 'Mexican Spanish lexical cues.',
  },
  {
    code: 'es-co',
    languageCode: 'es',
    nameEn: 'Colombian Spanish',
    region: 'CO',
    cueTerms: ['parce', 'bacano', 'que mas', 'listo', 'pues'],
    notes: 'Colombian Spanish lexical cues.',
  },
  {
    code: 'es-ar',
    languageCode: 'es',
    nameEn: 'Rioplatense Spanish',
    region: 'AR',
    cueTerms: ['che', 'boludo', 'vos', 're', 'barra'],
    notes: 'Argentine / Rioplatense cues including voseo.',
  },
  {
    code: 'es-pe',
    languageCode: 'es',
    nameEn: 'Peruvian Spanish',
    region: 'PE',
    cueTerms: ['causa', 'pata', 'pe', 'chibolo', 'ya pues'],
    notes: 'Peruvian coastal Spanish cues.',
  },
  {
    code: 'es-do',
    languageCode: 'es',
    nameEn: 'Dominican Spanish',
    region: 'DO',
    cueTerms: ['vaina', 'tiguere', 'klk', 'dimelo', 'jevi'],
    notes: 'Dominican Caribbean Spanish cues.',
  },
  {
    code: 'es-pr',
    languageCode: 'es',
    nameEn: 'Puerto Rican Spanish',
    region: 'PR',
    cueTerms: ['wepa', 'brutal', 'bregar', 'chinchorro', 'ahorita'],
    notes: 'Puerto Rican Spanish cues.',
  },
  {
    code: 'pt-br',
    languageCode: 'pt',
    nameEn: 'Brazilian Portuguese',
    nameNative: 'Portugues brasileiro',
    region: 'BR',
    cueTerms: ['voce', 'legal', 'cara', 'beleza', 'valeu', 'ne'],
    notes: 'Brazilian Portuguese lexical cues.',
  },
  {
    code: 'hi-in',
    languageCode: 'hi',
    nameEn: 'Indian Hindi',
    region: 'IN',
    cueTerms: ['namaste', 'ji', 'yaar', 'accha', 'theek hai', 'bhai'],
    notes: 'Hindi conversational cues (Latin transliteration OK for detect).',
  },
  {
    code: 'bn-bd',
    languageCode: 'bn',
    nameEn: 'Bangladeshi Bengali',
    region: 'BD',
    cueTerms: ['assalamualaikum', 'apni', 'kemon', 'dhonnobad', 'bhalo'],
    notes: 'Bangladeshi Bangla cues.',
  },
  {
    code: 'bn-in',
    languageCode: 'bn',
    nameEn: 'Indian Bengali',
    region: 'IN',
    cueTerms: ['nomoshkar', 'apni', 'kemon achen', 'dhonnobad', 'bhalo'],
    notes: 'West Bengal Bengali cues.',
  },
  {
    code: 'ta-in',
    languageCode: 'ta',
    nameEn: 'Indian Tamil',
    region: 'IN',
    cueTerms: ['vanakkam', 'nandri', 'unga', 'seri', 'ille'],
    notes: 'Indian Tamil cues (transliterated).',
  },
  {
    code: 'ta-lk',
    languageCode: 'ta',
    nameEn: 'Sri Lankan Tamil',
    region: 'LK',
    cueTerms: ['vanakkam', 'nandri', 'epdi', 'seri', 'illa'],
    notes: 'Sri Lankan Tamil cues.',
  },
  {
    code: 'te-in',
    languageCode: 'te',
    nameEn: 'Indian Telugu',
    region: 'IN',
    cueTerms: ['namaskaram', 'dhanyavadalu', 'ela unnaru', 'avunu', 'kadhu'],
    notes: 'Telugu cues (transliterated).',
  },
  {
    code: 'th-th',
    languageCode: 'th',
    nameEn: 'Central Thai',
    region: 'TH',
    cueTerms: ['sawasdee', 'khob khun', 'mai pen rai', 'krub', 'ka'],
    notes: 'Central Thai politeness particles (transliterated).',
  },
  {
    code: 'vi-vn',
    languageCode: 'vi',
    nameEn: 'Vietnamese (Vietnam)',
    region: 'VN',
    cueTerms: ['xin chao', 'cam on', 'khong', 'da', 'vang'],
    notes: 'Vietnamese lexical cues.',
  },
  {
    code: 'tl-ph',
    languageCode: 'tl',
    nameEn: 'Philippine Tagalog',
    region: 'PH',
    cueTerms: ['kumusta', 'salamat', 'po', 'opo', 'hindi', 'oo'],
    notes: 'Tagalog / Filipino cues.',
  },
  {
    code: 'id-id',
    languageCode: 'id',
    nameEn: 'Indonesian',
    region: 'ID',
    cueTerms: ['halo', 'terima kasih', 'apa kabar', 'sudah', 'belum'],
    notes: 'Bahasa Indonesia cues.',
  },
  {
    code: 'ms-my',
    languageCode: 'ms',
    nameEn: 'Malaysian Malay',
    region: 'MY',
    cueTerms: ['terima kasih', 'apa khabar', 'boleh', 'lah', 'tak'],
    notes: 'Malaysian Malay cues.',
  },
  {
    code: 'ur-pk',
    languageCode: 'ur',
    nameEn: 'Pakistani Urdu',
    region: 'PK',
    cueTerms: ['assalamualaikum', 'shukriya', 'ji', 'theek', 'haan'],
    notes: 'Pakistani Urdu cues (transliterated).',
  },
  {
    code: 'ht-ht',
    languageCode: 'ht',
    nameEn: 'Haitian Creole',
    region: 'HT',
    cueTerms: ['bonjou', 'mesi', 'kijan', 'wi', 'non', 'tanpri'],
    notes: 'Kreyol ayisyen cues.',
  },
  {
    code: 'jam-jm',
    languageCode: 'jam',
    nameEn: 'Jamaican Patwa',
    region: 'JM',
    cueTerms: ['wah gwaan', 'mi', 'yuh', 'nuh', 'likkle', 'irie'],
    notes: 'Jamaican Creole cues.',
  },
  {
    code: 'qu-pe',
    languageCode: 'qu',
    nameEn: 'Peruvian Quechua',
    region: 'PE',
    cueTerms: ['allillanchu', 'sulpayki', 'ari', 'mana', 'imas'],
    notes: 'Southern Quechua lexical cues.',
  },
  {
    code: 'gn-py',
    languageCode: 'gn',
    nameEn: 'Paraguayan Guarani',
    region: 'PY',
    cueTerms: ['mbaeteko', 'aguyje', 'heẽ', 'nahániri', 'che'],
    notes: 'Paraguayan Guarani cues.',
  },
  {
    code: 'pap-cw',
    languageCode: 'pap',
    nameEn: 'Curacao Papiamento',
    region: 'CW',
    cueTerms: ['bon dia', 'danki', 'kon ta', 'si', 'no'],
    notes: 'Papiamentu cues.',
  },
  {
    code: 'yue-hk',
    languageCode: 'yue',
    nameEn: 'Hong Kong Cantonese',
    region: 'HK',
    cueTerms: ['nei hou', 'm goi', 'hou', 'hai', 'm hai'],
    notes: 'Cantonese cues (jyutping-ish Latin).',
  },


  {
    code: 'km-kh',
    languageCode: 'km',
    nameEn: 'Khmer (Cambodia)',
    region: 'KH',
    cueTerms: ['suostei', 'arkoun', 'baat', 'ot', 'chas'],
    notes: 'Strategic global dialect cues for detect — lexical proxies only.',
  },


  {
    code: 'lo-la',
    languageCode: 'lo',
    nameEn: 'Lao (Laos)',
    region: 'LA',
    cueTerms: ['sabaidee', 'khop jai', 'dai', 'bo', 'jai'],
    notes: 'Strategic global dialect cues for detect — lexical proxies only.',
  },


  {
    code: 'my-mm',
    languageCode: 'my',
    nameEn: 'Burmese (Myanmar)',
    region: 'MM',
    cueTerms: ['mingalaba', 'kyeizu tin ba de', 'houk ke', 'ma houk'],
    notes: 'Strategic global dialect cues for detect — lexical proxies only.',
  },


  {
    code: 'jv-id',
    languageCode: 'jv',
    nameEn: 'Javanese (Indonesia)',
    region: 'ID',
    cueTerms: ['sugeng', 'matur nuwun', 'inggih', 'mboten', 'sampeyan'],
    notes: 'Strategic global dialect cues for detect — lexical proxies only.',
  },


  {
    code: 'su-id',
    languageCode: 'su',
    nameEn: 'Sundanese (Indonesia)',
    region: 'ID',
    cueTerms: ['wilujeng', 'hatur nuhun', 'muhun', 'teu', 'hideung'],
    notes: 'Strategic global dialect cues for detect — lexical proxies only.',
  },


  {
    code: 'ceb-ph',
    languageCode: 'ceb',
    nameEn: 'Cebuano (Philippines)',
    region: 'PH',
    cueTerms: ['kumusta', 'salamat', 'oo', 'dili', 'bay'],
    notes: 'Strategic global dialect cues for detect — lexical proxies only.',
  },


  {
    code: 'hil-ph',
    languageCode: 'hil',
    nameEn: 'Hiligaynon (Philippines)',
    region: 'PH',
    cueTerms: ['kumusta', 'salamat', 'huo', 'indi', 'bay'],
    notes: 'Strategic global dialect cues for detect — lexical proxies only.',
  },


  {
    code: 'war-ph',
    languageCode: 'war',
    nameEn: 'Waray (Philippines)',
    region: 'PH',
    cueTerms: ['kumusta', 'salamat', 'oo', 'dire', 'bay'],
    notes: 'Strategic global dialect cues for detect — lexical proxies only.',
  },


  {
    code: 'mr-in',
    languageCode: 'mr',
    nameEn: 'Indian Marathi',
    region: 'IN',
    cueTerms: ['namaskar', 'dhanyavad', 'ho', 'nahi', 'kay'],
    notes: 'Strategic global dialect cues for detect — lexical proxies only.',
  },


  {
    code: 'gu-in',
    languageCode: 'gu',
    nameEn: 'Indian Gujarati',
    region: 'IN',
    cueTerms: ['namaste', 'aabhar', 'ha', 'na', 'kem cho'],
    notes: 'Strategic global dialect cues for detect — lexical proxies only.',
  },


  {
    code: 'kn-in',
    languageCode: 'kn',
    nameEn: 'Indian Kannada',
    region: 'IN',
    cueTerms: ['namaskara', 'dhanyavadagalu', 'houdu', 'illa', 'hegiddira'],
    notes: 'Strategic global dialect cues for detect — lexical proxies only.',
  },


  {
    code: 'ml-in',
    languageCode: 'ml',
    nameEn: 'Indian Malayalam',
    region: 'IN',
    cueTerms: ['namaskaram', 'nanni', 'athe', 'alla', 'sukhamano'],
    notes: 'Strategic global dialect cues for detect — lexical proxies only.',
  },


  {
    code: 'pa-in',
    languageCode: 'pa',
    nameEn: 'Indian Punjabi',
    region: 'IN',
    cueTerms: ['sat sri akal', 'shukria', 'haan', 'nahin', 'ki haal'],
    notes: 'Strategic global dialect cues for detect — lexical proxies only.',
  },


  {
    code: 'or-in',
    languageCode: 'or',
    nameEn: 'Indian Odia',
    region: 'IN',
    cueTerms: ['namaskar', 'dhanyabad', 'han', 'nahin', 'kemiti achha'],
    notes: 'Strategic global dialect cues for detect — lexical proxies only.',
  },


  {
    code: 'as-in',
    languageCode: 'as',
    nameEn: 'Indian Assamese',
    region: 'IN',
    cueTerms: ['nomoskar', 'dhonyobad', 'hoy', 'nohoy', 'kene aase'],
    notes: 'Strategic global dialect cues for detect — lexical proxies only.',
  },


  {
    code: 'ne-np',
    languageCode: 'ne',
    nameEn: 'Nepali (Nepal)',
    region: 'NP',
    cueTerms: ['namaste', 'dhanyabad', 'ho', 'hoina', 'sanchai'],
    notes: 'Strategic global dialect cues for detect — lexical proxies only.',
  },


  {
    code: 'si-lk',
    languageCode: 'si',
    nameEn: 'Sinhala (Sri Lanka)',
    region: 'LK',
    cueTerms: ['ayubowan', 'stutiyi', 'owu', 'nehe', 'kohomada'],
    notes: 'Strategic global dialect cues for detect — lexical proxies only.',
  },


  {
    code: 'bho-in',
    languageCode: 'bho',
    nameEn: 'Indian Bhojpuri',
    region: 'IN',
    cueTerms: ['pranam', 'dhanyavad', 'haan', 'na', 'ka haal'],
    notes: 'Strategic global dialect cues for detect — lexical proxies only.',
  },


  {
    code: 'ay-bo',
    languageCode: 'ay',
    nameEn: 'Bolivian Aymara',
    region: 'BO',
    cueTerms: ['kamisaraki', "jusp'akt'a", 'jisa', 'jani', 'kamisaki'],
    notes: 'Strategic global dialect cues for detect — lexical proxies only.',
  },


  {
    code: 'nhe-mx',
    languageCode: 'nhe',
    nameEn: 'Mexican Nahuatl',
    region: 'MX',
    cueTerms: ['niltze', 'tlazohcamati', 'quema', 'ahmo', 'quen tika'],
    notes: 'Strategic global dialect cues for detect — lexical proxies only.',
  },


  {
    code: 'yua-mx',
    languageCode: 'yua',
    nameEn: 'Yucatec Maya',
    region: 'MX',
    cueTerms: ["ba'ax ka wa'alik", "jach dyos bo'otik", 'jaaj', "ma'", 'bix a bel'],
    notes: 'Strategic global dialect cues for detect — lexical proxies only.',
  },


  {
    code: 'gcf-gp',
    languageCode: 'gcf',
    nameEn: 'Guadeloupean Creole',
    region: 'GP',
    cueTerms: ['bonjou', 'mesi', 'wi', 'non', 'sa ka fèt'],
    notes: 'Strategic global dialect cues for detect — lexical proxies only.',
  },


  {
    code: 'pap-aw',
    languageCode: 'pap',
    nameEn: 'Aruba Papiamento',
    region: 'AW',
    cueTerms: ['bon dia', 'danki', 'si', 'no', 'kon ta'],
    notes: 'Strategic global dialect cues for detect — lexical proxies only.',
  },

];
