import { libraryReferenceHonesty } from './library-reference.honesty';

export type LibraryPhaseRow = { phase: number; name: string };
export type LibraryVolumeRow = { volume: number; title: string; phases: LibraryPhaseRow[] };

export function libraryReferenceVolumes(): LibraryVolumeRow[] {
  return [
    {
      volume: 1,
      title: 'Executive Foundation',
      phases: [
        { phase: -5, name: 'Company Vision' },
        { phase: -4, name: 'Market Strategy' },
        { phase: -3, name: 'AI Strategy' },
        { phase: -2, name: 'Business Architecture' },
        { phase: -1, name: 'Enterprise Product Blueprint' },
        { phase: 0, name: 'Engineering Operating System' },
        { phase: 1, name: 'Cloud Platform Foundation' },
        { phase: 2, name: 'Identity Cloud' },
        { phase: 3, name: 'Developer Cloud Foundation' },
        { phase: 4, name: 'Enterprise Cloud Foundation' },
        { phase: 5, name: 'AI Gateway Cloud Foundation' },
        { phase: 6, name: 'Language Cloud Foundation' },
        { phase: 7, name: 'Language Registry' },
        { phase: 8, name: 'Translation Engine' },
        { phase: 9, name: 'Localization Platform' },
        { phase: 10, name: 'Grammar Intelligence' },
        { phase: 11, name: 'Style Intelligence' },
        { phase: 12, name: 'Language Intelligence' },
        { phase: 13, name: 'Translation Memory' },
        { phase: 14, name: 'Language Analytics' },
        { phase: 15, name: 'Language Cloud Production Audit' },
      ],
    },
    {
      volume: 2,
      title: 'SPEECH CLOUD',
      phases: [
        { phase: 16, name: 'Speech Cloud Foundation' },
        { phase: 17, name: 'Speech Recognition Engine' },
        { phase: 18, name: 'Speaker Intelligence' },
        { phase: 19, name: 'Accent Intelligence' },
        { phase: 20, name: 'Emotion Intelligence' },
        { phase: 21, name: 'Audio Intelligence' },
        { phase: 22, name: 'Pronunciation Intelligence' },
        { phase: 23, name: 'Wake Word & Keyword Intelligence' },
        { phase: 24, name: 'Call Intelligence' },
        { phase: 25, name: 'Speech Analytics' },
        { phase: 26, name: 'Speech Cloud Production Audit' },
      ],
    },
    {
      volume: 3,
      title: 'VOICE CLOUD',
      phases: [
        { phase: 27, name: 'Voice Cloud Foundation' },
        { phase: 28, name: 'Neural Text-to-Speech' },
        { phase: 29, name: 'Voice Cloning Platform' },
        { phase: 30, name: 'Emotion Voice Engine' },
        { phase: 31, name: 'Voice Studio' },
        { phase: 32, name: 'Voice Enhancement Platform' },
        { phase: 33, name: 'Voice Biometrics' },
        { phase: 34, name: 'Voice Marketplace' },
        { phase: 35, name: 'Voice Analytics' },
        { phase: 36, name: 'Voice Cloud Production Audit' },
      ],
    },
    {
      volume: 4,
      title: 'VISION CLOUD',
      phases: [
        { phase: 37, name: 'Vision Cloud Foundation' },
        { phase: 38, name: 'OCR Engine' },
        { phase: 39, name: 'Document Intelligence' },
        { phase: 40, name: 'Invoice Intelligence' },
        { phase: 41, name: 'Identity Document Intelligence' },
        { phase: 42, name: 'Image Intelligence' },
        { phase: 43, name: 'Image Translation' },
        { phase: 44, name: 'Visual Search' },
        { phase: 45, name: 'Vision Analytics' },
        { phase: 46, name: 'Vision Cloud Production Audit' },
      ],
    },
    {
      volume: 5,
      title: 'INTELLIGENCE CLOUD',
      phases: [
        { phase: 47, name: 'Intelligence Cloud Foundation' },
        { phase: 48, name: 'Embedding Cloud' },
        { phase: 49, name: 'Vector Cloud' },
        { phase: 50, name: 'Memory Cloud' },
        { phase: 51, name: 'Knowledge Graph Cloud' },
        { phase: 52, name: 'Context Engine' },
        { phase: 53, name: 'Reasoning Cloud' },
        { phase: 54, name: 'Recommendation Engine' },
        { phase: 55, name: 'Prompt Intelligence' },
        { phase: 56, name: 'AI Decision Engine' },
        { phase: 57, name: 'AI Orchestration' },
        { phase: 58, name: 'Intelligence Analytics' },
        { phase: 59, name: 'Intelligence Cloud Production Audit' },
      ],
    },
    {
      volume: 6,
      title: 'KNOWLEDGE CLOUD',
      phases: [
        { phase: 60, name: 'Knowledge Cloud Foundation' },
        { phase: 61, name: 'Enterprise Knowledge Base' },
        { phase: 62, name: 'Enterprise Search' },
        { phase: 63, name: 'Ontology Platform' },
        { phase: 64, name: 'Taxonomy Platform' },
        { phase: 65, name: 'Enterprise RAG Platform' },
        { phase: 66, name: 'Knowledge Memory' },
        { phase: 67, name: 'Knowledge Intelligence' },
        { phase: 68, name: 'Enterprise Knowledge APIs' },
        { phase: 69, name: 'Knowledge Analytics' },
        { phase: 70, name: 'Knowledge Cloud Production Audit' },
      ],
    },
    {
      volume: 7,
      title: 'INFERENCE CLOUD',
      phases: [
        { phase: 71, name: 'Inference Cloud Foundation' },
        { phase: 72, name: 'GPU Platform' },
        { phase: 73, name: 'Model Serving' },
        { phase: 74, name: 'AI Router' },
        { phase: 75, name: 'Streaming Runtime' },
        { phase: 76, name: 'Batch Runtime' },
        { phase: 77, name: 'Intelligent Cache' },
        { phase: 78, name: 'Cost Optimization Engine' },
        { phase: 79, name: 'AI Runtime Analytics' },
        { phase: 80, name: 'Inference Cloud Production Audit' },
      ],
    },
    {
      volume: 8,
      title: 'VERBALAB AI KERNEL',
      phases: [
        { phase: 81, name: 'AI Kernel Foundation' },
        { phase: 82, name: 'Memory Runtime' },
        { phase: 83, name: 'Prompt Runtime' },
        { phase: 84, name: 'Context Runtime' },
        { phase: 85, name: 'Reasoning Runtime' },
        { phase: 86, name: 'Agent Runtime' },
        { phase: 87, name: 'Workflow Runtime' },
        { phase: 88, name: 'Plugin Runtime' },
        { phase: 89, name: 'Policy Runtime' },
        { phase: 90, name: 'Kernel Production Audit' },
      ],
    },
    {
      volume: 9,
      title: 'FOUNDATION MODEL CLOUD',
      phases: [
        { phase: 91, name: 'Foundation Model Cloud Foundation' },
        { phase: 92, name: 'Atlas' },
        { phase: 93, name: 'Baobab' },
        { phase: 94, name: 'Echo' },
        { phase: 95, name: 'Voice' },
        { phase: 96, name: 'Vision' },
        { phase: 97, name: 'Vector' },
        { phase: 98, name: 'Reason' },
        { phase: 99, name: 'Edge' },
        { phase: 100, name: 'Fusion' },
        { phase: 101, name: 'Translate' },
        { phase: 102, name: 'Model Training Platform' },
        { phase: 103, name: 'Model Evaluation Platform' },
        { phase: 104, name: 'Model Registry' },
        { phase: 105, name: 'Foundation Model Cloud Production Audit' },
      ],
    },
    {
      volume: 10,
      title: 'AI FABRIC CLOUD',
      phases: [
        { phase: 106, name: 'AI Fabric Foundation' },
        { phase: 107, name: 'Event Fabric' },
        { phase: 108, name: 'Context Fabric' },
        { phase: 109, name: 'Knowledge Fabric' },
        { phase: 110, name: 'Prompt Fabric' },
        { phase: 111, name: 'Reasoning Fabric' },
        { phase: 112, name: 'Memory Fabric' },
        { phase: 113, name: 'Agent Fabric' },
        { phase: 114, name: 'Policy Fabric' },
        { phase: 115, name: 'AI Fabric Production Audit' },
      ],
    },
    {
      volume: 11,
      title: 'ECOSYSTEM CLOUD',
      phases: [
        { phase: 116, name: 'Ecosystem Foundation' },
        { phase: 117, name: 'Plugin Marketplace' },
        { phase: 118, name: 'Model Marketplace' },
        { phase: 119, name: 'Dataset Marketplace' },
        { phase: 120, name: 'Prompt Marketplace' },
        { phase: 121, name: 'Agent Marketplace' },
        { phase: 122, name: 'Workflow Marketplace' },
        { phase: 123, name: 'Connector Marketplace' },
        { phase: 124, name: 'Voice & Language Marketplace' },
        { phase: 125, name: 'Creator Economy' },
        { phase: 126, name: 'Ecosystem Production Audit' },
      ],
    },
    {
      volume: 12,
      title: 'AFRICAN INTELLIGENCE CLOUD',
      phases: [
        { phase: 127, name: 'African Intelligence Cloud Foundation' },
        { phase: 128, name: 'African Language Registry' },
        { phase: 129, name: 'Cultural Intelligence Platform' },
        { phase: 130, name: 'African Knowledge Graph' },
        { phase: 131, name: 'Government Intelligence' },
        { phase: 132, name: 'Healthcare Intelligence' },
        { phase: 133, name: 'Financial Intelligence' },
        { phase: 134, name: 'Education Intelligence' },
        { phase: 135, name: 'Agricultural Intelligence' },
        { phase: 136, name: 'Tourism & Heritage Intelligence' },
        { phase: 137, name: 'African Intelligence Production Audit' },
      ],
    },
    {
      volume: 13,
      title: 'RESEARCH CLOUD',
      phases: [
        { phase: 138, name: 'Research Cloud Foundation' },
        { phase: 139, name: 'Experiment Platform' },
        { phase: 140, name: 'Synthetic Data Platform' },
        { phase: 141, name: 'Benchmark Platform' },
        { phase: 142, name: 'Evaluation Platform' },
        { phase: 143, name: 'AI Publication Platform' },
        { phase: 144, name: 'Patent & Innovation Platform' },
        { phase: 145, name: 'Open Science Platform' },
        { phase: 146, name: 'Research Analytics' },
        { phase: 147, name: 'Research Cloud Production Audit' },
      ],
    },
    {
      volume: 14,
      title: 'MLOPS & LLMOPS CLOUD',
      phases: [
        { phase: 148, name: 'MLOps & LLMOps Foundation' },
        { phase: 149, name: 'Dataset Pipeline' },
        { phase: 150, name: 'Training Pipeline' },
        { phase: 151, name: 'Continuous Evaluation' },
        { phase: 152, name: 'PromptOps Platform' },
        { phase: 153, name: 'RAGOps Platform' },
        { phase: 154, name: 'AgentOps Platform' },
        { phase: 155, name: 'AI Drift Detection' },
        { phase: 156, name: 'Continuous Learning' },
        { phase: 157, name: 'AI Operations Dashboard' },
        { phase: 158, name: 'MLOps Production Audit' },
      ],
    },
    {
      volume: 15,
      title: 'TRUST CLOUD',
      phases: [
        { phase: 159, name: 'Trust Cloud Foundation' },
        { phase: 160, name: 'AI Safety Platform' },
        { phase: 161, name: 'AI Governance Platform' },
        { phase: 162, name: 'Explainability Platform' },
        { phase: 163, name: 'Privacy Platform' },
        { phase: 164, name: 'Compliance Platform' },
        { phase: 165, name: 'Risk Intelligence' },
        { phase: 166, name: 'Identity Federation' },
        { phase: 167, name: 'Trust Analytics' },
        { phase: 168, name: 'Trust Cloud Production Audit' },
      ],
    },
    {
      volume: 16,
      title: 'PLATFORM ENGINEERING CLOUD',
      phases: [
        { phase: 169, name: 'Platform Engineering Foundation' },
        { phase: 170, name: 'Internal Developer Portal' },
        { phase: 171, name: 'Service Catalog' },
        { phase: 172, name: 'Golden Path Platform' },
        { phase: 173, name: 'GitOps Platform' },
        { phase: 174, name: 'Release Engineering' },
        { phase: 175, name: 'Reliability Engineering' },
        { phase: 176, name: 'FinOps Platform' },
        { phase: 177, name: 'Supply Chain Security' },
        { phase: 178, name: 'Developer Experience Platform' },
        { phase: 179, name: 'Platform Engineering Analytics' },
        { phase: 180, name: 'Platform Engineering Production Audit' },
      ],
    },
    {
      volume: 17,
      title: 'CONTROL PLANE CLOUD',
      phases: [
        { phase: 181, name: 'Control Plane Foundation' },
        { phase: 182, name: 'Organization Control' },
        { phase: 183, name: 'Global Configuration Platform' },
        { phase: 184, name: 'Global Policy Engine' },
        { phase: 185, name: 'Global Deployment Controller' },
        { phase: 186, name: 'Global Routing Controller' },
        { phase: 187, name: 'Secrets & Certificate Platform' },
        { phase: 188, name: 'Global Scheduler' },
        { phase: 189, name: 'Control Plane Analytics' },
        { phase: 190, name: 'Control Plane Production Audit' },
      ],
    },
    {
      volume: 18,
      title: 'DATA PLANE CLOUD',
      phases: [
        { phase: 191, name: 'Data Plane Foundation' },
        { phase: 192, name: 'Translation Runtime' },
        { phase: 193, name: 'Speech Runtime' },
        { phase: 194, name: 'Voice Runtime' },
        { phase: 195, name: 'Vision Runtime' },
        { phase: 196, name: 'Knowledge Runtime' },
        { phase: 197, name: 'Embedding Runtime' },
        { phase: 198, name: 'Streaming Runtime' },
        { phase: 199, name: 'GPU Runtime' },
        { phase: 200, name: 'Data Plane Production Audit' },
      ],
    },
    {
      volume: 19,
      title: 'VERBALAB AI OPERATING SYSTEM (VAIOS)',
      phases: [
        { phase: 201, name: 'VAIOS Foundation' },
        { phase: 202, name: 'AI Scheduler' },
        { phase: 203, name: 'Runtime Manager' },
        { phase: 204, name: 'Resource Manager' },
        { phase: 205, name: 'Workflow Operating System' },
        { phase: 206, name: 'Agent Operating System' },
        { phase: 207, name: 'AI Memory Operating System' },
        { phase: 208, name: 'Knowledge Operating System' },
        { phase: 209, name: 'Plugin Operating System' },
        { phase: 210, name: 'VAIOS Production Audit' },
      ],
    },
    {
      volume: 20,
      title: 'ENTERPRISE ENGINEERING SYSTEM (EES)',
      phases: [
        { phase: 211, name: 'Enterprise Engineering Foundation' },
        { phase: 212, name: 'Engineering Governance' },
        { phase: 213, name: 'Architecture Governance' },
        { phase: 214, name: 'Repository Standards' },
        { phase: 215, name: 'Engineering Quality Platform' },
        { phase: 216, name: 'AI Engineering Standards' },
        { phase: 217, name: 'API Engineering Standards' },
        { phase: 218, name: 'Database Engineering Standards' },
        { phase: 219, name: 'Infrastructure Engineering Standards' },
        { phase: 220, name: 'Engineering Production Audit' },
      ],
    },
    {
      volume: 21,
      title: 'VERBALAB CORPORATE OPERATING SYSTEM (VCOS)',
      phases: [
        { phase: 221, name: 'Corporate Operating System Foundation' },
        { phase: 222, name: 'Corporate Governance Platform' },
        { phase: 223, name: 'Strategic Planning Platform' },
        { phase: 224, name: 'Enterprise Portfolio Management' },
        { phase: 225, name: 'Business Architecture' },
        { phase: 226, name: 'Enterprise Architecture Repository' },
        { phase: 227, name: 'Corporate Knowledge System' },
        { phase: 228, name: 'Executive Intelligence Platform' },
        { phase: 229, name: 'Corporate Risk Platform' },
        { phase: 230, name: 'VCOS Production Audit' },
      ],
    },
    {
      volume: 22,
      title: 'VERBALAB GLOBAL AI STANDARD (VGAS)',
      phases: [
        { phase: 231, name: 'Global AI Standards Foundation' },
        { phase: 232, name: 'AI Certification Platform' },
        { phase: 233, name: 'AI Compliance Framework' },
        { phase: 234, name: 'Reference Architectures' },
        { phase: 235, name: 'Best Practices Library' },
        { phase: 236, name: 'Enterprise Assessment Platform' },
        { phase: 237, name: 'Standards Repository' },
        { phase: 238, name: 'Global Partner Program' },
        { phase: 239, name: 'Standards Analytics' },
        { phase: 240, name: 'Global Standards Production Audit' },
      ],
    },
    {
      volume: 23,
      title: 'VERBALAB AI ECONOMY',
      phases: [
        { phase: 241, name: 'AI Economy Foundation' },
        { phase: 242, name: 'AI Commerce Platform' },
        { phase: 243, name: 'AI Licensing Platform' },
        { phase: 244, name: 'Revenue Sharing Platform' },
        { phase: 245, name: 'AI Talent Platform' },
        { phase: 246, name: 'Research Funding Platform' },
        { phase: 247, name: 'Global Community Platform' },
        { phase: 248, name: 'AI Investment Platform' },
        { phase: 249, name: 'Economic Intelligence' },
        { phase: 250, name: 'AI Economy Production Audit' },
      ],
    },
    {
      volume: 24,
      title: 'VERBALAB DIGITAL CIVILIZATION',
      phases: [
        { phase: 251, name: 'Civilization Foundation' },
        { phase: 252, name: 'National AI Platform' },
        { phase: 253, name: 'Smart City Platform' },
        { phase: 254, name: 'Enterprise Nation Platform' },
        { phase: 255, name: 'Global Language Preservation' },
        { phase: 256, name: 'Universal Translation Grid' },
        { phase: 257, name: 'Global Knowledge Network' },
        { phase: 258, name: 'Global AI Federation' },
        { phase: 259, name: 'Civilization Intelligence Dashboard' },
        { phase: 260, name: 'Civilization Production Audit' },
      ],
    },
  ];
}

export function libraryReferenceSummary() {
  const volumes = libraryReferenceVolumes();
  const phaseCount = volumes.reduce((n, v) => n + v.phases.length, 0);
  return {
    libraryVersion: 'v2.0',
    volumeCount: volumes.length,
    phaseCount,
    executableThroughPhase: 260,
    visionBeyondPhase: '261–300 AI Internet (not packaged as executable phases)',
    honesty: libraryReferenceHonesty(),
  };
}

export function libraryReferenceProducts() {
  return [
    { id: 'master-phase-index', name: 'Master Phase Index', status: 'shipped' as const, api: 'GET /v1/library-reference/index', console: '/library-reference', notes: 'Volumes 1–24 / phases through 260.' },
    { id: 'deeper-risk-notes', name: 'Deeper Risk Notes', status: 'shipped' as const, api: 'GET /v1/library-reference/risks', console: '/library-reference', notes: 'Five flagged risk areas across the library.' },
    { id: 'ai-internet-vision', name: 'AI Internet Vision (raw)', status: 'shipped' as const, api: 'GET /v1/library-reference/vision', console: '/library-reference', notes: 'Vision feature names only — not executable phases.' },
    { id: 'mission-control-recommendation', name: 'Mission Control Recommendation', status: 'shipped' as const, api: 'GET /v1/library-reference/vision', console: '/library-reference', notes: 'Author closing advice catalogued as reference — not a shipped product claim.' },
  ];
}

export function libraryReferenceRiskAreas() {
  return [
    { id: 'vol11-creator-economy', volume: 11, phase: 125, title: 'Creator Economy payouts/tax', severity: 'high', summary: 'Route money through Stripe Connect; do not invent tax engines.', safeBuild: 'ledger + UI + processor integration' },
    { id: 'vol12-cultural-consent', volume: 12, phase: 129, title: 'Cultural knowledge consent/provenance', severity: 'high', summary: 'consentStatus must default to not-granted; human process required.', safeBuild: 'schema + enforcement + audit' },
    { id: 'vol17-control-plane-blast', volume: 17, phase: 187, title: 'Secrets/CA blast radius', severity: 'critical', summary: 'Paranoid defaults; second human review before prod.', safeBuild: 'short-lived creds + allow-lists + audit logs' },
    { id: 'vol23-investment-platform', volume: 23, phase: 248, title: 'Investment Platform ambiguity', severity: 'critical', summary: 'Dashboard-only unless legal structures a funding portal.', safeBuild: 'investmentDashboardOnly=true' },
    { id: 'vol24-public-safety', volume: 24, phase: 252, title: 'Gov/courts/police/emergency', severity: 'critical', summary: 'Demo platforms only; live use needs legal/gov/safety review.', safeBuild: 'productionCourtPoliceMilitary/Emergency/CitizenID=false' },
  ];
}

export function libraryReferenceVision() {
  return {
    label: 'Version 5.0 VerbaLab AI Internet (raw)',
    executablePhases: false,
    phaseRangeClaimed: '261–300',
    note: 'Flat feature-name list only — not packaged as Cursor phases. Do not mark Done without a real spec.',
    features: [
      'AI DNS',
      'AI Identity',
      'AI Discovery',
      'AI Federation',
      'Agent-to-Agent Communication Protocol',
      'Cross-Platform AI Messaging',
      'AI Service Discovery',
      'AI Memory Exchange',
      'AI Knowledge Exchange',
      'AI Trust Network',
      'AI Reputation Network',
      'AI Payment Network',
      'AI Identity Wallet',
      'AI Credential Exchange',
      'AI Digital Signatures',
      'AI Contract Protocol',
      'AI Resource Discovery',
      'AI Capability Registry',
      'AI Marketplace Federation',
      'AI Governance Federation',
      'AI Audit Federation',
      'AI Certificate Authority',
      'AI Global Routing',
      'AI Edge Federation',
      'AI Multi-cloud Fabric',
      'AI Sovereignty Exchange',
      'AI Policy Exchange',
      'AI Compliance Exchange',
      'AI Model Federation',
      'AI Runtime Federation',
      'AI Global Control Network',
    ],
    sixRepoRecommendation: [
      'verbalab-platform',
      'verbalab-clouds',
      'verbalab-models',
      'verbalab-research',
      'verbalab-sdk',
      'verbalab-docs',
    ],
    missionControl: 'Unified internal command center recommendation — vision, not shipped OS claim.',
    honesty: libraryReferenceHonesty(),
    docs: '/docs/library-reference/AI_INTERNET_AND_BEYOND_RAW.md',
  };
}
