
export type AfricanLanguageStatus = 'shipped' | 'partial' | 'deferred';

export type AfricanLanguageEntry = {
  code: string;
  name: string;
  family: string;
  writingSystems: string[];
  dialects: string[];
  regions: string[];
  status: AfricanLanguageStatus;
  notes: string;
};

/**
 * Library Phase 128 → African Language Registry (VL-261).
 * Curated major-language seed derived from LANGUAGE_SEEDS — coverageComplete=false.
 * Not every African micro-language; country packs + major spoken languages are seeded.
 */
export function africanLanguageSeed(): AfricanLanguageEntry[] {
  return [
    {
      code: 'sw',
      name: 'Swahili',
      family: 'Niger-Congo / Bantu',
      writingSystems: ['Latin'],
      dialects: ['Kiunguja', 'Kimvita', 'Kiamu', 'Kenyan Swahili', 'Congo Swahili'],
      regions: ['East Africa', 'Central Africa'],
      status: 'shipped',
      notes: 'Representative seed — not exhaustive dialect coverage.',
    },
    {
      code: 'yo',
      name: 'Yoruba',
      family: 'Niger-Congo / Volta-Niger',
      writingSystems: ['Latin'],
      dialects: ['Oyo', 'Egba', 'Ijebu', 'Beninese Yoruba'],
      regions: ['West Africa'],
      status: 'shipped',
      notes: 'Representative seed.',
    },
    {
      code: 'am',
      name: 'Amharic',
      family: 'Afro-Asiatic / Semitic',
      writingSystems: ['Geʽez / Fidel'],
      dialects: ['Addis', 'Gojjam', 'Wollo'],
      regions: ['Horn of Africa'],
      status: 'shipped',
      notes: 'Representative seed.',
    },
    {
      code: 'ha',
      name: 'Hausa',
      family: 'Afro-Asiatic / Chadic',
      writingSystems: ['Latin', 'Ajami'],
      dialects: ['Kano', 'Sokoto', 'Katsina'],
      regions: ['West Africa', 'Sahel'],
      status: 'shipped',
      notes: 'Representative seed.',
    },
    {
      code: 'zu',
      name: 'Zulu',
      family: 'Niger-Congo / Bantu',
      writingSystems: ['Latin'],
      dialects: ['Standard Zulu'],
      regions: ['Southern Africa'],
      status: 'shipped',
      notes: 'Representative seed.',
    },
    {
      code: 'ig',
      name: 'Igbo',
      family: 'Niger-Congo / Volta-Niger',
      writingSystems: ['Latin'],
      dialects: ['Central Igbo', 'Onitsha', 'Owerri'],
      regions: ['West Africa'],
      status: 'shipped',
      notes: 'Representative seed.',
    },
    {
      code: 'so',
      name: 'Somali',
      family: 'Afro-Asiatic / Cushitic',
      writingSystems: ['Latin', 'Osmanya'],
      dialects: ['Northern', 'Benadir', 'Maay'],
      regions: ['Horn of Africa'],
      status: 'shipped',
      notes: 'Representative seed.',
    },
    {
      code: 'ar-maghreb',
      name: 'Maghrebi Arabic',
      family: 'Afro-Asiatic / Semitic',
      writingSystems: ['Arabic'],
      dialects: ['Darija (Morocco)', 'Tunisian', 'Algerian', 'Libyan', 'Hassaniya', 'Sudanese'],
      regions: ['North Africa', 'Sahel'],
      status: 'shipped',
      notes:
        'Macro-variety index for Maghrebi/North African Arabic — ISO aliases ary/arq/aeb/ayl/mey/apd; country dialects ar-ma/ar-tn/ar-dz/ar-ly/ar-sd/mey-mr.',
    },
    {
      code: 'fr-africa',
      name: 'African French',
      family: 'Indo-European / Romance (African varieties)',
      writingSystems: ['Latin'],
      dialects: ['West African French', 'Central African French', 'Maghrebi French'],
      regions: ['West Africa', 'Central Africa', 'North Africa'],
      status: 'shipped',
      notes:
        'Macro-variety index for African French contact varieties — see fr-sn/fr-ci/fr-ma/fr-dz/fr-tn/fr-mr accent seeds and country tags fr-MA/fr-DZ/fr-TN/fr-MR.',
    },
    {
      code: 'en-africa',
      name: 'African English',
      family: 'Indo-European / Germanic (African varieties)',
      writingSystems: ['Latin'],
      dialects: ['Nigerian English', 'Kenyan English', 'South African English', 'Ghanaian English', 'Ugandan English'],
      regions: ['West Africa', 'East Africa', 'Southern Africa'],
      status: 'shipped',
      notes:
        'Macro-variety index for African English contact varieties — not exhaustive; see en-* accent/dialect seeds.',
    },
    {
      code: 'xh',
      name: 'Xhosa',
      family: 'Niger-Congo / Bantu',
      writingSystems: ['Latin'],
      dialects: ['isiXhosa (standard)', 'Ngqika', 'Gcaleka'],
      regions: ['Southern Africa'],
      status: 'shipped',
      notes: 'Official SA language; click consonants in orthography.',
    },
    {
      code: 'af',
      name: 'Afrikaans',
      family: 'Indo-European / Germanic',
      writingSystems: ['Latin'],
      dialects: ['Standard Afrikaans', 'Kaaps'],
      regions: ['Southern Africa'],
      status: 'shipped',
      notes: 'Representative seed for ZA/NA.',
    },
    {
      code: 'ak',
      name: 'Akan',
      family: 'Niger-Congo / Kwa',
      writingSystems: ['Latin'],
      dialects: ['Asante Twi', 'Akuapem Twi', 'Fante'],
      regions: ['West Africa'],
      status: 'shipped',
      notes: 'Macrolanguage covering Twi/Fante; see tw/fat seeds.',
    },
    {
      code: 'tw',
      name: 'Twi',
      family: 'Niger-Congo / Kwa',
      writingSystems: ['Latin'],
      dialects: ['Asante', 'Akuapem'],
      regions: ['West Africa'],
      status: 'shipped',
      notes: 'Major Akan variety in Ghana.',
    },
    {
      code: 'ee',
      name: 'Ewe',
      family: 'Niger-Congo / Gbe',
      writingSystems: ['Latin'],
      dialects: ['Anlo', 'Tongu', 'Inland Ewe'],
      regions: ['West Africa'],
      status: 'shipped',
      notes: 'Ghana/Togo national language.',
    },
    {
      code: 'gaa',
      name: 'Ga',
      family: 'Niger-Congo / Kwa',
      writingSystems: ['Latin'],
      dialects: ['Standard Ga'],
      regions: ['West Africa'],
      status: 'shipped',
      notes: 'Greater Accra major language.',
    },
    {
      code: 'dag',
      name: 'Dagbani',
      family: 'Niger-Congo / Gur',
      writingSystems: ['Latin'],
      dialects: ['Tomosili', 'Nayahili'],
      regions: ['West Africa'],
      status: 'shipped',
      notes: 'Northern Ghana major language.',
    },
    {
      code: 'wo',
      name: 'Wolof',
      family: 'Niger-Congo / Atlantic',
      writingSystems: ['Latin', 'Ajami'],
      dialects: ['Dakar Wolof', 'Rural Wolof'],
      regions: ['West Africa'],
      status: 'shipped',
      notes: 'Senegal lingua franca.',
    },
    {
      code: 'bm',
      name: 'Bambara',
      family: 'Niger-Congo / Mande',
      writingSystems: ['Latin', 'N\'Ko'],
      dialects: ['Standard Bambara', 'Urban Bamako'],
      regions: ['West Africa'],
      status: 'shipped',
      notes: 'Mali lingua franca.',
    },
    {
      code: 'ff',
      name: 'Fulah',
      family: 'Niger-Congo / Atlantic',
      writingSystems: ['Latin', 'Ajami', 'Adlam'],
      dialects: ['Pulaar', 'Fulfulde', 'Maasina'],
      regions: ['West Africa', 'Sahel', 'Central Africa'],
      status: 'shipped',
      notes: 'Macrolanguage across the Sahel — variety depends on country.',
    },
    {
      code: 'ln',
      name: 'Lingala',
      family: 'Niger-Congo / Bantu',
      writingSystems: ['Latin'],
      dialects: ['Kinshasa Lingala', 'Brazzaville Lingala'],
      regions: ['Central Africa'],
      status: 'shipped',
      notes: 'Congo basin urban lingua franca.',
    },
    {
      code: 'rw',
      name: 'Kinyarwanda',
      family: 'Niger-Congo / Bantu',
      writingSystems: ['Latin'],
      dialects: ['Standard Kinyarwanda'],
      regions: ['East Africa'],
      status: 'shipped',
      notes: 'Rwanda national language.',
    },
    {
      code: 'rn',
      name: 'Kirundi',
      family: 'Niger-Congo / Bantu',
      writingSystems: ['Latin'],
      dialects: ['Standard Kirundi'],
      regions: ['East Africa'],
      status: 'shipped',
      notes: 'Burundi national language; close to Kinyarwanda.',
    },
    {
      code: 'lg',
      name: 'Ganda (Luganda)',
      family: 'Niger-Congo / Bantu',
      writingSystems: ['Latin'],
      dialects: ['Standard Luganda'],
      regions: ['East Africa'],
      status: 'shipped',
      notes: 'Central Uganda major lingua franca.',
    },
    {
      code: 'om',
      name: 'Oromo',
      family: 'Afro-Asiatic / Cushitic',
      writingSystems: ['Latin'],
      dialects: ['West Central', 'Eastern', 'Southern'],
      regions: ['Horn of Africa'],
      status: 'shipped',
      notes: 'Largest mother tongue in Ethiopia.',
    },
    {
      code: 'ti',
      name: 'Tigrinya',
      family: 'Afro-Asiatic / Semitic',
      writingSystems: ['Geʽez / Fidel'],
      dialects: ['Eritrean', 'Tigray'],
      regions: ['Horn of Africa'],
      status: 'shipped',
      notes: 'ER/ET major language.',
    },
    {
      code: 'ny',
      name: 'Chichewa',
      family: 'Niger-Congo / Bantu',
      writingSystems: ['Latin'],
      dialects: ['Malawian Chewa', 'Zambian Nyanja'],
      regions: ['Southern Africa', 'East Africa'],
      status: 'shipped',
      notes: 'Malawi national language; also Zambia/Mozambique.',
    },
    {
      code: 'sn',
      name: 'Shona',
      family: 'Niger-Congo / Bantu',
      writingSystems: ['Latin'],
      dialects: ['Zezuru', 'Karanga', 'Manyika'],
      regions: ['Southern Africa'],
      status: 'shipped',
      notes: 'Zimbabwe major language.',
    },
    {
      code: 'nso',
      name: 'Northern Sotho',
      family: 'Niger-Congo / Bantu',
      writingSystems: ['Latin'],
      dialects: ['Sepedi'],
      regions: ['Southern Africa'],
      status: 'shipped',
      notes: 'Official SA language.',
    },
    {
      code: 'tn',
      name: 'Tswana',
      family: 'Niger-Congo / Bantu',
      writingSystems: ['Latin'],
      dialects: ['Setswana (ZA)', 'Setswana (BW)'],
      regions: ['Southern Africa'],
      status: 'shipped',
      notes: 'Botswana national language; also SA official.',
    },
    {
      code: 'st',
      name: 'Southern Sotho',
      family: 'Niger-Congo / Bantu',
      writingSystems: ['Latin'],
      dialects: ['Lesotho Sesotho', 'Free State Sesotho'],
      regions: ['Southern Africa'],
      status: 'shipped',
      notes: 'Lesotho national language; SA official.',
    },
    {
      code: 'ss',
      name: 'Swati',
      family: 'Niger-Congo / Bantu',
      writingSystems: ['Latin'],
      dialects: ['siSwati'],
      regions: ['Southern Africa'],
      status: 'shipped',
      notes: 'Eswatini / SA official.',
    },
    {
      code: 'ts',
      name: 'Tsonga',
      family: 'Niger-Congo / Bantu',
      writingSystems: ['Latin'],
      dialects: ['Xitsonga'],
      regions: ['Southern Africa'],
      status: 'shipped',
      notes: 'SA/MZ border language.',
    },
    {
      code: 've',
      name: 'Venda',
      family: 'Niger-Congo / Bantu',
      writingSystems: ['Latin'],
      dialects: ['Tshivenḓa'],
      regions: ['Southern Africa'],
      status: 'shipped',
      notes: 'Official SA language.',
    },
    {
      code: 'mg',
      name: 'Malagasy',
      family: 'Austronesian / Malayo-Polynesian',
      writingSystems: ['Latin'],
      dialects: ['Merina', 'Betsimisaraka', 'Sakalava'],
      regions: ['East Africa'],
      status: 'shipped',
      notes: 'Madagascar national language — Austronesian in Africa.',
    },
    {
      code: 'ber',
      name: 'Berber (Tamazight)',
      family: 'Afro-Asiatic / Berber',
      writingSystems: ['Latin', 'Tifinagh'],
      dialects: ['Macro Amazigh'],
      regions: ['North Africa'],
      status: 'shipped',
      notes: 'Macrolanguage index — prefer tzm/shi/rif/kab/zgh when the variety is known.',
    },
    {
      code: 'kab',
      name: 'Kabyle',
      family: 'Afro-Asiatic / Berber',
      writingSystems: ['Latin', 'Tifinagh'],
      dialects: ['Kabyle'],
      regions: ['North Africa'],
      status: 'shipped',
      notes: 'Major Algerian Amazigh variety; dialect/accent kab-dz.',
    },
    {
      code: 'tzm',
      name: 'Central Atlas Tamazight',
      family: 'Afro-Asiatic / Berber',
      writingSystems: ['Latin', 'Tifinagh'],
      dialects: ['Central Atlas'],
      regions: ['North Africa'],
      status: 'shipped',
      notes: 'Moroccan Amazigh variety; dialect/accent tzm-ma.',
    },
    {
      code: 'shi',
      name: 'Tachelhit',
      family: 'Afro-Asiatic / Berber',
      writingSystems: ['Latin', 'Tifinagh', 'Arabic'],
      dialects: ['Souss'],
      regions: ['North Africa'],
      status: 'shipped',
      notes: 'Southern Morocco Amazigh variety; dialect/accent shi-ma.',
    },
    {
      code: 'zgh',
      name: 'Standard Moroccan Tamazight',
      family: 'Afro-Asiatic / Berber',
      writingSystems: ['Tifinagh', 'Latin'],
      dialects: ['Standard (IRCAM)'],
      regions: ['North Africa'],
      status: 'shipped',
      notes: 'Standardized Moroccan Amazigh; dialect/accent zgh-ma.',
    },
    {
      code: 'rif',
      name: 'Tarifit',
      family: 'Afro-Asiatic / Berber',
      writingSystems: ['Latin', 'Tifinagh'],
      dialects: ['Rif'],
      regions: ['North Africa'],
      status: 'shipped',
      notes: 'Northern Morocco Amazigh variety; dialect/accent rif-ma.',
    },
    {
      code: 'mey',
      name: 'Hassaniya Arabic',
      family: 'Afro-Asiatic / Semitic',
      writingSystems: ['Arabic'],
      dialects: ['Mauritanian Hassaniya'],
      regions: ['North Africa', 'West Africa', 'Sahel'],
      status: 'shipped',
      notes: 'ISO 639-3 mey; dialect/accent mey-mr; locale pack ar-MR.',
    },
    {
      code: 'ary',
      name: 'Moroccan Arabic',
      family: 'Afro-Asiatic / Semitic',
      writingSystems: ['Arabic'],
      dialects: ['Darija'],
      regions: ['North Africa'],
      status: 'shipped',
      notes: 'ISO 639-3 alias for Moroccan Darija; related dialect ar-ma; locale pack ar-MA.',
    },
    {
      code: 'arq',
      name: 'Algerian Arabic',
      family: 'Afro-Asiatic / Semitic',
      writingSystems: ['Arabic'],
      dialects: ['Algerian Darija'],
      regions: ['North Africa'],
      status: 'shipped',
      notes: 'ISO 639-3 alias; related dialect/accent ar-dz; locale pack ar-DZ.',
    },
    {
      code: 'aeb',
      name: 'Tunisian Arabic',
      family: 'Afro-Asiatic / Semitic',
      writingSystems: ['Arabic'],
      dialects: ['Tunisian Darija'],
      regions: ['North Africa'],
      status: 'shipped',
      notes: 'ISO 639-3 alias; related dialect/accent ar-tn; locale pack ar-TN.',
    },
    {
      code: 'ayl',
      name: 'Libyan Arabic',
      family: 'Afro-Asiatic / Semitic',
      writingSystems: ['Arabic'],
      dialects: ['Libyan Arabic'],
      regions: ['North Africa'],
      status: 'shipped',
      notes: 'ISO 639-3 alias; related dialect/accent ar-ly; locale pack ar-LY.',
    },
    {
      code: 'apd',
      name: 'Sudanese Arabic',
      family: 'Afro-Asiatic / Semitic',
      writingSystems: ['Arabic'],
      dialects: ['Sudanese Arabic'],
      regions: ['East Africa', 'North Africa'],
      status: 'shipped',
      notes: 'ISO 639-3 alias; related dialect/accent ar-sd; locale pack ar-SD.',
    },
    {
      code: 'luo',
      name: 'Luo (Dholuo)',
      family: 'Nilo-Saharan / Nilotic',
      writingSystems: ['Latin'],
      dialects: ['Kenyan Luo'],
      regions: ['East Africa'],
      status: 'shipped',
      notes: 'Nilo-Saharan representative in Kenya/Tanzania.',
    },
    {
      code: 'din',
      name: 'Dinka',
      family: 'Nilo-Saharan / Nilotic',
      writingSystems: ['Latin'],
      dialects: ['Rek', 'Agar', 'Bor'],
      regions: ['East Africa'],
      status: 'shipped',
      notes: 'South Sudan major language.',
    },
    {
      code: 'nus',
      name: 'Nuer',
      family: 'Nilo-Saharan / Nilotic',
      writingSystems: ['Latin'],
      dialects: ['Western Nuer', 'Eastern Nuer'],
      regions: ['East Africa'],
      status: 'shipped',
      notes: 'South Sudan / Ethiopia border language.',
    },
    {
      code: 'kr',
      name: 'Kanuri',
      family: 'Nilo-Saharan / Saharan',
      writingSystems: ['Latin', 'Ajami'],
      dialects: ['Yerwa', 'Manga'],
      regions: ['West Africa', 'Sahel'],
      status: 'shipped',
      notes: 'Lake Chad basin major language.',
    },
    {
      code: 'naq',
      name: 'Nama (Khoekhoegowab)',
      family: 'Khoisan',
      writingSystems: ['Latin'],
      dialects: ['Nama', 'Damara'],
      regions: ['Southern Africa'],
      status: 'shipped',
      notes: 'Khoisan click-language representative (Namibia).',
    },
    {
      code: 'pcm',
      name: 'Nigerian Pidgin',
      family: 'Indo-European / English-based creole',
      writingSystems: ['Latin'],
      dialects: ['Lagos Pidgin', 'Warri Pidgin'],
      regions: ['West Africa'],
      status: 'shipped',
      notes: 'Widely spoken Nigerian lingua franca.',
    },
    {
      code: 'umb',
      name: 'Umbundu',
      family: 'Niger-Congo / Bantu',
      writingSystems: ['Latin'],
      dialects: ['Standard Umbundu'],
      regions: ['Southern Africa'],
      status: 'shipped',
      notes: 'Angola major national language.',
    },
    {
      code: 'kmb',
      name: 'Kimbundu',
      family: 'Niger-Congo / Bantu',
      writingSystems: ['Latin'],
      dialects: ['Standard Kimbundu'],
      regions: ['Southern Africa'],
      status: 'shipped',
      notes: 'Angola major national language (Luanda region).',
    },
    {
      code: 'bem',
      name: 'Bemba',
      family: 'Niger-Congo / Bantu',
      writingSystems: ['Latin'],
      dialects: ['Standard Bemba'],
      regions: ['Southern Africa'],
      status: 'shipped',
      notes: 'Zambia major language.',
    },
    {
      code: 'vmw',
      name: 'Makhuwa',
      family: 'Niger-Congo / Bantu',
      writingSystems: ['Latin'],
      dialects: ['Central Makhuwa'],
      regions: ['Southern Africa'],
      status: 'shipped',
      notes: 'Mozambique major language.',
    },
    {
      code: 'fon',
      name: 'Fon',
      family: 'Niger-Congo / Gbe',
      writingSystems: ['Latin'],
      dialects: ['Standard Fon'],
      regions: ['West Africa'],
      status: 'shipped',
      notes: 'Benin major national language.',
    },
    {
      code: 'mos',
      name: 'Mossi (Mooré)',
      family: 'Niger-Congo / Gur',
      writingSystems: ['Latin'],
      dialects: ['Central Mooré'],
      regions: ['West Africa'],
      status: 'shipped',
      notes: 'Burkina Faso major language.',
    },
    {
      code: 'sg',
      name: 'Sango',
      family: 'Niger-Congo / Ubangi',
      writingSystems: ['Latin'],
      dialects: ['Standard Sango'],
      regions: ['Central Africa'],
      status: 'shipped',
      notes: 'CAR national lingua franca.',
    },
    {
      code: 'ki',
      name: 'Kikuyu',
      family: 'Niger-Congo / Bantu',
      writingSystems: ['Latin'],
      dialects: ['Standard Gĩkũyũ'],
      regions: ['East Africa'],
      status: 'shipped',
      notes: 'Kenya major language.',
    },
    {
      code: 'ach',
      name: 'Acholi',
      family: 'Nilo-Saharan / Nilotic',
      writingSystems: ['Latin'],
      dialects: ['Ugandan Acholi'],
      regions: ['East Africa'],
      status: 'shipped',
      notes: 'Northern Uganda major language.',
    },
    {
      code: 'nyn',
      name: 'Nyankole',
      family: 'Niger-Congo / Bantu',
      writingSystems: ['Latin'],
      dialects: ['Runyankore'],
      regions: ['East Africa'],
      status: 'shipped',
      notes: 'Western Uganda major language.',
    },
    {
      code: 'mfe',
      name: 'Morisyen',
      family: 'Indo-European / French-based creole',
      writingSystems: ['Latin'],
      dialects: ['Standard Morisien'],
      regions: ['East Africa'],
      status: 'shipped',
      notes: 'Mauritius everyday lingua franca.',
    },
    {
      code: 'kea',
      name: 'Kabuverdianu',
      family: 'Indo-European / Portuguese-based creole',
      writingSystems: ['Latin'],
      dialects: ['Sotavento', 'Barlavento'],
      regions: ['West Africa'],
      status: 'shipped',
      notes: 'Cabo Verde dominant spoken language.',
    },
    {
      code: 'kri',
      name: 'Krio',
      family: 'Indo-European / English-based creole',
      writingSystems: ['Latin'],
      dialects: ['Freetown Krio'],
      regions: ['West Africa'],
      status: 'shipped',
      notes: 'Sierra Leone lingua franca.',
    },
    {
      code: 'aa',
      name: 'Afar',
      family: 'Afro-Asiatic / Cushitic',
      writingSystems: ['Latin'],
      dialects: ['Northern Afar', 'Southern Afar'],
      regions: ['Horn of Africa'],
      status: 'shipped',
      notes: 'Djibouti/Eritrea/Ethiopia Cushitic language.',
    },
    {
      code: 'kj',
      name: 'Kuanyama',
      family: 'Niger-Congo / Bantu',
      writingSystems: ['Latin'],
      dialects: ['Oshikwanyama'],
      regions: ['Southern Africa'],
      status: 'shipped',
      notes: 'Oshiwambo variety — Namibia/Angola.',
    },
    {
      code: 'dje',
      name: 'Zarma',
      family: 'Nilo-Saharan / Songhay',
      writingSystems: ['Latin'],
      dialects: ['Standard Zarma'],
      regions: ['West Africa', 'Sahel'],
      status: 'shipped',
      notes: 'Niger major language.',
    },
    {
      code: 'tmh',
      name: 'Tamasheq',
      family: 'Afro-Asiatic / Berber',
      writingSystems: ['Latin', 'Tifinagh'],
      dialects: ['Tuareg varieties'],
      regions: ['West Africa', 'Sahel', 'North Africa'],
      status: 'shipped',
      notes: 'Tuareg Amazigh macrolanguage representative.',
    },
  ];
}

export function africanLanguageFamilies() {
  return [
    { id: 'niger-congo', name: 'Niger-Congo', note: 'Largest family represented in seed (Bantu + Volta-Niger + Kwa + Atlantic + Mande + Gur).' },
    { id: 'afro-asiatic', name: 'Afro-Asiatic', note: 'Semitic, Chadic, Cushitic, and Berber representatives in seed.' },
    { id: 'nilo-saharan', name: 'Nilo-Saharan', note: 'Nilotic and Saharan representatives (Luo, Dinka, Nuer, Kanuri, Zarma).' },
    { id: 'khoisan', name: 'Khoisan', note: 'Click-language cluster representative (Nama); not an exhaustive genetic claim.' },
    { id: 'austronesian', name: 'Austronesian', note: 'Malagasy — Austronesian language of Madagascar.' },
    { id: 'indo-european-african', name: 'Indo-European (African varieties)', note: 'fr-africa / en-africa / Afrikaans / creoles contact varieties.' },
  ];
}

export function africanLanguageRegistryEngineCatalog() {
  const languages = africanLanguageSeed();
  return {
    product: 'VerbaLab African Language Registry',
    note:
      'African Language Registry. Curated major-language seed extending dialects/locales. coverageComplete=false — Africa country packs and major spoken languages are seeded; micro-languages may still expand. Not an Ethnologue dump.',
    capabilities: [
      {
        id: 'language-catalog',
        name: 'Language Catalog',
        status: 'shipped',
        api: 'GET /v1/african-language-registry/languages',
        notes: 'Seeded major spoken languages with family metadata.',
      },
      {
        id: 'dialect-index',
        name: 'Dialect Index',
        status: 'shipped',
        api: 'GET /v1/african-language-registry/languages',
        notes: 'Seed dialect names on registry entries — not an Ethnologue dialect atlas.',
      },
      {
        id: 'writing-systems',
        name: 'Writing Systems',
        status: 'shipped',
        api: 'GET /v1/african-language-registry/languages',
        notes: 'Latin, Geʽez, Ajami, Arabic, Osmanya, Tifinagh, Adlam, N\'Ko represented in seed.',
      },
      {
        id: 'family-metadata',
        name: 'Family Metadata',
        status: 'shipped',
        api: 'GET /v1/african-language-registry/families',
        notes: 'High-level family groups for the seed set including Nilo-Saharan, Khoisan, Austronesian.',
      },
    ],
    languages,
    families: africanLanguageFamilies(),
    architecture: {
      style: 'nest_modular_monolith',
      cqrs: true,
      hexagonalRewrite: false,
      extendsDialects: true,
      extendsLocales: true,
      regeneratesVolumes1to11: false,
      coverageComplete: false,
    },
    honesty: {
      coverageComplete: false,
      everyAfricanLanguageComplete: false,
      regeneratesVolumes1to11: false,
      extendsDialectsLocales: true,
      africaCountryPacksComplete: true,
      majorSpokenLanguagesSeeded: true,
      note:
        'Africa-complete for AU country packs and major spoken languages; micro-languages and full dialect atlases may still expand. Not Ethnologue-complete.',
    },
    docs: '/docs/AFRICAN_LANGUAGE_REGISTRY.md',
  };
}
