export type WorldLanguageStatus = 'shipped' | 'partial' | 'deferred';

export type WorldLanguageEntry = {
  code: string;
  name: string;
  family: string;
  writingSystems: string[];
  dialects: string[];
  regions: string[];
  status: WorldLanguageStatus;
  notes: string;
};

/**
 * World Language Registry — SEA / India / LatAm / Caribbean parallel to African Language Registry.
 * Curated major-language seed derived from GLOBAL_LANGUAGE_SEEDS — coverageComplete=false.
 */
export function worldLanguageSeed(): WorldLanguageEntry[] {
  return [
    {
      code: 'th',
      name: 'Thai',
      family: 'Tai-Kadai',
      writingSystems: ['Thai'],
      dialects: ['Central Thai', 'Northern Thai (Lanna)', 'Isan', 'Southern Thai'],
      regions: ['Southeast Asia'],
      status: 'shipped',
      notes: 'Central Thai public-sector baseline; particles (krub/ka) matter for politeness.',
    },
    {
      code: 'vi',
      name: 'Vietnamese',
      family: 'Austroasiatic',
      writingSystems: ['Latin'],
      dialects: ['Northern (Hanoi)', 'Central (Hue)', 'Southern (Saigon)'],
      regions: ['Southeast Asia'],
      status: 'shipped',
      notes: 'Tone-marked Latin orthography; Northern broadcast standard common in civic UX.',
    },
    {
      code: 'tl',
      name: 'Tagalog / Filipino',
      family: 'Austronesian',
      writingSystems: ['Latin'],
      dialects: ['Manila Tagalog', 'Batangas', 'Taglish continuum'],
      regions: ['Southeast Asia'],
      status: 'shipped',
      notes: 'po/opo respect markers; Taglish continuum with English.',
    },
    {
      code: 'ms',
      name: 'Malay',
      family: 'Austronesian',
      writingSystems: ['Latin'],
      dialects: ['Peninsular Malay', 'Brunei Malay', 'Singapore Malay'],
      regions: ['Southeast Asia'],
      status: 'shipped',
      notes: 'Closely related to Indonesian (id); keep locale-specific civic terms.',
    },
    {
      code: 'km',
      name: 'Khmer',
      family: 'Austroasiatic',
      writingSystems: ['Khmer'],
      dialects: ['Standard Khmer', 'Northern Khmer'],
      regions: ['Southeast Asia'],
      status: 'shipped',
      notes: 'Representative seed.',
    },
    {
      code: 'lo',
      name: 'Lao',
      family: 'Tai-Kadai',
      writingSystems: ['Lao'],
      dialects: ['Vientiane Lao', 'Northern Lao'],
      regions: ['Southeast Asia'],
      status: 'shipped',
      notes: 'Closely related to Isan Thai varieties.',
    },
    {
      code: 'my',
      name: 'Burmese',
      family: 'Sino-Tibetan',
      writingSystems: ['Myanmar'],
      dialects: ['Yangon', 'Mandalay'],
      regions: ['Southeast Asia'],
      status: 'shipped',
      notes: 'Representative seed.',
    },
    {
      code: 'jv',
      name: 'Javanese',
      family: 'Austronesian',
      writingSystems: ['Latin', 'Javanese'],
      dialects: ['Central Javanese', 'East Javanese'],
      regions: ['Southeast Asia'],
      status: 'shipped',
      notes: 'Speech levels (krama/ngoko) matter for respect.',
    },
    {
      code: 'su',
      name: 'Sundanese',
      family: 'Austronesian',
      writingSystems: ['Latin'],
      dialects: ['Priangan'],
      regions: ['Southeast Asia'],
      status: 'shipped',
      notes: 'Representative seed.',
    },
    {
      code: 'ceb',
      name: 'Cebuano',
      family: 'Austronesian',
      writingSystems: ['Latin'],
      dialects: ['Cebu', 'Mindanao Cebuano'],
      regions: ['Southeast Asia'],
      status: 'shipped',
      notes: 'Major Visayan language.',
    },
    {
      code: 'hil',
      name: 'Hiligaynon',
      family: 'Austronesian',
      writingSystems: ['Latin'],
      dialects: ['Iloilo', 'Bacolod'],
      regions: ['Southeast Asia'],
      status: 'shipped',
      notes: 'Also known as Ilonggo.',
    },
    {
      code: 'war',
      name: 'Waray',
      family: 'Austronesian',
      writingSystems: ['Latin'],
      dialects: ['Tacloban Waray'],
      regions: ['Southeast Asia'],
      status: 'shipped',
      notes: 'Representative seed.',
    },
    {
      code: 'yue',
      name: 'Cantonese',
      family: 'Sino-Tibetan',
      writingSystems: ['Traditional Chinese', 'Latin (jyutping)'],
      dialects: ['Hong Kong Cantonese', 'Guangzhou Cantonese'],
      regions: ['Southeast Asia', 'East Asia'],
      status: 'shipped',
      notes: 'Spoken Cantonese + Traditional Chinese UI for HK.',
    },
    {
      code: 'hi-india',
      name: 'Indian Hindi',
      family: 'Indo-European / Indo-Aryan',
      writingSystems: ['Devanagari'],
      dialects: ['Standard Hindi', 'Hinglish continuum', 'Bhojpuri-adjacent'],
      regions: ['South Asia'],
      status: 'shipped',
      notes: 'Macro-variety index — ISO hi plus Hinglish continuum; honorific plural forms.',
    },
    {
      code: 'bn',
      name: 'Bengali',
      family: 'Indo-European / Indo-Aryan',
      writingSystems: ['Bengali'],
      dialects: ['Standard Bangla', 'Chittagonian-adjacent', 'Sylheti-adjacent'],
      regions: ['South Asia'],
      status: 'shipped',
      notes: 'Bangladesh + West Bengal varieties.',
    },
    {
      code: 'ta',
      name: 'Tamil',
      family: 'Dravidian',
      writingSystems: ['Tamil'],
      dialects: ['Indian Tamil', 'Sri Lankan Tamil', 'Singapore/Malaysia Tamil'],
      regions: ['South Asia', 'Southeast Asia'],
      status: 'shipped',
      notes: 'Respectful plural address; diglossia literary vs spoken.',
    },
    {
      code: 'te',
      name: 'Telugu',
      family: 'Dravidian',
      writingSystems: ['Telugu'],
      dialects: ['Coastal Andhra', 'Telangana'],
      regions: ['South Asia'],
      status: 'shipped',
      notes: 'Representative seed.',
    },
    {
      code: 'mr',
      name: 'Marathi',
      family: 'Indo-European / Indo-Aryan',
      writingSystems: ['Devanagari'],
      dialects: ['Standard Marathi', 'Varhadi'],
      regions: ['South Asia'],
      status: 'shipped',
      notes: 'Representative seed.',
    },
    {
      code: 'gu',
      name: 'Gujarati',
      family: 'Indo-European / Indo-Aryan',
      writingSystems: ['Gujarati'],
      dialects: ['Standard Gujarati', 'Surti'],
      regions: ['South Asia'],
      status: 'shipped',
      notes: 'Representative seed.',
    },
    {
      code: 'kn',
      name: 'Kannada',
      family: 'Dravidian',
      writingSystems: ['Kannada'],
      dialects: ['Mysore', 'Dharwad'],
      regions: ['South Asia'],
      status: 'shipped',
      notes: 'Representative seed.',
    },
    {
      code: 'ml',
      name: 'Malayalam',
      family: 'Dravidian',
      writingSystems: ['Malayalam'],
      dialects: ['Central Kerala', 'Malabar'],
      regions: ['South Asia'],
      status: 'shipped',
      notes: 'Representative seed.',
    },
    {
      code: 'pa',
      name: 'Punjabi',
      family: 'Indo-European / Indo-Aryan',
      writingSystems: ['Gurmukhi', 'Shahmukhi'],
      dialects: ['Majhi', 'Doabi'],
      regions: ['South Asia'],
      status: 'shipped',
      notes: 'India Gurmukhi + Pakistan Shahmukhi continua.',
    },
    {
      code: 'or',
      name: 'Odia',
      family: 'Indo-European / Indo-Aryan',
      writingSystems: ['Odia'],
      dialects: ['Standard Odia'],
      regions: ['South Asia'],
      status: 'shipped',
      notes: 'Representative seed.',
    },
    {
      code: 'as',
      name: 'Assamese',
      family: 'Indo-European / Indo-Aryan',
      writingSystems: ['Bengali-Assamese'],
      dialects: ['Standard Assamese'],
      regions: ['South Asia'],
      status: 'shipped',
      notes: 'Representative seed.',
    },
    {
      code: 'ur',
      name: 'Urdu',
      family: 'Indo-European / Indo-Aryan',
      writingSystems: ['Arabic (Nastaliq)'],
      dialects: ['Standard Urdu', 'Dakhini'],
      regions: ['South Asia'],
      status: 'shipped',
      notes: 'RTL; closely related to Hindi with distinct script/register.',
    },
    {
      code: 'ne',
      name: 'Nepali',
      family: 'Indo-European / Indo-Aryan',
      writingSystems: ['Devanagari'],
      dialects: ['Kathmandu', 'Eastern Nepali'],
      regions: ['South Asia'],
      status: 'shipped',
      notes: 'Representative seed.',
    },
    {
      code: 'si',
      name: 'Sinhala',
      family: 'Indo-European / Indo-Aryan',
      writingSystems: ['Sinhala'],
      dialects: ['Colombo', 'Up-country'],
      regions: ['South Asia'],
      status: 'shipped',
      notes: 'Representative seed.',
    },
    {
      code: 'bho',
      name: 'Bhojpuri',
      family: 'Indo-European / Indo-Aryan',
      writingSystems: ['Devanagari'],
      dialects: ['Standard Bhojpuri', 'Caribbean Bhojpuri heritage'],
      regions: ['South Asia', 'Caribbean'],
      status: 'shipped',
      notes: 'Also spoken in diaspora (Trinidad, Mauritius, Fiji).',
    },
    {
      code: 'qu',
      name: 'Quechua',
      family: 'Quechuan',
      writingSystems: ['Latin'],
      dialects: ['Cusco Quechua', 'Ayacucho', 'Bolivian Quechua'],
      regions: ['Latin America'],
      status: 'shipped',
      notes: 'Andean respectful address; keep place/personal names stable across Spanish bridges.',
    },
    {
      code: 'gn',
      name: 'Guarani',
      family: 'Tupian',
      writingSystems: ['Latin'],
      dialects: ['Paraguayan Guarani', 'Jopara continuum'],
      regions: ['Latin America'],
      status: 'shipped',
      notes: 'Co-official in Paraguay; Spanish-Guarani mixing common.',
    },
    {
      code: 'ay',
      name: 'Aymara',
      family: 'Aymaran',
      writingSystems: ['Latin'],
      dialects: ['Southern Aymara', 'Central Aymara'],
      regions: ['Latin America'],
      status: 'shipped',
      notes: 'Bolivia / Peru / Chile Altiplano.',
    },
    {
      code: 'nhe',
      name: 'Eastern Huasteca Nahuatl',
      family: 'Uto-Aztecan',
      writingSystems: ['Latin'],
      dialects: ['Huasteca'],
      regions: ['Latin America'],
      status: 'shipped',
      notes: 'Representative Nahuatl seed — not every variety.',
    },
    {
      code: 'yua',
      name: 'Yucatec Maya',
      family: 'Mayan',
      writingSystems: ['Latin'],
      dialects: ['Yucatan', 'Quintana Roo'],
      regions: ['Latin America'],
      status: 'shipped',
      notes: 'Representative seed.',
    },
    {
      code: 'ht',
      name: 'Haitian Creole',
      family: 'French-based Creole',
      writingSystems: ['Latin'],
      dialects: ['Port-au-Prince', 'Northern Haitian'],
      regions: ['Caribbean'],
      status: 'shipped',
      notes: 'Kreyol everyday vs French formal continuum.',
    },
    {
      code: 'jam',
      name: 'Jamaican Creole',
      family: 'English-based Creole',
      writingSystems: ['Latin'],
      dialects: ['Kingston Patwa', 'Rural Patwa'],
      regions: ['Caribbean'],
      status: 'shipped',
      notes: 'English–Patwa continuum; offer both registers in civic UX.',
    },
    {
      code: 'pap',
      name: 'Papiamento',
      family: 'Iberian-based Creole',
      writingSystems: ['Latin'],
      dialects: ['Aruba', 'Curaçao', 'Bonaire'],
      regions: ['Caribbean'],
      status: 'shipped',
      notes: 'ABC islands; spelling norms differ by island.',
    },
    {
      code: 'gcf',
      name: 'Guadeloupean Creole',
      family: 'French-based Creole',
      writingSystems: ['Latin'],
      dialects: ['Guadeloupe', 'Martinique-adjacent'],
      regions: ['Caribbean'],
      status: 'shipped',
      notes: 'Antillean French Creole continuum.',
    },
    {
      code: 'es-latam',
      name: 'Latin American Spanish',
      family: 'Indo-European / Romance (LatAm varieties)',
      writingSystems: ['Latin'],
      dialects: ['Mexican', 'Andean', 'Rioplatense', 'Caribbean Spanish', 'Spanglish continuum'],
      regions: ['Latin America', 'Caribbean'],
      status: 'shipped',
      notes: 'Macro-variety index — do not force Mexican tú forms globally; voseo in Southern Cone.',
    },
    {
      code: 'pt-br-sphere',
      name: 'Brazilian Portuguese',
      family: 'Indo-European / Romance (Brazilian varieties)',
      writingSystems: ['Latin'],
      dialects: ['Carioca', 'Paulista', 'Nordestino'],
      regions: ['Latin America'],
      status: 'shipped',
      notes: 'Macro-variety index for BR Portuguese (not PT-PT).',
    },
    {
      code: 'en-sea',
      name: 'Southeast Asian English',
      family: 'Indo-European / Germanic (SEA varieties)',
      writingSystems: ['Latin'],
      dialects: ['Singapore English', 'Malaysian English', 'Philippine English'],
      regions: ['Southeast Asia'],
      status: 'shipped',
      notes: 'Macro-variety index for SEA English contact varieties.',
    },
    {
      code: 'en-india',
      name: 'Indian English',
      family: 'Indo-European / Germanic (South Asian varieties)',
      writingSystems: ['Latin'],
      dialects: ['Indian English', 'Hinglish continuum'],
      regions: ['South Asia'],
      status: 'shipped',
      notes: 'Macro-variety index — Indian English lexical norms + Hinglish.',
    },
    {
      code: 'en-caribbean',
      name: 'Caribbean English',
      family: 'Indo-European / Germanic (Caribbean varieties)',
      writingSystems: ['Latin'],
      dialects: ['Jamaican English', 'Trinidadian English', 'Eastern Caribbean'],
      regions: ['Caribbean'],
      status: 'shipped',
      notes: 'Macro-variety index on the English–creole continuum.',
    },
  ];
}

export function worldLanguageFamilies() {
  return [
    { id: 'tai-kadai', name: 'Tai-Kadai', note: 'Thai, Lao and related varieties.' },
    { id: 'austroasiatic', name: 'Austroasiatic', note: 'Vietnamese, Khmer representatives.' },
    { id: 'austronesian', name: 'Austronesian', note: 'Malay, Tagalog, Javanese, Visayan languages.' },
    { id: 'sino-tibetan', name: 'Sino-Tibetan', note: 'Burmese and Cantonese representatives.' },
    { id: 'dravidian', name: 'Dravidian', note: 'Tamil, Telugu, Kannada, Malayalam.' },
    { id: 'indo-aryan', name: 'Indo-Aryan', note: 'Hindi/Bengali/Marathi/Urdu and related South Asian languages.' },
    { id: 'quechuan-aymaran', name: 'Quechuan / Aymaran', note: 'Andean indigenous language families.' },
    { id: 'tupian-mayan-uto', name: 'Tupian / Mayan / Uto-Aztecan', note: 'Guarani, Yucatec Maya, Nahuatl representatives.' },
    { id: 'creole', name: 'Creole', note: 'Haitian, Jamaican, Papiamento, Guadeloupean creoles.' },
    { id: 'romance-global', name: 'Romance (regional varieties)', note: 'es-latam / pt-br-sphere macro-varieties.' },
  ];
}

export function worldLanguageRegistryEngineCatalog() {
  const languages = worldLanguageSeed();
  return {
    product: 'VerbaLab World Language Registry',
    note:
      'World Language Registry for SEA, India/South Asia, Latin America, and Caribbean. Curated major-language seed with culture/dialect/writing-system metadata. coverageComplete=false — not Ethnologue-complete.',
    capabilities: [
      {
        id: 'language-catalog',
        name: 'Language Catalog',
        status: 'shipped',
        api: 'GET /v1/world-language-registry/languages',
        notes: 'Seeded strategic global languages with family metadata.',
      },
      {
        id: 'dialect-index',
        name: 'Dialect Index',
        status: 'shipped',
        api: 'GET /v1/world-language-registry/languages',
        notes: 'Seed dialect names on registry entries — not a full dialect atlas.',
      },
      {
        id: 'writing-systems',
        name: 'Writing Systems',
        status: 'shipped',
        api: 'GET /v1/world-language-registry/languages',
        notes: 'Thai, Khmer, Myanmar, Indic scripts, Latin creoles, Traditional Chinese represented.',
      },
      {
        id: 'family-metadata',
        name: 'Family Metadata',
        status: 'shipped',
        api: 'GET /v1/world-language-registry/families',
        notes: 'High-level family groups including Dravidian, Quechuan, and Creole.',
      },
      {
        id: 'culture-people',
        name: 'Culture & People Links',
        status: 'shipped',
        api: 'GET /v1/country-packs',
        notes: 'Country packs + cultural intelligence for TH/VN/PH/IN/MX/HT/JM and related markets.',
      },
    ],
    languages,
    families: worldLanguageFamilies(),
    architecture: {
      style: 'nest_modular_monolith',
      cqrs: true,
      hexagonalRewrite: false,
      extendsDialects: true,
      extendsLocales: true,
      parallelToAfricanRegistry: true,
      coverageComplete: false,
    },
    honesty: {
      coverageComplete: false,
      everyWorldLanguageComplete: false,
      extendsDialectsLocales: true,
      globalCountryPacksSeeded: true,
      majorSpokenLanguagesSeeded: true,
      note:
        'Strategic global markets seeded for SEA / India / LatAm / Caribbean with country packs, dialects, accents, culture, and grammar. Not Ethnologue-complete.',
    },
    docs: '/docs/WORLD_LANGUAGE_REGISTRY.md',
  };
}
