import type { GlossarySnapshotTerm } from '../glossary/glossary-snapshot-install';

export type VerticalGlossaryPack = {
  id: string;
  vertical: 'public-sector' | 'healthcare' | 'banking' | 'education' | 'agriculture' | 'legal';
  title: string;
  description: string;
  sourceLang: string;
  targetLang: string;
  licenseTag: string;
  terms: GlossarySnapshotTerm[];
};

function pair(
  sourceLang: string,
  targetLang: string,
  sourceTerm: string,
  targetTerm: string,
): GlossarySnapshotTerm {
  return {
    sourceLang,
    targetLang,
    sourceTerm,
    targetTerm,
    caseSensitive: false,
    wholeWord: true,
  };
}

function t(sourceLang: string, targetLang: string, sourceTerm: string, targetTerm: string) {
  return pair(sourceLang, targetLang, sourceTerm, targetTerm);
}

const enSw = (s: string, tg: string) => t('en', 'sw', s, tg);
const enYo = (s: string, tg: string) => t('en', 'yo', s, tg);
const enHa = (s: string, tg: string) => t('en', 'ha', s, tg);
const enAm = (s: string, tg: string) => t('en', 'am', s, tg);
const enZu = (s: string, tg: string) => t('en', 'zu', s, tg);
const enAr = (s: string, tg: string) => t('en', 'ar', s, tg);
const enTh = (s: string, tg: string) => t('en', 'th', s, tg);
const enVi = (s: string, tg: string) => t('en', 'vi', s, tg);
const enHi = (s: string, tg: string) => t('en', 'hi', s, tg);
const enHt = (s: string, tg: string) => t('en', 'ht', s, tg);

/** Platform starter packs — Africa-first + strategic-global vertical terminology (VL-103). Free-tier installable. */
export const VERTICAL_GLOSSARY_PACKS: VerticalGlossaryPack[] = [
  {
    id: 'public-sector-en-sw',
    vertical: 'public-sector',
    title: 'Public sector (EN→SW)',
    description: 'Citizen services, administration, and official communications.',
    sourceLang: 'en',
    targetLang: 'sw',
    licenseTag: 'proprietary',
    terms: [
      enSw('citizen', 'raia'), enSw('government', 'serikali'), enSw('ministry', 'wizara'),
      enSw('municipality', 'manispaa'), enSw('district', 'wilaya'), enSw('ward', 'kata'),
      enSw('identity card', 'kitambulisho'), enSw('passport', 'pasipoti'),
      enSw('birth certificate', 'cheti cha kuzaliwa'), enSw('application form', 'fomu ya maombi'),
      enSw('public notice', 'tangazo la umma'), enSw('hearing', 'usikilizaji'),
      enSw('complaint', 'malalamiko'), enSw('office hours', 'saa za ofisi'),
      enSw('civil servant', 'mtumishi wa umma'), enSw('election', 'uchaguzi'),
      enSw('voter registration', 'usajili wa wapiga kura'), enSw('tax office', 'ofisi ya kodi'),
      enSw('permit', 'kibali'), enSw('license', 'leseni'), enSw('regulation', 'kanuni'),
      enSw('policy', 'sera'), enSw('emergency services', 'huduma za dharura'),
      enSw('police station', 'kituo cha polisi'), enSw('court', 'mahakama'),
    ],
  },
  {
    id: 'healthcare-en-sw',
    vertical: 'healthcare',
    title: 'Healthcare (EN→SW)',
    description: 'Clinical and patient-facing terms for clinics and hospitals.',
    sourceLang: 'en',
    targetLang: 'sw',
    licenseTag: 'proprietary',
    terms: [
      enSw('clinic', 'kliniki'), enSw('hospital', 'hospitali'), enSw('patient', 'mgonjwa'),
      enSw('nurse', 'muuguzi'), enSw('doctor', 'daktari'), enSw('pharmacy', 'duka la dawa'),
      enSw('prescription', 'maagizo ya daktari'), enSw('appointment', 'miadi'),
      enSw('emergency room', 'chumba cha dharura'), enSw('blood pressure', 'shinikizo la damu'),
      enSw('vaccination', 'chanjo'), enSw('symptoms', 'dalili'), enSw('diagnosis', 'utambuzi'),
      enSw('treatment', 'matibabu'), enSw('referral', 'rufaa'), enSw('laboratory', 'maabara'),
      enSw('medical record', 'rekodi ya matibabu'), enSw('consent form', 'fomu ya idhini'),
      enSw('outpatient', 'mgonjwa wa nje'), enSw('inpatient', 'mgonjwa wa ndani'),
      enSw('maternity ward', 'wodi ya uzazi'), enSw('ambulance', 'ambulansi'),
      enSw('infection', 'maambukizi'), enSw('chronic disease', 'ugonjwa sugu'),
      enSw('mental health', 'afya ya akili'),
    ],
  },
  {
    id: 'banking-en-sw',
    vertical: 'banking',
    title: 'Banking (EN→SW)',
    description: 'Retail banking and payments terminology.',
    sourceLang: 'en',
    targetLang: 'sw',
    licenseTag: 'proprietary',
    terms: [
      enSw('bank account', 'akaunti ya benki'), enSw('savings account', 'akaunti ya akiba'),
      enSw('current account', 'akaunti ya kawaida'), enSw('loan', 'mkopo'),
      enSw('interest rate', 'kiwango cha riba'), enSw('deposit', 'amana'),
      enSw('withdrawal', 'utoaji'), enSw('transfer', 'uhamisho'),
      enSw('mobile money', 'pesa za rununu'), enSw('ATM', 'ATM'), enSw('PIN', 'PIN'),
      enSw('statement', 'taarifa ya akaunti'), enSw('balance', 'salio'),
      enSw('overdraft', 'deni la akaunti'), enSw('collateral', 'dhamana'),
      enSw('credit score', 'alama ya mikopo'), enSw('foreign exchange', 'ubadilishaji wa fedha'),
      enSw('remittance', 'utumaji fedha'), enSw('branch', 'tawi'),
      enSw('customer service', 'huduma kwa wateja'), enSw('fraud alert', 'tahadhari ya ulaghai'),
      enSw('KYC', 'KYC'), enSw('account number', 'nambari ya akaunti'),
      enSw('transaction', 'muamala'), enSw('insurance', 'bima'),
    ],
  },
  {
    id: 'education-en-sw',
    vertical: 'education',
    title: 'Education (EN→SW)',
    description: 'Schools, exams, and learner-facing terms.',
    sourceLang: 'en',
    targetLang: 'sw',
    licenseTag: 'proprietary',
    terms: [
      enSw('school', 'shule'), enSw('student', 'mwanafunzi'), enSw('teacher', 'mwalimu'),
      enSw('classroom', 'darasa'), enSw('homework', 'kazi ya nyumbani'), enSw('exam', 'mtihani'),
      enSw('curriculum', 'mtaala'), enSw('scholarship', 'ufadhili wa masomo'),
      enSw('university', 'chuo kikuu'), enSw('primary school', 'shule ya msingi'),
      enSw('secondary school', 'shule ya sekondari'), enSw('grade', 'daraja'),
      enSw('attendance', 'mahudhurio'), enSw('parent meeting', 'mkutano wa wazazi'),
      enSw('library', 'maktaba'), enSw('textbook', 'kitabu cha kiada'),
      enSw('tuition', 'ada za shule'), enSw('diploma', 'diploma'), enSw('certificate', 'cheti'),
      enSw('graduation', 'mahitimu'), enSw('principal', 'mkuu wa shule'),
      enSw('enrollment', 'usajili'), enSw('literacy', 'ujuzi wa kusoma na kuandika'),
      enSw('vocational training', 'mafunzo ya ufundi'), enSw('distance learning', 'elimu kwa mbali'),
    ],
  },
  {
    id: 'agriculture-en-sw',
    vertical: 'agriculture',
    title: 'Agriculture (EN→SW)',
    description: 'Farming, markets, and extension services.',
    sourceLang: 'en',
    targetLang: 'sw',
    licenseTag: 'proprietary',
    terms: [
      enSw('farmer', 'mkulima'), enSw('crop', 'mazingao'), enSw('harvest', 'mavuno'),
      enSw('livestock', 'mifugo'), enSw('irrigation', 'umwagiliaji'), enSw('fertilizer', 'mbolea'),
      enSw('seed', 'mbegu'), enSw('market price', 'bei ya soko'), enSw('cooperative', 'ushirika'),
      enSw('extension officer', 'afisa wa ugani'), enSw('drought', 'ukame'),
      enSw('rainfall', 'mvua'), enSw('soil', 'udongo'), enSw('pesticide', 'dawa ya kuua wadudu'),
      enSw('warehouse', 'ghala'), enSw('dairy', 'maziwa'), enSw('poultry', 'kuku'),
      enSw('fisheries', 'uvuvi'), enSw('land title', 'hati miliki ya ardhi'),
      enSw('subsidy', 'ruzuku'), enSw('climate-smart', 'kilimo cha hali ya hewa'),
      enSw('value chain', 'mnyororo wa thamani'), enSw('post-harvest loss', 'hasara baada ya mavuno'),
      enSw('veterinary', 'mifugo na tiba'), enSw('tractor', 'trekta'),
    ],
  },
  {
    id: 'legal-en-sw',
    vertical: 'legal',
    title: 'Legal (EN→SW)',
    description: 'Courts and civic legal terminology — not legal advice.',
    sourceLang: 'en',
    targetLang: 'sw',
    licenseTag: 'proprietary',
    terms: [
      enSw('lawyer', 'mwanasheria'), enSw('judge', 'hakimu'), enSw('plaintiff', 'mlalamikaji'),
      enSw('defendant', 'mshtakiwa'), enSw('contract', 'mkataba'), enSw('affidavit', 'kiapo'),
      enSw('summons', 'wito wa mahakama'), enSw('bail', 'dhamana'), enSw('evidence', 'ushahidi'),
      enSw('verdict', 'hukumu'), enSw('appeal', 'rufaa'), enSw('constitution', 'katiba'),
      enSw('statute', 'sheria'), enSw('rights', 'haki'), enSw('witness', 'shahidi'),
      enSw('notary', 'mthibitishaji'), enSw('power of attorney', 'hati ya uwakilishi'),
      enSw('inheritance', 'urithi'), enSw('property deed', 'hati ya mali'),
      enSw('mediation', 'upatanishi'), enSw('arbitration', 'usuluhishi'),
      enSw('criminal case', 'kesi ya jinai'), enSw('civil case', 'kesi ya madai'),
      enSw('legal aid', 'msaada wa kisheria'), enSw('jurisdiction', 'mamlaka ya mahakama'),
    ],
  },
  {
    id: 'public-sector-en-yo',
    vertical: 'public-sector',
    title: 'Public sector (EN→YO)',
    description: 'Citizen services terminology for Yoruba.',
    sourceLang: 'en',
    targetLang: 'yo',
    licenseTag: 'proprietary',
    terms: [
      enYo('citizen', 'ara ilu'), enYo('government', 'ijoba'), enYo('ministry', 'ile-ise'),
      enYo('municipality', 'ijoba ibile'), enYo('identity card', 'kaadi idanimo'),
      enYo('passport', 'iwe irinna'), enYo('application form', 'foomu ibeere'),
      enYo('public notice', 'ikede'), enYo('complaint', 'edun okan'), enYo('election', 'idibo'),
      enYo('permit', 'iwe ase'), enYo('license', 'iwe ase ise'), enYo('regulation', 'ofin'),
      enYo('policy', 'eto'), enYo('police station', 'ago olopa'), enYo('court', 'ile ejo'),
      enYo('tax', 'owo ori'), enYo('birth certificate', 'iwe eri ibi'),
      enYo('civil servant', 'osisé ijoba'), enYo('district', 'agbegbe'), enYo('ward', 'adugbo'),
      enYo('hearing', 'igboro'), enYo('office hours', 'wakati ise'),
      enYo('voter registration', 'iforukosilẹ oludibo'), enYo('emergency services', 'ise pajawiri'),
    ],
  },
  {
    id: 'healthcare-en-ha',
    vertical: 'healthcare',
    title: 'Healthcare (EN→HA)',
    description: 'Clinical terms for Hausa patient-facing copy.',
    sourceLang: 'en',
    targetLang: 'ha',
    licenseTag: 'proprietary',
    terms: [
      enHa('clinic', 'asibiti karami'), enHa('hospital', 'asibiti'), enHa('patient', 'majinyaci'),
      enHa('nurse', 'ma aikaciyar jinya'), enHa('doctor', 'likita'),
      enHa('pharmacy', 'kantin magani'), enHa('prescription', 'takardar magani'),
      enHa('appointment', 'alkawari'), enHa('emergency room', 'dakin gaggawa'),
      enHa('blood pressure', 'karfin jini'), enHa('vaccination', 'allura'),
      enHa('symptoms', 'alamomi'), enHa('diagnosis', 'ganewar asali'),
      enHa('treatment', 'magani'), enHa('referral', 'turawa'), enHa('laboratory', 'dakin gwaji'),
      enHa('medical record', 'tarihin lafiya'), enHa('consent form', 'takardar yarda'),
      enHa('ambulance', 'motar asibiti'), enHa('infection', 'cutar kamuwa'),
      enHa('maternity ward', 'sashen haihuwa'), enHa('outpatient', 'majinyacin waje'),
      enHa('inpatient', 'majinyacin ciki'), enHa('chronic disease', 'cuta mai dogon zango'),
      enHa('mental health', 'lafiyar hankali'),
    ],
  },
  {
        id: 'banking-en-am',
    vertical: 'banking',
    title: 'Banking (EN\u2192AM)',
    description: 'Retail banking terms for Amharic.',
    sourceLang: 'en',
    targetLang: 'am',
    licenseTag: 'proprietary',
    terms: [
      enAm('bank account', '\u12e8\u1263\u1295\u12ad \u1202\u1233\u1265'),
      enAm('savings account', '\u12e8\u1241\u1320\u1263 \u1202\u1233\u1265'),
      enAm('current account', '\u12e8\u12a0\u1201\u1295 \u1202\u1233\u1265'),
      enAm('loan', '\u1265\u12f5\u122d'),
      enAm('interest rate', '\u12e8\u12c8\u1208\u12f5 \u1218\u1320\u1295'),
      enAm('deposit', '\u1270\u1240\u121b\u132d'),
      enAm('withdrawal', '\u121b\u12cd\u1323\u1275'),
      enAm('transfer', '\u12dd\u12cd\u12cd\u122d'),
      enAm('mobile money', '\u121e\u1263\u12ed\u120d \u1308\u1295\u12d8\u1265'),
      enAm('ATM', '\u12a4\u1272\u12a4\u121d'),
      enAm('PIN', '\u1342\u1295'),
      enAm('statement', '\u12e8\u1202\u1233\u1265 \u1218\u130d\u1208\u133b'),
      enAm('balance', '\u1240\u122a \u1202\u1233\u1265'),
      enAm('branch', '\u1245\u122d\u1295\u133b\u134b\u134d'),
      enAm('customer service', '\u12e8\u12f0\u1295\u1260\u129b \u12a0\u1308\u120d\u130d\u120e\u1275'),
      enAm('remittance', '\u1308\u1295\u12d8\u1265 \u120d\u12cd\u12cd\u1325'),
      enAm('foreign exchange', '\u12cd\u132d \u121d\u1295\u12db\u122c'),
      enAm('insurance', '\u12a2\u1295\u1239\u122b\u1295\u1235'),
      enAm('transaction', '\u130d\u1265\u12ed\u1275'),
      enAm('account number', '\u12e8\u1202\u1233\u1265 \u1241\u1325\u122d'),
      enAm('KYC', 'KYC'),
      enAm('fraud alert', '\u12e8\u121b\u132d\u1260\u122d\u1260\u122d \u121b\u1235\u1320\u1295\u1240\u1242\u12eb'),
      enAm('collateral', '\u12cb\u1235\u1275\u1293'),
      enAm('overdraft', '\u12a8\u1218\u1320\u1295 \u1260\u120b\u12ed \u12c8\u1322'),
      enAm('credit score', '\u12e8\u1265\u12f5\u122d \u1290\u1325\u1265'),
    ],
  },
  {
    id: 'public-sector-en-zu',
    vertical: 'public-sector',
    title: 'Public sector (EN→ZU)',
    description: 'Citizen services terminology for isiZulu.',
    sourceLang: 'en',
    targetLang: 'zu',
    licenseTag: 'proprietary',
    terms: [
      enZu('citizen', 'isakhamuzi'), enZu('government', 'uhulumeni'), enZu('ministry', 'umnyango'),
      enZu('municipality', 'umasipala'), enZu('identity card', 'umazisi'),
      enZu('passport', 'iphasipoti'), enZu('application form', 'ifomu lesicelo'),
      enZu('public notice', 'isaziso somphakathi'), enZu('complaint', 'isikhalazo'),
      enZu('election', 'ukhetho'), enZu('permit', 'imvume'), enZu('license', 'ilayisensi'),
      enZu('regulation', 'umthetho'), enZu('policy', 'inqubomgomo'),
      enZu('police station', 'isiteshi samaphoyisa'), enZu('court', 'inkantolo'),
      enZu('tax', 'intela'), enZu('birth certificate', 'isitifiketi sokuzalwa'),
      enZu('civil servant', 'isisebenzi sikahulumeni'), enZu('district', 'isifunda'),
      enZu('ward', 'iwadi'), enZu('hearing', 'ukulalelwa'), enZu('office hours', 'amahora omsebenzi'),
      enZu('voter registration', 'ukubhaliswa kwabavoti'),
      enZu('emergency services', 'izinsiza eziphuthumayo'),
    ],
  },
  {
    id: 'healthcare-en-ar',
    vertical: 'healthcare',
    title: 'Healthcare (EN→AR)',
    description: 'Clinical terms for Arabic (North Africa MSA-leaning).',
    sourceLang: 'en',
    targetLang: 'ar',
    licenseTag: 'proprietary',
    terms: [
      enAr('clinic', 'عيادة'), enAr('hospital', 'مستشفى'), enAr('patient', 'مريض'),
      enAr('nurse', 'ممرض'), enAr('doctor', 'طبيب'), enAr('pharmacy', 'صيدلية'),
      enAr('prescription', 'وصفة طبية'), enAr('appointment', 'موعد'),
      enAr('emergency room', 'غرفة الطوارئ'), enAr('blood pressure', 'ضغط الدم'),
      enAr('vaccination', 'تطعيم'), enAr('symptoms', 'أعراض'), enAr('diagnosis', 'تشخيص'),
      enAr('treatment', 'علاج'), enAr('referral', 'إحالة'), enAr('laboratory', 'مختبر'),
      enAr('medical record', 'سجل طبي'), enAr('consent form', 'نموذج موافقة'),
      enAr('ambulance', 'سيارة إسعاف'), enAr('infection', 'عدوى'),
      enAr('maternity ward', 'جناح الولادة'), enAr('outpatient', 'مريض خارجي'),
      enAr('inpatient', 'مريض داخلي'), enAr('chronic disease', 'مرض مزمن'),
      enAr('mental health', 'الصحة النفسية'),
    ],
  },
  {
    id: 'public-sector-en-th',
    vertical: 'public-sector',
    title: 'Public sector (EN→TH)',
    description: 'Citizen services terminology for Thai.',
    sourceLang: 'en',
    targetLang: 'th',
    licenseTag: 'proprietary',
    terms: [
      enTh('citizen', 'phonlamueang'), enTh('government', 'ratthaban'),
      enTh('ministry', 'krasuang'), enTh('identity card', 'bat pracham tua'),
      enTh('passport', 'nangsue doen thang'), enTh('application form', 'baep phor'),
      enTh('public notice', 'prakat satharana'), enTh('complaint', 'kham rongrian'),
      enTh('permit', 'bai anuyat'), enTh('tax', 'phasi'),
      enTh('police station', 'sathani tamruat'), enTh('court', 'san'),
      enTh('birth certificate', 'bai koeut'), enTh('emergency services', 'borikan chukchoen'),
      enTh('office hours', 'wela tham ngan'),
    ],
  },
  {
    id: 'public-sector-en-vi',
    vertical: 'public-sector',
    title: 'Public sector (EN→VI)',
    description: 'Citizen services terminology for Vietnamese.',
    sourceLang: 'en',
    targetLang: 'vi',
    licenseTag: 'proprietary',
    terms: [
      enVi('citizen', 'cong dan'), enVi('government', 'chinh phu'),
      enVi('ministry', 'bo'), enVi('identity card', 'can cuoc cong dan'),
      enVi('passport', 'ho chieu'), enVi('application form', 'don dang ky'),
      enVi('public notice', 'thong bao cong'), enVi('complaint', 'khieu nai'),
      enVi('permit', 'giay phep'), enVi('tax', 'thue'),
      enVi('police station', 'don canh sat'), enVi('court', 'toa an'),
      enVi('birth certificate', 'giay khai sinh'), enVi('emergency services', 'dich vu khan cap'),
      enVi('office hours', 'gio lam viec'),
    ],
  },
  {
    id: 'public-sector-en-hi',
    vertical: 'public-sector',
    title: 'Public sector (EN→HI)',
    description: 'Citizen services terminology for Hindi.',
    sourceLang: 'en',
    targetLang: 'hi',
    licenseTag: 'proprietary',
    terms: [
      enHi('citizen', 'nagarik'), enHi('government', 'sarkar'),
      enHi('ministry', 'mantralay'), enHi('identity card', 'pehchaan patra'),
      enHi('passport', 'passport'), enHi('application form', 'aavedan patra'),
      enHi('public notice', 'sarvajanik suchna'), enHi('complaint', 'shikayat'),
      enHi('permit', 'anumati'), enHi('tax', 'kar'),
      enHi('police station', 'thana'), enHi('court', 'adalat'),
      enHi('birth certificate', 'janam praman patra'), enHi('emergency services', 'apatkalin seva'),
      enHi('office hours', 'karyalay samay'),
    ],
  },
  {
    id: 'public-sector-en-ht',
    vertical: 'public-sector',
    title: 'Public sector (EN→HT)',
    description: 'Citizen services terminology for Haitian Creole.',
    sourceLang: 'en',
    targetLang: 'ht',
    licenseTag: 'proprietary',
    terms: [
      enHt('citizen', 'sitwayen'), enHt('government', 'gouvènman'),
      enHt('ministry', 'ministè'), enHt('identity card', 'kat idantite'),
      enHt('passport', 'paspò'), enHt('application form', 'fòm aplikasyon'),
      enHt('public notice', 'avi piblik'), enHt('complaint', 'plent'),
      enHt('permit', 'pèmi'), enHt('tax', 'taks'),
      enHt('police station', 'komisarya'), enHt('court', 'tribinal'),
      enHt('birth certificate', 'akt nesans'), enHt('emergency services', 'sèvis ijans'),
      enHt('office hours', 'èdtan biwo'),
    ],
  },
];

export function findVerticalPack(id: string) {
  return VERTICAL_GLOSSARY_PACKS.find((p) => p.id === id) ?? null;
}

export const VERTICAL_PREVIEW_LIMIT = 12;
