export type VcosSeed = {
  domain: string;
  kind: string;
  title: string;
  status: string;
  summary: string;
  ownerLabel: string;
  content: Record<string, unknown>;
};

/** Default African-AI-company oriented seed rows for local review. */
export function vcosDefaultSeeds(): VcosSeed[] {
  return [
    {
      domain: 'governance',
      kind: 'ai_ethics_committee',
      title: 'AI Ethics Committee — Q4 charter',
      status: 'active',
      summary: 'Tracks ethics reviews for African language models and voice cloning.',
      ownerLabel: 'Chief Ethics Officer (role)',
      content: { cadence: 'monthly', focus: ['consent', 'provenance', 'fairness'] },
    },
    {
      domain: 'governance',
      kind: 'board',
      title: 'Board pack template — voice sovereignty',
      status: 'active',
      summary: 'Agenda template for board updates on language ownership and residency.',
      ownerLabel: 'Company Secretary (role)',
      content: { sections: ['mission', 'risks', 'KPIs', 'asks'] },
    },
    {
      domain: 'strategy',
      kind: 'strategy_3y',
      title: '3-year African voice platform strategy',
      status: 'active',
      summary: 'Own speech/translate/voice stack for top African markets.',
      ownerLabel: 'CEO (role)',
      content: { horizons: ['product', 'research', 'partnerships', 'governance'] },
    },
    {
      domain: 'strategy',
      kind: 'okr',
      title: 'OKR — Swahili+Yoruba production STT quality',
      status: 'active',
      summary: 'Raise production STT quality for bilingual callers.',
      ownerLabel: 'VP Speech (role)',
      content: { keyResults: ['WER target', 'latency p95', 'accent coverage'] },
    },
    {
      domain: 'portfolio',
      kind: 'program',
      title: 'Program — Language Registry expansion',
      status: 'active',
      summary: 'Expand canonical dialect coverage across West/East/Southern Africa.',
      ownerLabel: 'Portfolio PMO (role)',
      content: { budgetUsd: 0, dependencies: ['research', 'data'] },
    },
    {
      domain: 'portfolio',
      kind: 'project',
      title: 'Project — Voice Studio lexicon v2',
      status: 'active',
      summary: 'Pronunciation lexicon for product names across markets.',
      ownerLabel: 'Voice PM (role)',
      content: { status: 'in_progress' },
    },
    {
      domain: 'capability',
      kind: 'capability',
      title: 'Capability — Multilingual customer support',
      status: 'active',
      summary: 'Business capability spanning STT, translate, and agent assist.',
      ownerLabel: 'Biz Architect (role)',
      content: { valueStreams: ['acquire', 'support', 'retain'] },
    },
    {
      domain: 'capability',
      kind: 'value_stream',
      title: 'Value stream — Creator voice publishing',
      status: 'active',
      summary: 'From script to published African-language audio.',
      ownerLabel: 'Biz Architect (role)',
      content: { stages: ['draft', 'voice', 'review', 'publish'] },
    },
    {
      domain: 'architecture',
      kind: 'application_map',
      title: 'Application map — Voice + Speech hubs',
      status: 'active',
      summary: 'Maps console hubs to runtime services for African voice workloads.',
      ownerLabel: 'Enterprise Architect (role)',
      content: { alignment: 'TOGAF-inspired catalog', modelingSuiteOs: false },
    },
    {
      domain: 'architecture',
      kind: 'technology_map',
      title: 'Technology map — VAIOS + Data Plane',
      status: 'active',
      summary: 'Links corporate capabilities to Volume 18–19 runtime planes.',
      ownerLabel: 'Enterprise Architect (role)',
      content: { planes: ['control', 'data', 'vaios'] },
    },
    {
      domain: 'knowledge',
      kind: 'policy',
      title: 'Policy — Voice clone consent',
      status: 'active',
      summary: 'Consent, watermark, and abuse-review requirements for cloning.',
      ownerLabel: 'Trust (role)',
      content: { related: ['Volume 15 Trust', 'Voice cloning ADR'] },
    },
    {
      domain: 'knowledge',
      kind: 'playbook',
      title: 'Playbook — Incident response for AI misuse',
      status: 'active',
      summary: 'Steps for moderating generated speech misuse.',
      ownerLabel: 'Security (role)',
      content: { severity: ['sev1', 'sev2', 'sev3'] },
    },
    {
      domain: 'executive',
      kind: 'corporate_kpi',
      title: 'KPI — African language coverage',
      status: 'active',
      summary: 'Languages with production STT/TTS paths.',
      ownerLabel: 'CEO cockpit',
      content: { unit: 'languages', target: 40 },
    },
    {
      domain: 'executive',
      kind: 'ai_kpi',
      title: 'KPI — Voice provenance labeling rate',
      status: 'active',
      summary: 'Share of generated audio with provenance labels.',
      ownerLabel: 'Board dashboard',
      content: { unit: 'percent', target: 100 },
    },
    {
      domain: 'risk',
      kind: 'ai_risk',
      title: 'Risk — Voice deepfake misuse',
      status: 'open',
      summary: 'Mitigate with watermarking, review gates, and abuse monitoring.',
      ownerLabel: 'Risk Committee (role)',
      content: { severity: 'high', residual: 'medium' },
    },
    {
      domain: 'risk',
      kind: 'regulatory_risk',
      title: 'Risk — Cross-border voice data residency',
      status: 'open',
      summary: 'Ensure regional deploy islands and data region pins.',
      ownerLabel: 'Compliance (role)',
      content: { severity: 'high', residual: 'medium' },
    },
    {
      domain: 'constitution',
      kind: 'mission',
      title: 'Digital Constitution — Mission',
      status: 'active',
      summary: 'Africa owns its voice — VerbaLab exists so the continent is not a speech/data colony.',
      ownerLabel: 'Founding Architect',
      content: {
        layer: 'mission',
        principles: ['language sovereignty', 'consent', 'accessibility', 'long-term stewardship'],
      },
    },
    {
      domain: 'constitution',
      kind: 'ai',
      title: 'Digital Constitution — AI',
      status: 'active',
      summary: 'Responsible AI, human oversight, evaluation, and fairness for African languages.',
      ownerLabel: 'AI Council (role)',
      content: {
        layer: 'ai',
        principles: ['human oversight', 'safety', 'fairness', 'evaluation required'],
      },
    },
    {
      domain: 'constitution',
      kind: 'data',
      title: 'Digital Constitution — Data',
      status: 'active',
      summary: 'Ownership, privacy, sovereignty, retention, and classification.',
      ownerLabel: 'Data Council (role)',
      content: {
        layer: 'data',
        principles: ['ownership', 'privacy', 'sovereignty', 'retention', 'classification'],
      },
    },
  ];
}
